:PROPERTIES:
:ID:       e83f6a87-0e50-44b4-b0e5-3ca4650fd0a6
:END:
#+TITLE: Crystal anisotropy
#+FILETAGS: :problem:
#+SETUPFILE: ../../setupfile.org

2. Crystal anisotropy: Consider a ferromagnet with a tetragonal crystal structure. Coupling of the spins to the underlying lattice may destroy their full rotational symmetry. The resulting anisotropies can be described by modifying the LandauGinzburg Hamiltonian to

\begin{align*}
\beta \mathcal{H}=\int \mathrm{d}^{d} \mathbf{x}\left[\frac{K}{2}(\nabla \vec{m})^{2}+\frac{t}{2} \vec{m}^{2}+u\left(\vec{m}^{2}\right)^{2}+\frac{r}{2} m_{1}^{2}+v m_{1}^{2} \vec{m}^{2}\right]
\end{align*}

where \(\vec{m} \equiv\left(m_{1}, \cdots, m_{n}\right)\), and \(\vec{m}^{2}=\sum_{i=1}^{n} m_{i}^{2}(d=n=3\) for magnets in three dimensions). Here \(u>0\), and to simplify calculations we shall set \(v=0\) throughout.

(a) For a fixed magnitude \(|\vec{m}|\), what directions in the \(n\) component magnetization space are selected for \(r>0\), and for \(r<0\) ?
(b) Using the saddle point approximation, calculate the free energies \((\ln Z)\) for phases uniformly magnetized parallel and perpendicular to direction 1 .

(c) Sketch the phase diagram in the \((t, r)\) plane, and indicate the phases (type of order), and the nature of the phase transitions (continuous or discontinuous).

(d) Are there Goldstone modes in the ordered phases?

(e) For \(u=0\), and positive \(t\) and \(r\), calculate the unperturbed averages \(\left\langle m_{1}(\mathbf{q}) m_{1}\left(\mathbf{q}^{\prime}\right)\right\rangle_{0}\) and \(\left\langle m_{2}(\mathbf{q}) m_{2}\left(\mathbf{q}^{\prime}\right)\right\rangle_{0}\), where \(m_{i}(\mathbf{q})\) indicates the Fourier transform of \(m_{i}(\mathbf{x})\).

(f) Write the fourth order term \(\mathcal{U} \equiv u \int \mathrm{d}^{d} \mathbf{x}\left(\vec{m}^{2}\right)^{2}\), in terms of the Fourier modes \(m_{i}(\mathbf{q})\).

(g) Treating \(\mathcal{U}\) as a perturbation, calculate the first order correction to \(\left\langle m_{1}(\mathbf{q}) m_{1}\left(\mathbf{q}^{\prime}\right)\right\rangle\). (You can leave your answers in the form of some integrals.)

(h) Treating \(\mathcal{U}\) as a perturbation, calculate the first order correction to \(\left\langle m_{2}(\mathbf{q}) m_{2}\left(\mathbf{q}^{\prime}\right)\right\rangle\)

(i) Using the above answer, identify the inverse susceptibility \(\chi_{22}^{-1}\), and then find the transition point, \(t_{c}\), from its vanishing to first order in \(u\).

(j) Is the critical behavior different from the isotropic \(O(n)\) model in \(d<4\) ? In RG language, is the parameter \(r\) relevant at the \(\mathcal{O}(n)\) fixed point? In either case indicate the universality classes expected for the transitions.

