:PROPERTIES:
:ID:       ab4f8368-2ed1-4360-a455-d869bc75e3bd
:END:
#+TITLE: Ginzburg criterion along the magnetic field direction
#+FILETAGS: :problem:critical:
#+SETUPFILE: ../../setupfile.org

* Problem Statement

8. Ginzburg criterion along the magnetic field direction: Consider the Hamiltonian

\begin{align*}
\beta \mathcal{H}=\int \mathrm{d}^{d} \mathbf{x}\left[\frac{K}{2}(\nabla \vec{m})^{2}+\frac{t}{2} \vec{m}^{2}+u\left(\vec{m}^{2}\right)^{2}-\vec{h} \cdot \vec{m}\right]
\end{align*}

describing an \(n\)-component magnetization vector \(\vec{m}(\mathbf{x})\), with \(u>0\).

(a) In the saddle point approximation, the free energy is \(f=\min \{\Psi(m)\}_{m}\). Indicate the resulting phase boundary in the \((h, t)\) plane, and label the phases. ( \(h\) denotes the magnitude of \(\vec{h}\).)

(b) Sketch the form of \(\Psi(m)\) for \(t<0\), on both sides of the phase boundary, and for \(t>0\) at \(h=0\).

(c) For \(t\) and \(h\) close to zero, the spontaneous magnetization can be written as \(\bar{m}=t^{\beta} g_{m}\left(h / t^{\Delta}\right)\). Identify the exponents \(\beta\) and \(\Delta\) in the saddle point approximation.

For the remainder of this problem set \(t=0\).

(d) Calculate the transverse and longitudinal susceptibilities at a finite \(h\).

(e) Include fluctuations by setting \(\vec{m}(\mathbf{x})=\left(\bar{m}+\phi_{\ell}(\mathbf{x})\right) \hat{e}_{\ell}+\vec{\phi}_{t}(\mathbf{x}) \hat{e}_{t}\), and expanding \(\beta \mathcal{H}\) to second order in the \(\phi \mathrm{s}\). ( \(\hat{e}_{\ell}\) is a unit vector parallel to the average magnetization, and \(\hat{e}_{t}\) is perpendicular to it.)

(f) Calculate the longitudinal and transverse correlation lengths.

(g) Calculate the first correction to the free energy from these fluctuations. (The scaling form is sufficient.)

(h) Calculate the first correction to magnetization, and to longitudinal susceptibility from the fluctuations.

(i) By comparing the saddle point value with the correction due to fluctuations, find the upper critical dimension, \(d_{u}\), for the validity of the saddle point result.

(j) For \(d<d_{u}\) obtain a Ginzburg criterion by finding the field \(h_{G}\) below which fluctuations are important. (You may ignore the numerical coefficients in \(h_{G}\), but the dependences on \(K\) and \(u\) are required.)

* Solution

* Related Concepts

