:PROPERTIES:
:ID:       4e99d122-00d5-45af-a16b-fedbe1033585
:END:
#+TITLE: Tricritical point
#+FILETAGS: :problem:
#+SETUPFILE: ../../setupfile.org

* Problem Statement

2. Tricritical point: By tuning an additional parameter, a second order transition can be made first order. The special point separating the two types of transitions is known as a tricritical point, and can be studied by examining the Landau-Ginzburg Hamiltonian

\begin{align*}
\beta \mathcal{H}=\int \mathrm{d}^{d} \mathbf{x}\left
[
\frac{K}{2}(\nabla m)^{2}+\frac{t}{2} m^{2}+u m^{4}+v m^{6}-h m\right]
\end{align*}

where \(u\) can be positive or negative. For \(u<0\), a positive \(v\) is necessary to insure stability.
(a) By sketching the energy density \(\Psi(m)\), for various \(t\), show that in the saddle point approximation there is a first order transition for \(u<0\) and \(h=0\).

(b) Calculate \(\bar{t}\) and the discontinuity \(\bar{m}\) at this transition.

(c) For \(h=0\) and \(v>0\), plot the phase boundary in the \((u, t)\) plane, identifying the phases, and order of the phase transitions.

(d) The special point \(u=t=0\), separating first and second order phase boundaries, is a tricritical point. For \(u=0\), calculate the tricritical exponents \(\beta, \delta, \gamma\), and \(\alpha\), governing the singularities in magnetization, susceptibility, and heat capacity. (Recall: \(C \propto t^{-\alpha} ; \bar{m}(h=0) \propto t^{\beta} ; \chi \propto t^{-\gamma} ;\) and \(\left.\bar{m}(t=0) \propto h^{1 / \delta}.\right)\)

* Solution

* Related Concepts
