:PROPERTIES:
:ID:       5cef1940-2b35-4845-bc4f-8b5dbb4df15e
:END:
#+TITLE: Inverse-square interactions
#+FILETAGS: :problem:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
8. Inverse-square interactions: Consider a scalar field $s(x)$ in one-dimension, subject to an energy

\begin{align*}
-\beta \mathcal{H}_{s}=\frac{K}{2} \int \mathrm{d} x \mathrm{~d} y \frac{s(x) s(y)}{|x-y|^{2}}+\int \mathrm{d} x \Phi[s(x)]
\end{align*}

The local energy $\Phi[s]$ strongly favors $s(x)= \pm 1$ (e.g. $\Phi[s]=g\left(s^{2}-1\right)^{2}$, with $g \gg 1$ ).
(a) With $K>0$, the ground state is ferromagnetic. Estimate the energy cost of a single domain wall in a chain of length $L$. You may assume that the transition from $s=+1$ to $s=-1$ occurs over a short distance cutoff $a$.

(b) From the probability of the formation of a single kink, obtain a lower bound for the critical coupling $K_{c}$, separating ordered and disordered phases.

(c) Show that the energy of a dilute set of domain walls located at positions $\left\{x_{i}\right\}$ is given by

\begin{align*}
-\beta \mathcal{H}_{Q}=4 K \sum_{i<j} q_{i} q_{j} \ln \left(\frac{\left|x_{i}-x_{j}\right|}{a}\right)+\ln y_{0} \sum_{i}\left|q_{i}\right|
\end{align*},

where $q_{i}= \pm 1$ depending on whether $s(x)$ increases or decreases at the domain wall. (Hints: Perform integrations by part, and coarse-grain to size $a$. The function $\Phi[s]$ only contributes to the core energy of the domain wall, which results in the fugacity $y_{0}$.)

(d) The logarithmic interaction between two opposite domain walls at a large distance $L$ is reduced due to screening by other domain walls in between. This interaction can be calculated perturbatively in $y_{0}$, and to lowest order is described by an effective coupling (see later)

\begin{align*}
K \rightarrow K_{\mathrm{eff}}=K-2 K y_{0}^{2} \int_{a}^{\infty} \mathrm{d} r r\left(\frac{a}{r}\right)^{4 K}+\mathcal{O}\left(y_{0}^{4}\right) \tag{1}
\end{align*}

By changing the cutoff from $a$ to $b a=(1+\delta \ell) a$, construct differential recursion relations for the parameters $K$ and $y_{0}$.

(e) Sketch the renormalization group flows as a function of $T=K^{-1}$ and $y_{0}$, and discuss the phases of the model.

(f) Derive the effective interaction given above as Eq. (1). (Hint: This is somewhat easier than the corresponding calculation for the two-dimensional Coulomb gas, as the charges along the chain must alternate.)

* Solution

* Related Concepts
