:PROPERTIES:
:ID:       74908522-ad05-4c10-995d-e846569b0313
:END:
#+TITLE: ICML Privacy Policy
#+FILETAGS: :fleeting:icml:2025:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org

Our Privacy Policy explains how information is collected, used, and disclosed by ICML, with respect to your access and use of our services, through our website or in connection with third party services.

* Information We Collect and How We Use It
We collect certain information from you through your use of the Website, such as the information you provide to ICML by registering for a user account.
Information You Provide to Us

When you use the ICML Website to register a user account, limited information is collected about you through a form. This information is for the purpose of identifying and communicating with you as supporters, conference registrants and community members.

We may need to send you announcements and account-related messages. These will be sent through the Website or by email.

*We will not share the personal information we have collected from you, except as described below:*

   + when you agree to share your information with our sponsors during registration in the Jobs and Recruitment section.
   + when auditing our books, your information may be shared temporarily with our partners in a very limited scope.
   + when we believe we are authorized or legally required to do so or that doing so is necessary or appropriate to comply with the law or legal processes or respond to lawful requests or legal authorities, including things like  subpoenas, warrants or court orders.
   + to enforce or apply our Privacy Policy, our Terms of Use or our other policies or agreements.
   + if your company is one of our sponsors. Some sponsors have access to a report that shows who from their company is attending (including email addresses), what they've registered for, and what they are presenting. A sponsor can only see information for their own employees.
   + to facilitate and support visa applications, we may share a list of current year registrations with the immigration office of the current year host government
   + meeting organizers have access to user profile information to facilitate building the schedule, and communicating with speakers and presenters

* Accessing Your Information
If you would like ICML to delete your personal information that has been collected, please contact us with your request.

* How We Protect Your Information
We employ administrative, physical, and electronic measures designed to protect your information from unauthorized access. However, despite those efforts, no security measures are perfect or impenetrable.

* Links to Other Sites
The ICML Website may contain links to other services, apps, and sites not operated by us (we refer to these as "Other Sites"). Any information you provide on those Other Sites is provided directly to the owner of that site. Our Privacy Policy does not apply to those Other Sites, and we are not responsible for the content you provide to, or the privacy and security practices and policies of, Other Sites. CMT and OpenReview are examples of Other Sites.

* Changes to Our Privacy Policy
Any information that is collected is subject to our Privacy Policy in effect at the time such information is collected. We may, however, modify and revise our Privacy Policy from time-to-time. In the event of a modification to the Privacy Policy, ICML will send notification to you that a change has occurred via the Website or Email. It is required that you accept the revised Privacy Policy before continuing to use the Website. By accepting changes to the policy, you are agreeing to be bound by the revised policy.

* Questions or Concerns

Please contact us if you have any questions or concerns about our Privacy Policy.

