:PROPERTIES:
:ID:       5be666a9-4dcf-4dbd-a84a-c924e70dfa05
:END:
#+TITLE: Notes on Principles of Quantum Mechanics by Ramamurthy Shankar
#+FILETAGS: :pqm:problems:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org
#+BEGIN: clocktable :maxlevel 2 :scope nil :emphasize nil
#+CAPTION: Clock summary at [2024-11-07 Thu 14:12]
| Headline                             |    Time |      |
|--------------------------------------+---------+------|
| *Total time*                         | *59:15* |      |
|--------------------------------------+---------+------|
| Simple Problems in One Dimension     |    2:42 |      |
| Systems with N Degrees of Freedom    |   10:43 |      |
| Symmetries and Their Consequences    |    3:07 |      |
| Rotational Invariance and Angular... |   10:00 |      |
| The Hydrogen Atom                    |    3:29 |      |
| Spin                                 |    4:52 |      |
| Addition of Angular Momenta          |   17:47 |      |
| Time-Independent Perturbation Theory |    6:35 |      |
| \_  Selection rules                  |         | 1:58 |
#+END:
* Mathematical Introduction
:LOGBOOK:
CLOCK: [2022-11-16 Wed 19:42]--[2022-11-16 Wed 19:42] =>  0:00
:END:
#+NAME: Vector Space

#+ATTR_LATEX: :environment definition
#+BEGIN_definition
Let \(\mathbb{V} = \left \lbrace \vert 1 \rangle , \thinspace \vert 2 \rangle , \thinspace \dotso, \thinspace \vert V \rangle, \thinspace \vert W \rangle, \dotso \right \rbrace\) be a set of elements. Let \(\mathbb{F}\) be a /field/ over scalars, \(B_{1}\) and \(B_{2}\) be two binary operations defined on the elements of \(\mathbb{V}\) such that:

\[B_{1}: \mathbb{V} \times \mathbb{V} \to \mathbb{V}\]
\[B_{2}: \mathbb{F} \times \mathbb{V} \to \mathbb{V}\]

\(\mathbb{V}\) called a /vector space/, and the elements called /vectors/ if: 

+ \(B_{2}\) is /associative/, /distributive in scalars/, /distributive in vectors/,
+ \(B_{1}\) is /associative/ and /commutative/
+ There is a /null vector/ \(\vert 0 \rangle\) in \(\mathbb{V}\) that satisfies

  \[ \vert V \rangle + \vert 0 \rangle = \vert V \rangle,\]
+ For every vector \(\vert V \rangle\), there exists an /inverse under addition/ \(\vert - V \rangle\) such that

  \[\vert V \rangle + \vert - V \rangle = \vert 0 \rangle\].
#+END_definition

#+NAME: Field
#+ATTR_LATEX: :environment definition
#+begin_definition latex
The numbers \(a\), \(b\), \(\dotso\), are called the /field/ over which the vector space is defined.
#+end_definition

#+NAME: Linear Independence
#+ATTR_LATEX: :environment definition
#+begin_definition latex
A set of vectors is called linearly independent /iff/:
\begin{align*}
\sum_{i=1}^{n} a_{i} \vert i \rangle = 0 \Longrightarrow a_{i} = 0 \quad \text{for all} \quad i.
\end{align*}
#+end_definition

#+NAME: Dimensionality
#+ATTR_LATEX: :environment definition
#+begin_definition latex
A vector space has dimensions \(n\) if it can accomodale a maximum of \(n\) linearly independent vectors. When such a vector space is defined over the field of real numbers it is denoted by \(\mathbb{V}^n(R)\). When it is defined over the field of complex numbers it is denoted by \(\mathbb{V}^{n}(C)\).
#+end_definition

#+NAME: Span
#+ATTR_LATEX: :environment definition
#+begin_theorem latex
Any \(|v\rangle \in V^n\) may be written as a linear combination of \(n\) linearly independent vectors \(\{11\rangle, \ldots,|n\rangle\}\).
#+end_theorem

#+NAME: Basis
#+ATTR_LATEX: :environment definition
#+begin_definition latex
A set of \(n\) linearly independent vectors in an n-dimensional vector space is called a /basis/.

\(|v\rangle=\sum_{i=1}^n v_i|i\rangle\)

where \(\left \lbrace \vert 1 \rangle, \vert 2 \rangle, \dotso, \vert n \rangle  \right \rbrace\) form a /basis/.
#+end_definition

#+NAME: Components of a Vector
#+ATTR_LATEX: :environment definition
#+begin_definition latex
The coefficients of expansion \(v_i\) of a vector in terms of a linearly independent basis \(\{|i\rangle\}\) are called the components of the vector in that basis.
#+end_definition

#+NAME: Uniqueness of Vector Expansion
#+ATTR_LATEX: :environment definition
#+begin_theorem latex
The expansion of a vector \(|v\rangle\), in a given basis \(\{ \vert i\rangle\}\), with the coefficients \(\left\{v_i\right\}\) is unique.
#+end_theorem

\begin{align*}
&|V\rangle=\sum v_i|i\rangle, \quad
|W\rangle=\sum \omega_i|i\rangle, \quad |V\rangle+|W\rangle=\sum\left(v_i+w_i\right)|i\rangle
\end{align*}

\begin{align*}
|V\rangle=\sum v_i|i\rangle, \quad a|V\rangle=\sum a v_i|i\rangle.
\end{align*}

#+NAME: Inner Product
#+ATTR_LATEX: :environment definition
#+begin_definition latex
The inner-product between two vectors \(|V\rangle\) and \(|W\rangle\), denoted is \(\langle V \mid W\rangle\) is a number complex in general) that has the properties:
(a) \(\langle V \mid W\rangle=\langle W \mid V\rangle^*\) (Skew-symmetry)
(b) \(\langle V \mid V\rangle \geqslant 0,\langle V \mid V\rangle= 0 \Longleftrightarrow \vert V\rangle= \vert 0\rangle\) (Positive semi-definiteness)
(c) \(\langle V|(a|W\rangle+b|Z\rangle) \equiv\langle V \mid a W+b Z\rangle=a\langle V \mid W\rangle+b\langle V \mid Z\rangle\) (Linearity in ket)
#+end_definition

Skew-symmetry implies /anti-linearity of the inner product in bras/.

\(\langle a W+b Z \mid V\rangle=a^*\langle W \mid V\rangle+b^*\langle Z \mid V\rangle\)

#+NAME: Orthogonality
#+ATTR_LATEX: :environment definition
#+begin_definition
\(|V\rangle\) and \(|W\rangle\) are called orthogonal (to each other) iff \(\langle V \mid W\rangle=0\).
#+end_definition

#+NAME: Norm
#+begin_definition latex
Given vector \(|V\rangle, \sqrt{\langle V \mid V\rangle} \equiv|V|\) is called its norm. A normalized vector has unit norm.
#+end_definition

#+NAME: Orthonormal Basis
#+begin_definition latex
A set of normalized basis vectors, that are pair-wise orthogonal are said to form an orthonormal basis.
#+end_definition

Given two vectors \(|V\rangle\) and \(|W\rangle\) expanded in two different basis \(\{|i\rangle\}\) and \(\{\vert j\rangle\}\), their inner product is given as \(\langle V \mid W \rangle=\sum_i \sum_j v_i^* w_j\langle i \mid j\rangle\).

For every ket \(|V\rangle\), there exists a bra, denoted by \(\langle V|\). The bra is the Ket's /adjoint/ (transpose-conjugate). /Bras and Kets reside in distinct vector spaces/. Formally, the inner product is a /bilinear map/ - a machine that tokes vectors from two distinct vector spaces - the space of the kets and a /dual space/ of bras - and spits out a number.

\begin{equation*}
|V\rangle \leftrightarrow\left[\begin{array}{c}
v_1 \\
\vdots \\
v_n
\end{array}\right] \leftrightarrow\left[v_1^*, \ldots, v_n^*\right] \leftrightarrow\langle V|
\end{equation*}

Expanding two vectors in a common orthonormal basis simplifies the inner product:

\begin{align*}
\langle V \mid W \rangle=\sum_i \sum_j v_i^* w_j \underbrace{ \langle i \vert j \rangle}_{\equiv\delta_{ij}} &=\sum_i v_i^* w_i\langle i \mid i\rangle =\sum_i v_i^* w_i.
\end{align*}

Expanding a vector in an orthonormal basis simplifies finding the coefficients:

\begin{align*}
| V \rangle =\sum_i v_i | i\rangle, \quad \langle j \mid V \rangle=\sum_i v_i \underbrace{\langle j \mid i\rangle}_{\equiv \delta_{j i}}=v_j \Longrightarrow \vert V\rangle =\sum_i | i\rangle \langle i \mid V \rangle.
\end{align*}

#+NAME: Gram-Schmidt
#+begin_theorem latex
Any basis \(\{\vert i\rangle\}\) can be converted into an orthonormal basis. An orthonormal basis has the property:

\begin{align*}
\langle i \mid j\rangle= \delta_{ij} \equiv \begin{cases}1, & i=j \\ 0, & i \neq j\end{cases}.
\end{align*}

Here \(\delta_{ij}\) is the /Kronecker delta/.

Let \(|I\rangle\), \(\vert II \rangle\), \(\dotso\) be a /linearly independent basis/. The orthonormal basis \(|1\rangle,|2\rangle, \ldots\) is:

\(|1\rangle=|I\rangle /|I|\)

\(\vert 2 \rangle = \vert 2^{\prime} \rangle / \lvert 2^{\prime} \rvert, \quad \vert 2^{\prime} \rangle = \vert II \rangle - \vert 1 \rangle \langle 1 \mid II \rangle\)

\(\vert 3 \rangle= \vert 3^{\prime}\rangle / \lvert 3^{\prime} \rvert, \quad  \vert 3^{\prime} \rangle= \vert III \rangle - \vert 2 \rangle \langle 2 \mid III \rangle - |1 \rangle \langle 1 \mid III \rangle\)

Linear independence of \(\{ \vert I \rangle, \vert II \rangle, \dotso \}\) guarantees /completion of the orthogonalization/.
#+end_theorem

#+NAME: Dimensionality
#+begin_theorem latex
The dimensionality of a space equals \(n_{\perp}\), the maximum number of mutually or thogonds vectors in it.
#+end_theorem

#+NAME: Schwarz Inequality
#+begin_theorem latex
\begin{align*}
|\langle V \mid W\rangle| \leqslant|V||W|.
\end{align*}
#+end_theorem

#+NAME: Triangle Inequality
#+begin_theorem latex
\begin{align*}
\vert V+W \vert \leq |V|+|W|.
\end{align*}
#+end_theorem

#+NAME: Subspace
#+begin_definition latex
Given a vector space \(\mathbb{V}\), a subset of its elements that form a vector space among themselves is called a /subspace/. The \(i^{\text {th }}\) subspace with dimensionality \(n_i\) is denoted as \(\mathbb{V}_i^{n_{i}}\).
#+end_definition

#+NAME: Sum of Vector (sub) Spaces
#+begin_definition latex
Given two subspaces \(\mathbb{V}_i^{n_i}, \mathbb{V}_j^{m_j}\), the sum, denoted as

\(\mathbb{V}_{i}^{n_i} \oplus \mathbb{V}_{j}^{m_j} \equiv \mathbb{V}_{k}^{o_{k}}\)

is the set containing:

(1) all elements of \(\mathbb{V}_i^{n_i}\)

(2) all elements of \(\mathbb{V}_j^{m_j}\)

(3) all possible linear combinations of the above.
#+end_definition

#+NAME: Linear Operator
#+begin_definition latex
An linear operator is a function from one vector space to another; a mapping between vectors.

\(\Omega: \mathbb{V} \rightarrow \mathbb{W}, \quad \Omega | V \rangle = | W \rangle\).
#+end_definition

A linear operafor satisfying closure has the following properties:

\(\Omega: \mathbb{V} \rightarrow \mathbb{V}, \quad \Omega| V \rangle=\left|V^{\prime}\right\rangle\)

+ \(\Omega \alpha\left|V_i\right\rangle=\alpha \Omega\left|V_i\right\rangle\)
  
+ \(\Omega\left(\alpha\left|V_i\right\rangle+\beta\left|V_j\right\rangle\right)=\alpha \Omega\left|V_i\right\rangle+\beta \Omega\left|V_j\right\rangle\)
  
+ \(\left\langle V_i\right| \alpha \Omega=\left\langle V_i\right| \Omega \alpha\)
  
+ \(\left(\left\langle V_i\right| \alpha+\left\langle V_j\right| \beta\right) \Omega=\alpha\left\langle V_i\right| \Omega+\beta\left\langle V_j\right| \Omega\)
  
+ \(\Omega|V\rangle=\Omega\left(\sum_i v_i|i\rangle\right)=\sum_i v_i \Omega|i\rangle=\sum_i v_i\left|i^{\prime}\right\rangle\)

#+NAME: Commutator
#+begin_definition latex
\([\Omega, \Lambda] \equiv \Omega \Lambda-\Lambda \Omega\) is called the commutator of \(\Omega\) and \(\Lambda\).
#+end_definition

The commutator satisfies the identities:

\begin{align*}
&{[\Omega, \Lambda \theta]=\Lambda[\Omega, \theta]+[\Omega, \Lambda] \theta} \\
\end{align*}

\begin{align*}
&{[\Lambda \Omega, \theta]=\Lambda[\Omega, \theta]+[\Lambda, \theta] \Omega}
\end{align*}

#+NAME: Identity Operator
#+begin_definition latex
\(I\) is the identity operator, a machine that returns the same vector it took.
#+end_definition

#+NAME: Inverse of an Operator
#+begin_definition latex
The inverse of a operator \(\Omega\), denoted by \(\Omega^{-1}\), by definition, satisfies:

\begin{align*}
\Omega \Omega^{-1}=\Omega^{-1} \Omega=I.
\end{align*}

#+end_definition

In general, the existence of the inverse is not guaranteed.

The inverse of a product of operators is given as:

\begin{align*}
(\Omega \Lambda)^{-1}=\Lambda^{-1} \Omega^{-1}.
\end{align*}

#+NAME: Matrix Elements of an Operator
#+begin_definition latex
In a given basis \(\{|i\rangle\}\) for \(\mathbb{V}^n\), an operator is represented as a matrix. The \(i j^{\text{th}}\) element of this matrix is

\begin{align*}
\Omega_{i j}=\langle i|\Omega| j\rangle.
\end{align*}

The \(n^2\) numbers, \(\Omega_{i j}\), are the /matrix elements/ of \(\Omega\) in this basis.
#+end_definition

\begin{align*}
|V\rangle=\sum_i v_i|i\rangle, \quad \Omega|V\rangle=\left|V^{\prime}\right\rangle, \quad
\left|V^{\prime}\right\rangle=\sum_i v_i^{\prime}|i\rangle, \quad v_i^{\prime}=\sum_j \Omega_{i j} v_j
\end{align*}

#+NAME: Projection Operator
#+begin_definition latex
The projection operator for ket \(\vert i \rangle\) is defined as:

\begin{align*}
\mathbb{P}_i=|i\rangle\langle i|, \quad\left(\mathbb{P}_i\right)_{k l}=\langle k \mid i\rangle\langle i \mid \ell\rangle=\delta_{k i} \delta_{i l}.
\end{align*}
#+end_definition

#+NAME: Completeness Relation
#+begin_definition latex
The identity operator may be expressed as a sum over projection operators. It is called the completeness relation.
\begin{align*}
I=\sum_{i=1}^n|i\rangle\langle i|=\sum_{i=1}^n \mathbb{P}_i.
\end{align*}
#+end_definition

The action of projection operator on bras and kets is:

\begin{align*}
\mathbb{P}_i|v\rangle=|i\rangle\left\langle i\left|\sum_{j=1}^n v_j\right| j\right\rangle=\sum_{j=1}^n v_j|i\rangle\langle i \mid j\rangle=\sum_{j=1}^n v_j|i\rangle \delta_{i j}=v_i|i\rangle,
\end{align*}

\begin{align*}
\left\langle v\left|\mathbb{P}_i=\sum_{j=1}^n v_j^*\right| j\right\rangle^*|i\rangle\langle i|=\sum_{j=1}^n v_j^*\langle i|\langle j \mid i\rangle=\sum_{j=1}^n v_j^*\langle i| \delta_{j i}=v_i^*\langle i|.
\end{align*}

Projection operators have the property:

\begin{align*}
\mathbb{P}_i \mathbb{P}_j=|i\rangle\langle i \mid j\rangle\langle j|=\delta_{i j} \mathbb{P}_j.
\end{align*}

#+NAME: Outer Product
#+begin_definition latex
The object \(|V\rangle\left\langle V^{\prime}\right|\) is called the outer product of \(|V\rangle\) and \(\langle V^{\prime} \vert\). It is a linear operator. If \(| V \rangle \in \mathbb{V}^{n}\), then the matrix representation of \(|V\rangle\langle V^{\prime}|\) has \(n^2\) elements.
#+end_definition

#+NAME: Adjoint of an Operator
#+begin_definition latex
An operator acting on a ket has a corresponding operator that acts on the bras, called its adjoint

\begin{align*}
\Omega|V\rangle=|\Omega V\rangle=\left|V^{\prime}\right\rangle, \quad\left\langle V^{\prime}\right|=\langle\Omega V|=\langle V| \Omega^{\dagger}
\end{align*}

\begin{align*}
\left(\Omega^{\dagger}\right)_{i j}=\left\langle i\left|\Omega^{\dagger}\right| j\right\rangle=\langle\Omega i \mid j\rangle=\langle j \mid \Omega i\rangle^*=\langle j|\Omega | i\rangle^{\ast} =\left(\Omega_{j i}^{\ast}\right).
\end{align*}
#+end_definition

The adjoint of a product is the product of the adjoint in reverse:

\begin{align*}
(\Omega \Lambda)^{\dagger} = \Lambda^{\dagger} \Omega^{\dagger}.
\end{align*}

*To take the adjoint of an equation consisting of kets, scalars, and operators, reverse the order of all factors and make the substitutions*

\begin{align*}
\left.\Omega \leftrightarrow \Omega^{\dagger}, \quad | \rangle \leftrightarrow \langle |, \quad \alpha \leftrightarrow \alpha^{\ast}.
\end{align*}

Example: The adjoint of

\begin{align*}
&\alpha_1\left|V_1\right\rangle=\alpha_2\left|V_2\right\rangle+\alpha_3\left|V_3\right\rangle\left\langle V_4 | V_5\right\rangle+\alpha_4 \Omega \Lambda \left| V_6 \right\rangle \\
\end{align*}

is

\begin{align*}
\left\langle V_1\right| \alpha_1^{*} = \left\langle V_{2} \right| \alpha_2^{*} + \left\langle V_{5} | V_4\right\rangle\left\langle V_3\right| \alpha_3^*+\left\langle V_6\right| \Lambda^{\dagger} \Omega^{\dagger} \alpha_4^*.
\end{align*}

#+NAME: Hermitian Operator
#+begin_definition latex
An operator \(\Omega\) is Hermitian if \(\Omega^{\dagger}=\Omega\).
#+end_definition

#+NAME: Anti-Hermitian
#+begin_definition latex
An operator \(\Omega\) is anti-Hermitian if \(\Omega^{\dagger} = -\Omega\).
#+end_definition

#+NAME: Hermitian Decomposition
#+begin_theorem latex
An arbitrary operator \(\Omega\) can be expressed as a sum of a Hermitian and anti-Hermitian operator:

\begin{align*}
\Omega=\frac{\Omega+\Omega^{\dagger}}{2}+\frac{\Omega-\Omega^{\dagger}}{2}.
\end{align*}

#+end_theorem

#+NAME: Unitary Operator
#+begin_definition latex
An operator \(U\) is unitary if

\begin{align*}
U U^{\dagger}=I=U^{\dagger} U, \quad U^{-1}=U^{\dagger}, \quad \left[U, U^{\dagger}\right]=0.
\end{align*}

#+end_definition

#+NAME: Unitary Operators preserve the Norm
#+begin_theorem latex
Unitary operators preserve the inner product between the vectors they act on, i.e.,

if

\begin{align*}
U\left|V_1\right\rangle=\left|V_1^{\prime}\right\rangle \quad \text{and} \quad U\left|V_2\right\rangle=\left|V_2^{\prime}\right\rangle
\end{align*}

then

\begin{align*}
\left\langle V_2^{\prime} | V_1^{\prime} \rangle = \left\langle V_2 | V_{1} \rangle.
\end{align*}

#+end_theorem

#+NAME: Columns (or rows) of a Unitary Matrix are pairwise orthonormal
#+begin_theorem latex
The \((n)\) columns and \((n)\) rows of an \(n \times n\) unitary matrix, when treated as vectors in \(\mathbb{V}^n\), are orthonormal.
#+end_theorem

Hermitian, anti-Hermitian, and Unitary operators are analogous to pure real, pure imaginary, complex numbers of unit modulus respectively.

Unitary operators are generalizations of rotation operators from \(\mathbb{V}^{3}(R)\) to \(\mathbb{V}^{n}(C)\) - preserving the inner-product, and thus the length of vectors.

#+NAME: Active Transformation
#+begin_definition latex
\begin{align*}
|V\rangle \rightarrow U|V\rangle, \quad \Omega \rightarrow \Omega, \quad \left\langle V^{\prime}|\Omega| V\right\rangle \rightarrow\left\langle V^{\prime}\left|U^{\dagger} \Omega U\right| V\right\rangle
\end{align*}
#+end_definition

#+NAME: Passive Transformation
#+begin_definition latex
\begin{align*}
|V\rangle \rightarrow|V\rangle, \quad \Omega \rightarrow U^{\dagger} \Omega U, \quad \left\langle V^{\prime}|\Omega| V\right\rangle \rightarrow\left\langle V^{\prime}\left|U^{\dagger} \Omega U\right| V\right\rangle
\end{align*}
#+end_definition

A ``passive transformation" is really an ``active transformation" done backstage. Choosing between the two views is choosing between being on audience or a member of the crew. I'm active, unless it's =Birdman=. Then I'm PASSIVE.

#+NAME: Eigenvalue Equation
#+begin_definition latex
\begin{align*}
\Omega \vert V \rangle = \omega \vert V \rangle.
\end{align*}
#+end_definition

#+NAME: Characteristic Polynomial
#+begin_definition latex
\begin{align*}
P^{n}(\omega) = \sum_{m=0} c_{m} \omega^{m}.
\end{align*}
#+end_definition

#+NAME: Characteristic Equation
#+begin_definition latex
\begin{align*}
P^{n}(\omega) = \sum_{m=0} c_{m} \omega^{m} = 0.
\end{align*}
#+end_definition

+ A sequence of steps to go from the eigenvalue equation to the characteristic equation:
  + \(\Omega \vert V \rangle = \omega \vert V \rangle\),
  + \(\left( \Omega - \omega I \right) \vert V \rangle = \vert 0 \rangle\),
  + \(\det \left( \Omega - \omega I \right) = 0\) if non-trivial eigenkets are to exist.
  + \(\det \left( \Omega - \omega I \right)\) is obtained as a product of the projection of \(\left( \Omega - \omega I \right) \vert V \rangle = \vert 0 \rangle\) onto the entire set of basis bras \(\{ \langle i \vert \}\) and has the general form: \(\sum_{m}^{n} c_{m} \omega^{m} = 0\) which is the characteristic equation.

Finding eigenvalues of \(\Omega\) has been /reduced to root-finding/.

Finding eigenvectors has been reduced to /solving a system of linear equation./

Each distinct (or not) eigenvalue ( \(n\) for the \(n\) roots of the characteristic polynomial for \(\Omega\) acting on vectors in \(\mathbb{V}^n\) ) may /not/ pair with a unique eigenket (upto a scaling factor). Some eigenvalues may not have a corresponding eigenket at all.

+ A polynomial \(P^n(x)=\sum_{i=0}^n a_i x^i\) is guaranteed to have \(n\) -roots, not necessarily distinct or real.
+ Roots of \(P^n(x)\) are value of \(x\), say \(x^*\), such that \(P^n\left(x^*\right)=0\).
+ Real roots are points on real axis that satisfy \(P^n(x)=0\).
+ Complex roots are points in the complex plane that satisfy \(P^n(x)=0\).
  
+ A root of the characteristic polynomial of a non-degenerate operator \(\Omega: \mathbb{V}^{n} \to \mathbb{V}^{n}\), upon substitution in the eigenvalue equation yields a system of \(n\) linear equation. There are \(n\) such systems. The freedom to scale eigenkets can be used to eliminate 1 equation from every system. The solution to each system is the eigenket for the eigenvalue that generated it. A solution, in general, is not guaranteed.
  
+ For a degenerate operator \(\Lambda\) that has for \(m\) roots out of \(n\), the \(i^{\text {th }}\) one repeating \(k_i\) times, \((n-m)\) systems with \(n-1\) equations each are obtained, the solutions of which (if exists) yields \(n-m\) eigenkets, corresponding to the \(n-m\) distinct eigenvalues. Another \(m\) systems are obtained for the \(m\) degenerate roots all the same, but only \(m - \sum_{i} k_{i}\) of them are /unique/. Each degenerate eigenvalue adds a degree of freedom to its eigenket: the eigenket of the \(i^{\text{th}}\) root (it it exists at all) lives in an eigenspace of dimensionality \(k_i\).

#+NAME: Eigenvalues of a Hermitian Operator
#+begin_theorem latex
The eigenvalues of a Hermitian operator are real.
#+end_theorem

#+NAME: Eigenvalues of a Unitary Operator
#+begin_theorem latex
The eigenvalues of a unitary operator are complex numbers of unit modulus.
#+end_theorem

#+NAME: Eigenvectors of a Non-Degenerate Unitary Operator
#+begin_theorem latex
The eigenvectors of a non-degenerate unitary operator are mutually orthogonal.
#+end_theorem

#+NAME: Diagonalization of Hermitian Operator
#+begin_theorem latex
To every Hermitian operator \(\Omega\), there exists (at least) a basis consisting of its orthonormal eigenvectors. It is diagonal in this eigenbasis and has its eigenvalues as its diagonal entries.
#+end_theorem

#+NAME: Similarity Transformation
#+begin_theorem latex
If \(\Omega\) is Hermitian, there exists a unitary matrix \(U\) ( its columns being the eigenvectors of \(\Omega\) ) such that \(\mathrm{U}^{+} \Omega \mathrm{U}^*\) is diagonal.
#+end_theorem  
  
Finding a basis that diagonalizes \(\Omega\) is /reduced to solving its eigenvalue problem./

#+NAME: Simultaneous Diagonalization
#+begin_theorem latex
If \(\Omega\) and \(\Lambda\) are two commuting Hermitian matrices/operators, there exists (at least) a basis of common eigenkets that diagonalizes them both.
#+end_theorem

Consider

\begin{align*}
f(x)=\sum_{n=0}^{\infty} a_n x^n.
\end{align*}

In this equation \(x\) is a /``c-number"/.

Consider

\begin{align*}
f(\Omega)=\sum_{n=0}^{\infty} a_n \Omega^n
\end{align*}

In this equation \(\Omega\) is a /``q-number"/.

#+NAME: Derivative of a Operator
#+begin_definition latex
The derivative of an operator w.r.t a parameter is defined as

\begin{align*}
\frac{d \theta(\lambda)}{d \lambda}=\lim _{\Delta \lambda \rightarrow 0}\left[\frac{\theta(\lambda+\Delta \lambda)-\theta(\lambda)}{\Delta \lambda}\right]
\end{align*}
#+end_definition

Example: Suppose \(\theta(\lambda)=\exp [\lambda \Omega], \quad \Omega=\Omega^{\dagger}\).

Since \(\Omega\) is Hermitian, \(\exp [\Omega]=\sum_{n=1}^{\infty} \Omega^n / n !\) is well-defined (it should be obvious why). We then have:

\begin{align*}
\frac{d \theta}{d \lambda}=\Omega \exp [\lambda \Omega]=\exp [\lambda \Omega] \Omega=\theta(\lambda) \Omega.
\end{align*}

If only one \(q\) -number appears in an equation (or its powers), everything commutes and they may thus be treated just like \(c\) -numbers. If more than one \(q\) number is involved, the order of factors is all important. For example:

\begin{align*}
\exp (\alpha \Omega) \exp (\beta \Omega)=\exp ((\alpha+\beta) \Omega),
\end{align*}

but

\begin{align*}
\exp (\alpha \Omega) \exp (\beta \theta) \neq \exp (\alpha \Omega+\beta \theta)
\end{align*}

unless \([\Omega, \theta]=0\).

Similarly

\begin{align*}
\exp (\alpha \Omega) \exp (\beta \theta) \exp (-\alpha \Omega) \neq \exp (\beta \theta),
\end{align*}

and

\begin{align*}
\Omega \exp (\lambda \Omega) \exp (\beta \theta)=\exp (\lambda \Omega) \Omega \exp (\beta \theta)$ \neq \exp (\lambda \Omega ) \exp (\beta \theta) \Omega
\end{align*}

unless \([\Omega, \theta]=0\).

The chain rule for differentiating a product of functions of operators

\begin{align*}
\frac{d}{d \lambda} f(\Omega) g(\theta)=\frac{d}{d \lambda} f(\Omega) \cdot g(\theta)+f(\Omega) \frac{d}{d \lambda} g(\theta)
\end{align*}

As an example:

\begin{align*}
\frac{d}{d \lambda} \exp (\lambda \Omega) \exp (\beta \theta)=\Omega \exp (\lambda \Omega) \exp (\beta \theta)+\exp (\lambda \Omega) \exp (\beta \theta).
\end{align*}

Functions can be elements of vector spaces. Each function is represented by a ket \(|f\rangle\) belonging to an infinite-dimensional vector space. Vector addition and scalar multiplication is analogous to the finite-dimensional case. The space must satisfy all the axioms satisfied by a vector space. The space of square integrable functions is an example of a Hilbert space.

The inner product is redefined as:

\begin{align*}
\langle f \vert g\rangle=\int f^{\ast}(x) g(x) d x
\end{align*}

+ \(\langle f \vert g\rangle=0 \Rightarrow|f\rangle\) and \(|g\rangle\) are orthogonal.
+ \(\langle f \vert f\rangle=0+1=1 \Rightarrow|f\rangle\) is normalized.

The completeness relation is redefined as:

\begin{align*}
\int\left|x^{\prime}\right\rangle\left\langle x^{\prime}\right| d x^{\prime}=I.
\end{align*}

The orthogonality condition is redefined as:

\begin{align*}
\left \langle x \vert x^{\prime} \right \rangle = \delta \left( x - x^{\prime} \right).
\end{align*}

This is /not/ the Kronecker della, it is the /Dirac delta function/.

#+NAME: Dirac delta function
#+begin_definition latex
A heuristic characterization of the Dirac delta function is:

\begin{align*}
\delta \left( x \right) \simeq
\begin{cases}
+ \infty, \quad &x = 0 \\
0, \quad &x \neq 0
\end{cases}
\end{align*}

and

\begin{align*}
\int_{-\infty}^{\infty} \delta \left( x \right) dx = 1.
\end{align*}
#+end_definition

The Dirac della function is defined only in the context of an integration:

\begin{align*}
\int \delta\left(x-x^{\prime}\right) f\left(x^{\prime}\right) d x^{\prime}=f(x).
\end{align*}

+ The Dirac delta function is even, real.
+ The Dirac delta function may be defined as a Gaussian distribution in the limit of zero variance:

\begin{align*}
g_{\Delta} = \dfrac{1}{\left( \pi \Delta \right)^{1/2}} \exp \left \lbrace - \dfrac{\left( x - x^{\prime} \right)^{2}}{\Delta^{2}}  \right \rbrace,
\end{align*}

so that

\begin{align*}
\lim_{\Delta \to 0} g_{\Delta} \left( x - x^{\prime} \right) = \delta \left( x - x^{\prime} \right).
\end{align*}

+ The Dirac delta function may be defined as a fourier integral:

\begin{align*}
\delta \left( x^{\prime} - x \right) \equiv \dfrac{1}{2 \pi} \int_{-\infty}^{\infty} dk \exp \left \lbrace i k \left[ x^{\prime} - x \right]  \right \rbrace.
\end{align*}

The derivative of Dirac delta function is
  
\begin{align*}
\delta^{\prime}\left(x-x^{\prime}\right)=\frac{d}{d x} \delta\left(x-x^{\prime}\right) \\
\Longrightarrow \int \delta^{\prime}\left(x-x^{\prime}\right) f\left(x^{\prime}\right) d x^{\prime} &= \int \frac{d}{d x} \delta\left(x-x^{\prime}\right) f(x^{\prime}) d x^{\prime} \\
&= \dfrac{d}{dx} \int \delta \left( x - x^{\prime} \right) f \left( x^{\prime} \right) d x^{\prime} \\
&= \dfrac{d}{dx} f(x).
\end{align*}

Now

\begin{align*}
\delta^{\prime}\left(x-x^{\prime}\right)=\frac{d}{d x} \delta\left(x-x^{\prime}\right) = - \dfrac{d}{d x^{\prime}} \delta \left( x - x^{\prime} \right),
\end{align*}

so that

\begin{align*}
\int-\frac{d}{d x^{\prime}} \delta\left(x-x^{\prime}\right) f(x) d x &=
\int\frac{d}{d x^{\prime}} \delta\left(x^{\prime}-x\right) f(x) d x \\
&= \dfrac{d}{d x^{\prime}} \int \delta \left( x^{\prime} - x \right) f \left( x \right) d x \\
&= \dfrac{d}{d x^{\prime}} f \left( x^{\prime} \right).
\end{align*}

+ \(\delta^{\prime} \left( x - x^{\prime} \right)\) is an odd function.
+ The action of higher derivatives may similarly be represented as:

\begin{align*}
\frac{d^n \delta\left(x-x^{\prime}\right)}{d x^n}=\delta\left(x-x^{\prime}\right) \frac{d^n}{d x^{\prime n}}
\end{align*}


Linear operators may be defined on function spaces. They change one function to another.

\begin{align*}
\Omega|f\rangle=|\tilde{f}\rangle
\end{align*}

#+NAME: Differential Operator
#+begin_definition latex
The /differential operator/ \(D\) has the action:

\begin{align*}
D \vert f \rangle = \vert df/dx \rangle.
\end{align*}

#+end_definition

\begin{align*}
&\dfrac{d f(x)}{dx} = \int \delta^{\prime} \left( x - x^{\prime} \right) f \left( x^{\prime} \right) d x^{\prime} = \int \left \langle x \left \lvert D  \right \rvert x^{\prime} \right \rangle \left \langle x^{\prime} \vert f \right \rangle d x^{\prime} \\
&\Longrightarrow \left \langle x \left \lvert D  \right \rvert x^{\prime} \right \rangle = \delta^{\prime} \left( x - x^{\prime} \right) = \delta \left( x - x^{\prime} \right) \dfrac{d}{d x^{\prime}}.
\end{align*}

+ \(D\) is /not/ Hermitian:

\begin{align*}
&\left \langle x \left \lvert D  \right \rvert x^{\prime} \right \rangle = \delta^{\prime} \left( x - x^{\prime} \right) \neq - \delta^{\prime} \left( x - x^{\prime} \right) = \left \langle x^{\prime} \left \lvert D  \right \rvert x \right \rangle^{\ast}
\Longrightarrow D \neq D^{\dagger}.
\end{align*}

- \(K \equiv-i D\) is Hermitian /given that it is defined on a function space in which the *surface term* vanishes/:

\begin{align*}
&K \stackrel{?}{=} K^{\dagger} \\
\text{or} & \left \langle g \left \lvert K  \right \rvert f \right \rangle \stackrel{?}{=} \left \langle f \left \lvert K  \right \rvert g \right \rangle^{\ast} \\
\text{or} & \int_{a}^{b} \int_{a}^{b} \left \langle g \vert x \right \rangle \left \langle x \left \lvert K  \right \rvert x^{\prime} \right \rangle \left \langle x^{\prime} \vert f \right \rangle dx dx^{\prime} \stackrel{?}{=} \left( \int_{a}^{b} \int_{a}^{b} \left \langle f \vert x \right \rangle \left \langle x \left \lvert K  \right \rvert x^{\prime} \right \rangle \left \langle x^{\prime} \vert g \right \rangle dx dx^{\prime} \right)^{\ast} \\
\text{or} &\int_{a}^{b} g^{\ast} \left( x \right) \left[ - i \dfrac{d f(x)}{dx} \right] dx \stackrel{?}{=} \left( \int_{a}^{b} f^{\ast} (x) \left[ - i \dfrac{d g (x)}{dx} \right] dx \right)^{\ast} \\
\text{or} &- i g^{\ast} (x) f (x) \Big \vert_{a}^{b} + i \int_{a}^{b} \dfrac{dg^{\ast}(x)}{dx} f(x) dx \stackrel{?}{=} i \int_{a}^{b} \dfrac{d g^{\ast} (x)}{dx} f(x) dx \\
\text{or} &- i g^{\ast} (x) f (x) \Big \vert_{a}^{b} \stackrel{?}{=} 0.
\end{align*}

Examples of function spaces in which \(K\) is Hermitian:

1) \(f(x)\) defined on \(0 \leqslant x \leqslant L\), and \(f(0)=f(L)=0\).
2) Periodic functions.
3) \(f(x)\) defined on \(-\infty \leqslant x \leqslant \infty\), and \(|x| \rightarrow \infty \Rightarrow f(x) \rightarrow 0\).
4) \(f(x) = \exp \left \lbrace i k x  \right \rbrace\), and:

\begin{align*}
\exp \left \lbrace i k x  \right \rbrace \exp \left \lbrace - i k^{\prime} x \right \rbrace \Big \vert_{-\infty}^{\infty} &=
\lim_{x \to \infty} \exp \left \lbrace i k x  \right \rbrace \exp \left \lbrace - i k^{\prime} x  \right \rbrace \\
&= \lim_{\Delta \to \infty, L \to \infty} \dfrac{1}{\Delta} \int_{L}^{\lambda - \Delta} \exp \left \lbrace i \left[ k - k^{\prime} \right] x  \right \rbrace dx \\
&= 0 \quad \text{if} \quad k \neq k^{\prime}.
\end{align*}

\begin{align*}
K \vert k \rangle = k \vert k \rangle &\Longrightarrow \left \langle x \left \lvert K  \right \rvert k \right \rangle = k \left \langle x \vert k \right \rangle \xrightarrow[]{\left( \psi_k(x) \equiv\langle x \vert k \rangle \right)} \\
&\text{or} \int\left\langle x|K| x^{\prime}\right\rangle\langle x^{\prime} \vert k\rangle d x^{\prime}=k \psi_k(x) \\
&\text{or} - i \dfrac{d}{dx} \psi_{k} \left( x \right) = k \psi_{k} \left( x \right).
\end{align*}

The solution for this differential equation is:

\begin{align*}
\psi_k(x)=A \exp \left \lbrace i k x  \right \rbrace.
\end{align*}

Any real number \(k\) is an eigenvalue, and the corresponding eigenfunction is given by \(A \exp \left \lbrace i k x  \right \rbrace\). Normalizing \(\vert k \rangle\)

\begin{align*}
\vert k \rangle \longleftrightarrow \dfrac{1}{(2 \pi)^{1/2}} \exp \left \lbrace i k x  \right \rbrace.
\end{align*}

The orthogonality condition is:

\begin{align*}
\left \langle k \vert k^{\prime} \right \rangle = \int_{-\infty}^{\infty} \left \langle k \vert x \right \rangle \left \langle x \vert k^{\prime} \right \rangle dx = \dfrac{1}{2 \pi} \int_{-\infty}^{\infty} \exp \left \lbrace - i \left( k - k^{\prime} \right) x \right \rbrace dx = \delta \left( k - k^{\prime} \right),
\end{align*}

as it should be. Therefore:

\begin{align*}
\left \langle k \left \lvert K  \right \rvert k^{\prime} \right \rangle = k^{\prime} \left \langle k \vert k \right \rangle = k^{\prime} \delta \left( k - k^{\prime} \right).
\end{align*}

We shall only be concerned with the *physical Hilbert space* - the space of functions that can either be /normalized to unity/ or to the /Dirac delta function/.

Because \(K\) is Hermitian, there exists a basis (orthonormal) in which \(K\) is diagonal. The ket \(\vert f \rangle\) may thus be expanded in the ``\(K\) basis":

\begin{align*}
f \left( k \right) = \left \langle k \vert f \right \rangle = \int_{-\infty}^{\infty} \left \langle k \vert x \right \rangle \left \langle x \vert f \right \rangle dx = \dfrac{1}{\left( 2 \pi \right)^{1/2}} \int_{-\infty}^{\infty} \exp \left \lbrace - i k x  \right \rbrace f \left( x \right) dx.
\end{align*}

\begin{align*}
f \left( x \right) = \left \langle x \vert f \right \rangle = \int_{-\infty}^{\infty} \left \langle x \vert k \right \rangle \left \langle k \vert f \right \rangle dk = \dfrac{1}{\left( 2 \pi \right)^{1/2}} \int_{-\infty}^{\infty} \exp \left \lbrace i k x  \right \rbrace f \left( k \right) dk.
\end{align*}

Suppose that \(X\), a Hermitian operator, brings into focus an (orthonormal) basis in which it is diagonal, and that this basis is made of \(\{|x\rangle\}\). The eigenvalue equation of \(X\) is

\begin{align*}
X \vert x \rangle = x \vert x \rangle,
\end{align*}

and the matrix elements of \(X\) are:

\begin{align*}
\left \langle x^{\prime} \left \lvert X  \right \rvert x \right \rangle = x \left \langle x^{\prime} \vert x \right \rangle = x \delta \left( x^{\prime} - x \right).
\end{align*}

The action of \(X\) on functions is

\begin{align*}
X \vert f \rangle = \vert \tilde{f} \rangle.
\end{align*}

But

\begin{align*}
\left \langle x \left \lvert X  \right \rvert f \right \rangle &= \int \left \langle x \left \lvert X  \right \rvert x^{\prime} \right \rangle \left \langle x^{\prime} \vert f \right \rangle dx^{\prime} = x f \left( x \right) = \left \langle x \vert \tilde{f} \right \rangle = \tilde{f} (x),
\end{align*}

so

\begin{align*}
X \vert f \rangle = x f \left( x \right) = \tilde{f} \left( x \right) = \vert x f (x) \rangle.
\end{align*}

Now

\begin{align*}
\left \langle k \left \lvert X  \right \rvert k^{\prime} \right \rangle &=
\dfrac{1}{2 \pi} \int_{-\infty}^{\infty} \exp \left \lbrace - i k x  \right \rbrace x \exp \left \lbrace i k^{\prime} x \right \rbrace dx \\
&= i \dfrac{d}{dk} \left( \dfrac{1}{2 \pi} \int_{-\infty}^{\infty} \exp \left \lbrace i \left( k^{\prime} - k \right) x \right \rbrace dx \right) \\
&= i \delta^{\prime} \left( k - k^{\prime} \right).
\end{align*}

It follows that:

\begin{align*}
X \vert g \left( k \right) \rangle = \Big \vert i \dfrac{d g (k)}{dk} \Big \rangle.
\end{align*}

In the \(x\) basis, \(x\) acts as \(x\) and \(K\) as \(-i d / d x\) (on functions \(f(x)\)), while in the \(K\) basis, \(K\) acts like \(k\) and \(x\) acts like \(i d / d k\) (on functions \(f(k)\)). Operators with this inter-relationship are called *conjugate* to each other.

\begin{align*}
[X, K]|f\rangle &\rightarrow(X K-K X) \vert f \rangle \rightarrow X K \vert f \rangle - K X \vert f \rangle \\
&\rightarrow - i x \frac{d f(x)}{d x}-\left(-i \frac{d}{d x} [x f(x)]\right) \\
&\rightarrow i I \vert f \rangle.
\end{align*}

Thus, \([X, K]=i I\), i.e \(X\) and \(K\) don't commute.
* All Is Not Well with Classical Mechanics            
* The Postulates a General Discussion                 
* Simple Problems in One Dimension                        
:LOGBOOK:
CLOCK: [2022-09-21 Wed 15:00]--[2022-09-21 Wed 15:25] =>  0:25
CLOCK: [2022-09-21 Wed 02:54]--[2022-09-21 Wed 05:11] =>  2:17
:END:
* The Classical Limit                                 
* The Harmonic Oscillator                                 
* The Path Integral Formulation of Quantum Theory          
* The Heisenberg Uncertainty Relations                    
* Systems with N Degrees of Freedom
CLOSED: [2022-11-19 Sat 09:28]
:LOGBOOK:
CLOCK: [2022-11-17 Thu 01:22]--[2022-11-17 Thu 03:51] =>  2:29
CLOCK: [2022-11-14 Mon 15:47]--[2022-11-14 Mon 17:17] =>  1:30
:END:
:LOGBOOK:
CLOCK: [2022-11-18 Fri 21:40]--[2022-11-19 Sat 04:24] =>  6:44
:END:
Consider two particles described classically by coordinates \((x_{1}, p_{1})\) and \((x_{2},p_{2})\). The Hilbert space for this system may be characterized in two ways:
1) the /simultaneous eigenkets/ \(\vert \omega_{1} \omega_{2} \rangle\) of two commuting operators \(\Omega_{1} \left( X_{1}, P_{1} \right)\) and \(\Omega_{2} \left( X_{2}, P_{2} \right)\) defines a basis \(\Omega\) that spans the /two-particle Hilbert space/ \(\mathbb{V}_{1 \otimes 2}\). The commuting operators \(\Omega_{1} \left( X_{1}, P_{1} \right)\) and \(\Omega_{2} \left( X_{2}, P_{2} \right)\) defined on the /two-particle Hilbert space/ \(\mathbb{V}_{1 \otimes 2}\) acts on its eigenket \(\ket{\omega_{1} \omega_{2}}\) as:

\begin{align*}
\Omega_{1} \vert \omega_{1} \omega_{2} \rangle = \omega_{1} \vert \omega_{1} \omega_{2} \rangle,
\end{align*}

\begin{align*}
\Omega_{2} \vert \omega_{1} \omega_{2} \rangle = \omega_{2} \vert \omega_{1} \omega_{2} \rangle.
\end{align*}
   
2) the /direct product/ \(\vert \omega_{1} \rangle \otimes \vert \omega_{2} \rangle\) of the eigenkets of operator \(\Omega_{1}^{(1)} \otimes \Omega_{2}^{(2)}\) span the /direct product space/ \(\mathbb{V}_{1} \otimes \mathbb{V}_{2}\) of \(\mathbb{V}_{1}\) and \(\mathbb{V}_{2}\). The operator \(\Omega_{1}^{(1)} \otimes \Omega_{2}^{(2)}\), a /direct product of operators/ \(\Omega_{1}^{(1)}\) and  \(\Omega_{2}^{(2)}\), defined on the direct product space \(\mathbb{V}_{1} \otimes \mathbb{V}_{2}\) acts on its eigenket \(\ket{\omega_{1}} \otimes \ket{\omega_{2}}\) as:

\begin{align*}
\left( \Omega_{1}^{(1)} \otimes \Omega_{2}^{(2)} \right) \vert \omega_{1} \rangle \otimes \vert \omega_{2} \rangle = \vert \Omega_{1}^{(1)} \omega_{1} \rangle \otimes \vert \Omega_{2}^{(2)} \otimes \omega_{2} \rangle.
\end{align*}

We have the equivalences:

\begin{align*}
\mathbb{V}_{1 \otimes 2} \equiv \mathbb{V}_{1} \otimes \mathbb{V}_{2}, \qquad \vert \omega_{1} \omega_{2} \rangle \equiv \vert \omega_{1} \rangle \otimes \vert \omega_{2} \rangle, \qquad \Omega_{1} \equiv \Omega_{1}^{(1)} \otimes I^{(2)}, \qquad \Omega_{2} \equiv I^{(1)} \otimes \Omega_{2}^{(2)}.
\end{align*}

Remarks:
1) The direct product is a product of /vectors from two different spaces/.
2) The direct product is a linear operation:
   
\begin{align*}
\left( \alpha \vert x_{1} \rangle + \alpha^{\prime} \vert x_{1}^{\prime} \rangle \right) \otimes \left( \beta \vert x_{2} \rangle \right) = \alpha \beta \vert x_{1} \rangle \otimes \vert x_{2} \rangle + \alpha^{\prime} \beta \vert x_{1}^{\prime} \rangle \otimes \vert x_{2} \rangle.
\end{align*}
   
3) The dimensionality of \(\mathbb{V}_{1} \otimes \mathbb{V}_{2}\) is the product of the dimensionality of \(\mathbb{V}_{1}\) and the dimensionality of \(\mathbb{V}_{2}\): to each basis vector \(\ket{\omega_{1}}\) of \(\mathbb{V}_{1}\) and \(\ket{\omega_{2}}\) of \(\mathbb{V}_{2}\), there is one and only one basis vector \(\ket{\omega_{1}} \otimes \ket{\omega_{2}}\) of \(\mathbb{V}_{1} \otimes \mathbb{V}_{2}\).
4) Not every element of a direct product space \(\mathbb{V}_{1} \otimes \mathbb{V}_{2}\) is a direct product; for example: \(\ket{\psi} = \vert \omega_{1}^{\prime} \rangle \otimes \vert \omega_{2}^{\prime} \rangle + \vert \omega_{1}^{\prime \prime} \rangle \otimes \vert x_{2}^{\prime \prime} \rangle\).

The inner product of \(\vert \omega_1 \rangle \otimes \vert \omega_{2} \rangle\) and \(\vert \omega_{1}^{\prime} \rangle \otimes \vert \omega_{2}^{\prime} \rangle\) is

\begin{align*}
\left( \langle \omega_{1}^{\prime} \vert \otimes \langle \omega_{2}^{\prime} \vert \right) \left( \vert \omega_{1} \rangle \otimes \vert \omega_{2} \rangle \right) = \left \langle \omega_{1}^{\prime} \vert \omega_{1} \right \rangle \left \langle \omega_{2}^{\prime} \vert \omega_{2} \right \rangle = \delta \left( \omega_{1}^{\prime} - \omega_{1} \right) \delta \left( \omega_{2}^{\prime} - \omega_{2} \right).
\end{align*}

Because the basis \(\vert \omega_1 \rangle \otimes \vert \omega_{2} \rangle\) spans \(\mathbb{V}_{1} \otimes \mathbb{V}_{2}\), the equation above defines the inner product between any two vectors. A ket \(\vert \psi \rangle\) may be expanded as:

\begin{align*}
\vert \psi \rangle = \sum_{\omega_{1}} \sum_{\omega_{2}} \vert \omega_{1} \rangle \otimes \vert \omega_{2} \rangle \left(\langle \omega_{1} \vert \otimes \langle \omega_{2} \vert \right) \vert \psi \rangle \equiv \sum_{\omega_{1}} \sum_{\omega_{2}} C_{\omega_{1}, \omega_{2}} \vert \omega_{1} \rangle \otimes \vert \omega_{2} \rangle.
\end{align*}

in practice, one usually works in a basis, usually the coordinate basis comprised of the simultaneous eigenkets \(\vert x_1 x_2 \rangle\) of \(X_{1}\) and \(X_{2}\):

\begin{align*}
X_{1} \vert x_{1} x_{2} \rangle = x_{1} \vert x_{1} x_{2} \rangle,
\end{align*}

\begin{align*}
X_{2} \vert x_{1} x_{2} \rangle = x_{2} \vert x_{1} x_{2} \rangle.
\end{align*}

The normalization is:

\begin{align*}
\left \langle x_{1}^{\prime} x_{2}^{\prime} \vert x_{1} x_{2} \right \rangle = \delta \left( x^{\prime}_{1} - x_{1} \right) \delta \left( x_{2}^{\prime} - x_{2} \right).
\end{align*}

In this basis:

\begin{align*}
\vert \psi \rangle \longrightarrow \left \langle x_{1} x_{2} \vert \psi \right \rangle = \psi \left( x_{1}, x_{2} \right),
\end{align*}

\begin{align*}
X_{i} \longrightarrow x_{i},
\end{align*}

\begin{align*}
P_{i} \longrightarrow - i \hbar \partial_{x_{i}},
\end{align*}

and we may interpret

\begin{align*}
P \left( x_{1}, x_{2} \right) = \left \lvert \left \langle x_{1} x_{2} \vert \psi \right \rangle  \right \rvert^{2}.
\end{align*}

Descending to coordinate basis:

\begin{align*}
\vert \psi \rangle &= \sum_{\omega_{1}} \sum_{\omega_{2}} C_{\omega_{1}, \omega_{2}} \vert \omega_{1} \rangle \otimes \vert \omega_{2} \rangle \xrightarrow[]{\text{coordinate basis}} \\
&\psi \left( x_{1}, x_{2} \right) = \sum_{\omega_{1}} \sum_{\omega_{2}} C_{\omega_{1}, \omega_{2}} \omega_{1} \left( x_{1} \right) \omega_{2} \left( x_{2} \right).
\end{align*}

The Schrodinger equation for a two particle ket \(\vert \psi \rangle\) living in \(\mathbb{V}_{1 \otimes 2}\) is:

\begin{align*}
i \hbar \vert \dot{\psi} \rangle = \left[ \dfrac{P_{1}^{2}}{2m_{1}} + \dfrac{P_{2}^{2}}{2m_{2}} + V \left( X_{1}, X_{2} \right) \right] \vert \psi \rangle = H \vert \psi \rangle.
\end{align*}

1) If \(H\) is *separable*, the time-independent Schrodinger equation, for a stationary state \(\vert \psi \left( t \right) \rangle = \vert E \rangle \exp \left \lbrace - i E t / \hbar \right \rbrace\) is

\begin{align*}
\left[ H_{1} \left( X_{1}, P_{1} \right) + H_{2} \left( X_{2}, P_{2} \right) \right] \vert E \rangle = E \vert E \rangle.
\end{align*}

Operators of particle 1 commute with those of particle 2. Thus we have \(\left[ H_1, H_2 \right] = 0\): \(H_{1}\) and \(H_{2}\) share an eigenbasis. Their simultaneous eigenkets are \(\vert E \rangle = \vert E_1 \rangle \otimes \vert E_2 \rangle = \vert E_{1} E_{2} \rangle\), where \(\vert E_1 \rangle\) and \(\vert E_2 \rangle\) are solutions to

\begin{align*}
H_{1}^{(1)} \vert E_{1} \rangle = E_{1} \vert E_{1} \rangle
\end{align*}

and

\begin{align*}
H_{2}^{(1)} \vert E_{2} \rangle = E_{2} \vert E_{2} \rangle.
\end{align*}

The state \(\vert E_1 \rangle \otimes \vert E_2 \rangle\) corresponds to particle \(1\) being in the energy eigenstate \(\vert E_1 \rangle\) and particle \(2\) being in the energy eigenstate \(\vert E_{2} \rangle\). Clearly then,

\begin{align*}
H \vert E \rangle = \left( H_{1} + H_{2} \right) \vert E_{1} \rangle \otimes \vert E_{2} \rangle = \left( E_{1} + E_{2} \right) \vert E_{1} \rangle \otimes \vert E_{2} \rangle = \left( E_{1} + E_{2} \right) \vert E \rangle,
\end{align*}

so that

\begin{align*}
E = E_{1} + E_{2}.
\end{align*}

Feeding

\begin{align*}
\vert E \rangle = \vert E_1 \rangle \otimes \vert E_2 \rangle = \vert E_{1} E_{2} \rangle
\end{align*}

in

\begin{align*}
\left[ H_{1} \left( X_{1}, P_{1} \right) + H_{2} \left( X_{2}, P_{2} \right) \right] \vert E \rangle = E \vert E \rangle,
\end{align*}

we get

\begin{align*}
\vert \psi \left( t \right) \rangle = \vert E_{1} \rangle \exp \left \lbrace - i E_{1} t/ \hbar  \right \rbrace \otimes \vert E_{2} \rangle \exp \left \lbrace - i E_{2} t/ \hbar \right \rbrace.
\end{align*}

Descending to coodinate basis:

\begin{align*}
&\vert \psi \left( t \right) \rangle = \vert E_{1} \rangle \exp \left \lbrace - i E_{1} t/ \hbar  \right \rbrace \otimes \vert E_{2} \rangle \exp \left \lbrace - i E_{2} t/ \hbar \right \rbrace \xrightarrow[]{\text{coordinate basis}} \\
& \psi_{E} \left( x_{1}, x_{2}, t \right) = \psi_{E} \left( x_{1}, x_{2} \right) \exp \left \lbrace - i E t / \hbar  \right \rbrace = \psi_{E_{1}} \left( x_{1} \right) \exp \left \lbrace - i E_{1} t/ \hbar \right \rbrace \psi_{E_{2}} \left( x_{2} \right) \exp \left \lbrace - i E_{2} t/ \hbar  \right \rbrace,
\end{align*}

where \(\psi_{E_{1}}\) and \(\psi_{E_{2}}\) are eigenfunctions of the one-particle Schrodinger equation with eigenvalues \(E_{1}\) and \(E_{2}\) respectively.

2) If \(H\) is *not separable*, i.e.,

\begin{align*}
V \left( X_{1}, X_{2} \right) \neq V \left( X_{1} \right) + V \left( X_{2} \right),
\end{align*}

the solution is irreducible to a direct product of the solutions of two single-particle problems, and must be treated case-by-case, apart from a special case when:

\begin{align*}
V \left( X_{1}, X_{2} \right) = V \left( X_{1} - X_{2} \right).
\end{align*}

In this case, a /similarity transform/ to /Jacobi coordinates/:

\begin{align*}
X_{\text{CM}} = \dfrac{m_{1} X_{1} + m_{2} X_{2}}{m_{1} + m_{2}}, \quad \text{and} \quad X_{\text{rel}} = X_{1} - X_{2},
\end{align*}

reduces the problem to that of two independent fictitious particles: one, the \(\text{CM}\) which is free, has mass \(M = m_{1} + m_{2}\) and momentum \(P_{\text{CM}} = M \dot{X}_{\text{CM}} = m_{1} \dot{X}_{1} + m_{2} \dot{X_{2}}\), and another, with the /reduced mass/ \(\mu = m_{1} m_{2}/ \left( m_{1} + m_{2} \right)\), momentum \(P = \mu \dot{X}_{\text{rel}}\), moving under the influence of \(V(x)\):

\begin{align*}
H \left( X_{1}, P_{1} ; P_{2}, P_{2} \right) &\xrightarrow[]{\text{Jacobi coordinates}} H \left( X_{\text{CM}}, P_{\text{CM}}; X_{\text{rel}}, P_{\text{rel}} \right) \\
&= H_{\text{CM}} + H_{\text{rel}} = \dfrac{P_{\text{CM}}^{2}}{2M} + \dfrac{P_{\text{rel}}^{2}}{2 \mu} + V \left( X \right).
\end{align*}

See =Exercise 2.5.4= and =Exercise 2.7.6=. We have the commutation relations

\begin{align*}
\left[ X_{\text{CM}}, P_{\text{CM}} \right] = i \hbar
\end{align*}

\begin{align*}
\left[ X_{\text{rel}}, P_{\text{rel}} \right] = i \hbar,
\end{align*}

and all other commutators zero. The eigenkets of \(H\) now factorize as:

\begin{align*}
\vert \psi_{E} \left( t \right) \rangle = \exp \left \lbrace - i E t / \hbar  \right \rbrace \vert \psi_{\text{CM}} \rangle \otimes \vert \psi_{\text{rel}} \rangle, \quad \text{and} \quad E = \dfrac{P_{\text{CM}}^{2}}{2M} + E_{\text{rel}}.
\end{align*}

Descending to coordinate basis:

\begin{align*}
&\vert \psi_{E} \left( t \right) \rangle = \exp \left \lbrace - i E t / \hbar  \right \rbrace \vert \psi_{\text{CM}} \rangle \otimes \vert \psi_{\text{rel}} \rangle \xrightarrow[]{\text{coordinate basis}} \\
&\psi_{E} \left( x_{\text{CM}}, x_{\text{rel}} \right) = \dfrac{1}{\left( 2 \pi \hbar \right)^{1/2}} \exp \left \lbrace i p_{\text{CM}} \cdot x_{\text{CM}} / \hbar \right \rbrace \cdot \psi_{E_{\text{rel}}} \left( x \right),
\end{align*}
and

\begin{align*}
E = \dfrac{p_{\text{CM}}^{2}}{2M} + E_{\text{rel}}.
\end{align*}

Since the \(\text{CM}\) drifts along as a free particle, one usually chooses to study the problem in the \(\text{CM}\) frame. In this case \(E_{\text{CM}} = P_{\text{CM}}^{2}/2M\) drops out of the energy, and the plane wave factor in \(\psi\) representing \(\text{CM}\) motion becomes a constant.

The entirety of what has been mentioned till now generalizes in a straightforward manner to arbitrary number of particles except for a non-separable \(H\) but a \(V\) as a functions of difference of coordinates: a transform to Jacobi coordinates does not yield a separable equation expect for when \(V\) is (or can be recast as) quadratic in in coordinates. In such cases, the oscillators become independent and their energies add both in the classical and quantum cases.

Generalization from one-dimension (which is what we have been considering so far) to more than one dimension is mathematically equivalent to an increasing in the number of particles equal to the increase in the number of dimensions.

A special case of many particle systems is the family of systems comprised of /identical particles/. Two particles are identical when no conceivable experiment can distinguish between their intrinsic properties. Within the ambits of classical mechanics, there is no such thing as /indistinguishability/ - /intrinsic/ to each particle is its /unique trajectory/ in configuration space. In contrast, /non-locality/ and /superposition/ in /quantum mechanics/ allows for the notion of /indistinguishability/.

If a measurement of \(\Omega\) of two /identical/ particles yields \(\omega_1\) and \(\omega_2\), the state vectors /before/ and /after/ measurement satisfy the constraint

\begin{align*}
\vert \psi \left( \omega_{1}, \omega_{2} \right) \rangle = \alpha \vert \psi \left( \omega_{2}, \omega_{1} \right) \rangle
\end{align*}

where \(\alpha\) is any complex number. In the \(\vert \omega_{1} \omega_{2} \rangle\) basis we may /not/ have:

\begin{align*}
\vert \psi \left( \omega_{1}, \omega_{2} \right) \rangle \longleftrightarrow \vert \omega_{1} \omega_{2} \rangle \quad \text{and} \quad \vert \psi \left( \omega_{2}, \omega_{1} \right) \rangle \longleftrightarrow \vert \omega_{2} \omega_{1} \rangle
\end{align*}

since \(\vert \omega_{1} \omega_{2} \rangle\) and \(\vert \omega_{2} \omega_{1} \rangle\) are not multiples of each other. The superpositions

\begin{align*}
\vert \psi \left( \omega_{1}, \omega_{2} \right) \rangle &\longleftrightarrow \beta \vert \omega_{1} \omega_{2} \rangle + \gamma \vert \omega_{2} \omega_{1} \rangle \quad \\
&\text{and} \quad \vert \psi \left( \omega_{2}, \omega_{1} \right) \rangle \longleftrightarrow \beta \vert \omega_{2} \omega_{1} \rangle + \gamma \vert \omega_{1} \omega_{2} \rangle
\end{align*}

,however, work just fine for:

\begin{align*}
\beta = \alpha \gamma \quad \text{and} \quad \gamma = \alpha \beta
\end{align*}

is solved by \(\beta = \pm \gamma\) and \(\alpha = \pm 1\). The allowed (un-normalized) /state vector/ in the \(\vert \omega_{1} \omega_{2} \rangle\) basis therefore are:

\begin{align*}
\vert \omega_{1} \omega_{2}, S \rangle = \vert \omega_{1} \omega_{2} \rangle + \vert \omega_{2} \omega_{1} \rangle \quad \text{and} \quad \vert \omega_{1} \omega_{2}, A \rangle = \vert \omega_{1} \omega_{2} \rangle - \vert \omega_{2} \omega_{1} \rangle,
\end{align*}

called respectively the /symmetric/ and /anti-symmetric/ state vectors. Symmetric states are called /bosons/ and anti-symmetric states are called /fermions/ - the Hilbert space of two identical particles may /not/ accomodate /both/ bosons and fermions for

\begin{align*}
\beta \vert \omega_{1} \omega_{2} , S \rangle + \gamma \vert \omega_{1} \omega_{2}, A \rangle = \alpha \left( \beta \vert \omega_{2} \omega_{1}, S \rangle + \gamma \vert \omega_{2} \omega_{1}, A \rangle \right)
\end{align*}

and thus

\begin{align*}
\beta + \gamma = \alpha \left( \beta - \gamma \right) \quad \text{and} \quad \beta - \gamma = \alpha \left( \beta + \gamma \right)
\end{align*}

only has solutions \(\alpha = + 1\) and \(\vert \omega_1 \omega_2, A \rangle = \vert 0 \rangle\) or \(\alpha = - 1\) and \(\vert \omega_1 \omega_2, S \rangle = \vert 0 \rangle\). Observations confirm this expectation - once a boson, /always/ a boson, such as pions, photons, and gravitons, and once a fermion, /always/ a fermion such as electrons, protons, and neutrons.

/Two identical fermions cannot be in the same quantum state/ for to say so is to say that a measurement of \(\Omega\) yields say \(\omega\) for /both/ of them which is equivalent to saying that non-existent states have measureable properties:

\begin{align*}
\Omega \vert \omega \omega, A \rangle = \Omega \left( \vert \omega \omega \rangle - \vert \omega \omega \rangle \right)  =  \Omega \vert 0 \rangle = \omega \vert 0 \rangle,
\end{align*}

which is bogus. This is called the /Pauli exclusion principle/.

*Once a boson, always a boson? Says /who/?*

Pair of eigenkets \(\vert \omega_1 \omega_2 \rangle\) and \(\vert \omega_2 \omega_1 \rangle\) of the direct product Hilbert space \(\mathbb{V}_{1 \otimes 2}\) combine to to form either a boson or a fermion but /nothing else/:

\begin{align*}
\mathbb{V}_{1 \otimes 2} = \mathbb{V}_{S} \oplus \mathbb{V}_{A},
\end{align*}

where \(\mathbb{V}_{S}\) is the /bosonic Hilbert space/ and \(\mathbb{V}_{A}\) is the /fermionic Hilbert space/. This is true for two identical particles. For three or more identical particles \(\dim \mathbb{V}_{1 \otimes 2} > \dim \mathbb{V}_{S} \oplus \dim \mathbb{V}_{A}\). Note that \(\dim \mathbb{V}_{S} > \dim \mathbb{V}_{A}\) because of Pauli's exclusion principle.

*How do I know whether I'm in Bosonia or Fermionia?*

For a two-particle bosonic Hilbert spaces, the normalization for the eigenkets is:

\begin{align*}
\vert \omega_{1} \omega_{2}, S \rangle =
\begin{cases}
2^{-1/2} \left[ \vert \omega_{1} \omega_{2} \rangle + \vert \omega_{2} \omega_{1} \rangle \right] \quad &\text{if} \quad \omega_{1} \neq \omega_{2} \\
\vert \omega \omega \rangle \quad &\text{if} \quad \omega_{1} = \omega_{2} = \omega \\
\end{cases}.
\end{align*}

\begin{align*}
\vert \omega_{1} \omega_{2}, A \rangle =
2^{-1/2} \left[ \vert \omega_{1} \omega_{2} \rangle - \vert \omega_{2} \omega_{1} \rangle \right].
\end{align*}

An arbitrary two-particle bosonic state vector \(\vert \psi_S \rangle\) expanded in the in terms of the eigenkets of operator \(\Omega\) with a /discrete spectrum/:

\begin{align*}
\vert \psi_{S} \rangle \xrightarrow[]{\text{\(\Omega\) basis}}
\begin{cases}
\sum_{\omega_{1}, \omega_{2}}^{\prime} 2^{-1/2} \vert \omega_{1} \omega_{2} \rangle \langle \omega_{1} \omega_{2} \vert \left[ \vert \omega_{1} \omega_{2} \rangle + \vert \omega_{2} \omega_{1} \rangle \right] \quad &\text{if} \quad \omega_{1} \neq \omega_{2} \\
\sum_{\omega_{1}, \omega_{2}}^{\prime} \vert \omega_{1} \omega_{2} \rangle \langle \omega_{1} \omega_{2} \vert \omega \omega \rangle
\end{cases}.
\end{align*}

The sum is restricted to prevent double-counting of indistinguishable states \(\vert \omega_1 \omega_2, S \rangle\) and \(\vert \omega_2 \omega_1, S \rangle\). The probability of obtaining \(\omega_1\) and \(\omega_{2}\) on a measurement of \(\Omega\) is

\begin{align*}
P_{S} \left( \omega_{1}, \omega_{2} \right) = \left \lvert \left \langle \omega_{1} \omega_{2}, S \vert \psi_{S} \right \rangle  \right \rvert^{2},
\end{align*}

and thus

\begin{align*}
\sum_{\omega_{1}, \omega_{2}}^{\prime} P_{S} \left( \omega_{1}, \omega_{2} \right) = \sum_{\omega_{1}, \omega_{2}}^{\prime} \left \lvert \left \langle \omega_{1} \omega_{2}, S \vert \psi_{S} \right \rangle  \right \rvert^{2} = 1.
\end{align*}

In terms of the eigenkets of an operator \(\Lambda\) with a /continous spectrum/, the normalization condition is:

\begin{align*}
\iint P_{S} \left( \lambda_{1}, \lambda_{2} \right) \dfrac{d \lambda_{1} d \lambda_{2}}{2} = \iint \left \lvert \left \langle \lambda_{1} \lambda_{2}, S \vert \psi_{S} \right \rangle  \right \rvert^{2} \dfrac{d \lambda_{1} d \lambda_{2}}{2} = 1,
\end{align*}

where the measure has been modified to account for the double-counting. With

\begin{align*}
\vert \psi \left( \lambda_{1}, \lambda_{2} \right) \rangle \equiv 2^{-1/2} \left \langle \lambda_{1} \lambda_{2}, S \vert \psi_{S} \right \rangle
\end{align*}

an equivalent normalization condition is

\begin{align*}
\iint \left \lvert \psi_{S} \left( \lambda_{1}, \lambda_{2} \right)  \right \rvert^{2} d \lambda_{1} d \lambda_{2} = \iint \left \langle \psi_{S} \vert \lambda_{1} \lambda_{2} \right \rangle \left \langle \lambda_{1} \lambda_{2} \vert \psi_{S} \right \rangle d \lambda_{1} d \lambda_{2} = 1,
\end{align*}

for

\begin{align*}
&\vert \psi \left( \lambda_{1}, \lambda_{2} \right) \rangle \equiv 2^{-1/2} \left \langle \lambda_{1} \lambda_{2}, S \vert \psi_{S} \right \rangle \\
&\Longrightarrow P_{S} \left( \lambda_{1} , \lambda_{2} \right) = 2 \left \lvert \psi_{S} \left( \lambda_{1}, \lambda_{2} \right)  \right \rvert^{2}
\quad \text{and} \quad \psi_{S} \left( \lambda_{1}, \lambda_{2} \right) = \left \langle \lambda_{1} \lambda_{2} \vert \psi_{S} \right \rangle.
\end{align*}

For a two-particle fermionic Hilbert spaces, the normalization for the eigenkets is:

\begin{align*}
\vert \omega_{1} \omega_{2}, A \rangle =
2^{-1/2} \left[ \vert \omega_{1} \omega_{2} \rangle - \vert \omega_{2} \omega_{1} \rangle \right].
\end{align*}

An arbitrary two-particle fermionic state vector \(\vert \psi_S \rangle\) expanded in the in terms of the eigenkets of operator \(\Omega\) with a /discrete spectrum/:

\begin{align*}
\vert \psi_{A} \rangle \xrightarrow[]{\text{\(\Omega\) basis}}
\sum_{\omega_{1}, \omega_{2}}^{\prime} 2^{-1/2} \vert \omega_{1} \omega_{2} \rangle \langle \omega_{1} \omega_{2} \vert \left[ \vert \omega_{1} \omega_{2} \rangle - \vert \omega_{2} \omega_{1} \rangle \right]
\end{align*}

The sum is restricted to prevent double-counting of indistinguishable states \(\vert \omega_1 \omega_2, A \rangle\) and \(\vert \omega_2 \omega_1, A \rangle\). The probability of obtaining \(\omega_1\) and \(\omega_{2}\) on a measurement of \(\Omega\) is

\begin{align*}
P_{A} \left( \omega_{1}, \omega_{2} \right) = \left \lvert \left \langle \omega_{1} \omega_{2}, A \vert \psi_{A} \right \rangle  \right \rvert^{2},
\end{align*}

and thus

\begin{align*}
\sum_{\omega_{1}, \omega_{2}}^{\prime} P_{A} \left( \omega_{1}, \omega_{2} \right) = \sum_{\omega_{1}, \omega_{2}}^{\prime} \left \lvert \left \langle \omega_{1} \omega_{2}, A \vert \psi_{A} \right \rangle  \right \rvert^{2} = 1.
\end{align*}

In terms of the eigenkets of an operator \(\Lambda\) with a /continous spectrum/, the normalization condition is:

\begin{align*}
\iint P_{A} \left( \lambda_{1}, \lambda_{2} \right) \dfrac{d \lambda_{1} d \lambda_{2}}{2} = \iint \left \lvert \left \langle \lambda_{1} \lambda_{2}, A \vert \psi_{A} \right \rangle  \right \rvert^{2} \dfrac{d \lambda_{1} d \lambda_{2}}{2} = 1,
\end{align*}

where the measure has been modified to account for the double-counting. With

\begin{align*}
\vert \psi \left( \lambda_{1}, \lambda_{2} \right) \rangle \equiv 2^{-1/2} \left \langle \lambda_{1} \lambda_{2}, A \vert \psi_{A} \right \rangle
\end{align*}

an equivalent normalization condition is

\begin{align*}
\iint \left \lvert \psi_{A} \left( \lambda_{1}, \lambda_{2} \right)  \right \rvert^{2} d \lambda_{1} d \lambda_{2} = \iint \left \langle \psi_{A} \vert \lambda_{1} \lambda_{2} \right \rangle \left \langle \lambda_{1} \lambda_{2} \vert \psi_{A} \right \rangle d \lambda_{1} d \lambda_{2} = 1,
\end{align*}

for

\begin{align*}
&\vert \psi \left( \lambda_{1}, \lambda_{2} \right) \rangle \equiv 2^{-1/2} \left \langle \lambda_{1} \lambda_{2}, A \vert \psi_{A} \right \rangle \\
&\Longrightarrow P_{A} \left( \lambda_{1} , \lambda_{2} \right) = 2 \left \lvert \psi_{A} \left( \lambda_{1}, \lambda_{2} \right)  \right \rvert^{2}
\quad \text{and} \quad \psi_{A} \left( \lambda_{1}, \lambda_{2} \right) = \left \langle \lambda_{1} \lambda_{2} \vert \psi_{A} \right \rangle.
\end{align*}

A measurement of \(\Lambda\) for a two-particle (of identical particles) state whose fermionic/bosonic nature is as of yet unbeknown will yield:

\begin{align*}
P_{S/A} \left( \lambda_{1}, \lambda_{2} \right) &= 2 \left \lvert \psi_{S/A} \left( \lambda_{1}, \lambda_{2} \right)  \right \rvert^{2} \\
&= 2 \left \lvert 2^{-1/2} \left[ \vert \lambda_{1} \rangle \vert \lambda_{2} \rangle \pm \vert \lambda_{2} \rangle \vert \lambda_{1} \rangle \right]  \right \rvert^{2} \\
&= \left \lvert \lambda_{1}  \right \rvert^{2} \left \lvert \lambda_{2} \right \rvert^{2} + \left \lvert \lambda_{2}  \right \rvert^{2} \left \lvert \lambda_{1}  \right \rvert^{2} \pm \left[ \left \langle \lambda_{1} \vert \lambda_{1} \right \rangle \left \langle \lambda_{2} \vert \lambda_{2} \right \rangle + \left \langle \lambda_{2} \vert \lambda_{2} \right \rangle \left \langle \lambda_{1} \vert \lambda_{1} \right \rangle \right].
\end{align*}

\(\left[ \left \langle \lambda_{1} \vert \lambda_1 \right \rangle \left \langle \lambda_{2} \vert \lambda_2 \right \rangle + \left \langle \lambda_{2} \vert \lambda_{2} \right \rangle \left \langle \lambda_{1} \vert \lambda_{1} \right \rangle \right]\) is called the /interference term/. Now notice that

\begin{align*}
P_{S} \left( \lambda_{1} \to \lambda, \lambda_{2} \to \lambda \right) = 4 \left \lvert \lambda  \right \rvert^{4} \quad \text{and} \quad P_{A} \left( \lambda_{1} \to \lambda, \lambda_{2} \to \lambda \right) = 0.
\end{align*}

\(P_{S}\) is called a /Bose-Einstein particle statistics/ and \(P_{A}\) is called a /Fermi-Dirac particle statistics/. The joint probability density function over \(\lambda_1\) and \(\lambda_{2}\) will /vanish/ along the \(\lambda_1 = \lambda_2\) line for fermions; for bosons it will have /mode/ there. This striking difference immediately lends way for distinguishing the fermionic/bosonic nature of the as of yet unknown two-particle state function - via an empirical reconstruction of the the probability distribution over the spectrum of some arbitrary operator (usually position) from their ensemble averages of its eigenvalue measurements.

A measurement of \(\Lambda\) /also/ betrays the /indistinguishability/ of particles: to say that two particles are /not/ indistinguishable is to say that they have /labels/, be they as they may unbeknown to us. Labels are instantiations of a certain property say \(P\). Say two possible labels for the property \(P\) of a state are \(A\) and \(B\). We will then have:

\begin{align*}
P_{S/A} \left( \lambda_{1}, \lambda_{2} \right) &= \left \lvert \lambda_{1}  \right \rvert_{A}^{2} \left \lvert \lambda_{2} \right \rvert_{B}^{2} + \left \lvert \lambda_{2}  \right \rvert_{B}^{2} \left \lvert \lambda_{1}  \right \rvert_{A}^{2} \\
&\pm \left[ {}_{A}\left \langle \lambda_{1} \vert \lambda_{1} \right \rangle_{B} {}_{B} \left \langle \lambda_{2} \vert \lambda_{2} \right \rangle_{A} + {}_{B} \left \langle \lambda_{2} \vert \lambda_{2} \right \rangle_{A} {}_{A}\left \langle \lambda_{1} \vert \lambda_{1} \right \rangle_{B} \right].
\end{align*}

so that

\begin{align*}
P_{S/A} \left( \lambda_{1} \to \lambda, \lambda_{2} \to \lambda \right) = 2 \left \lvert \lambda  \right \rvert_{A}^{2} \left \lvert \lambda  \right \rvert_{B}^{2} \pm 2 \left \lvert {}_{A}\left \langle \lambda \vert \lambda \right \rangle_{B} \right \rvert^{2}
\end{align*}

We have the ratio

\begin{align*}
\dfrac{\left \lvert {}_{A}\left \langle \lambda \vert \lambda \right \rangle_{B} \right \rvert^{2}}{\left \lvert \lambda  \right \rvert_{A}^{2} \left \lvert \lambda  \right \rvert_{B}^{2}} \xrightarrow[A = B]{\text{identical bosons}} 1 \quad \text{and} \quad \dfrac{\left \lvert {}_{A}\left \langle \lambda \vert \lambda \right \rangle_{B} \right \rvert^{2}}{\left \lvert \lambda  \right \rvert_{A}^{2} \left \lvert \lambda  \right \rvert_{B}^{2}} \xrightarrow[A = B]{\text{identical fermions}} 1.
\end{align*}

whose computation betrays indistinguishablity: any deviation from \(1\) reflects our ignorance of /some/ label that distinguishes these particles based on property \(P\).

That's how you determine whether you're in Bosonia or Fermionia. Are you so much better off now?

*Is it possible that some of these identical particles manifest a bosonic nature while the other a fermionic nature?*

To say that they do so is to say that spanning the state vector of these identical particles requires kets from /both/ bosonic and fermionic Hilbert spaces. Wait a second, what happened to once a boson/fermion always a boson/fermion? Indeed. If the evolution of the state vector of a bunch of identical particles is restricted to a fermionic/bosonic subspace, how could it possibly have picked those non-vanishing coefficients for the kets of the bosonic/fermionic subspace? Did it sneak a dip? There you have your answer.

* Symmetries and Their Consequences
CLOSED: [2022-11-22 Tue 05:52]
:LOGBOOK:
CLOCK: [2022-11-21 Mon 15:45]--[2022-11-21 Mon 16:17] =>  0:32
:END:
:LOGBOOK:
CLOCK: [2022-11-19 Sat 18:46]--[2022-11-19 Sat 19:32] =>  0:46
CLOCK: [2022-11-19 Sat 16:36]--[2022-11-19 Sat 16:55] =>  0:19
CLOCK: [2022-11-19 Sat 16:08]--[2022-11-19 Sat 16:22] =>  0:14
CLOCK: [2022-11-19 Sat 14:02]--[2022-11-19 Sat 15:18] =>  1:16
:END:
In the /active transformation picture/ (in which the particle is physically displaced to the /right/ by \(\epsilon\)), the quantum correspondence for classical /translations/ is

\begin{align*}
\left \langle X  \right \rangle \to \left \langle X  \right \rangle + \epsilon \quad \text{or} \quad \left \langle \psi_{\epsilon} \left \lvert X  \right \rvert \psi_{\epsilon} \right \rangle = \left \langle \psi \left \lvert X  \right \rvert \psi \right \rangle + \epsilon,
\end{align*}

\begin{align*}
\left \langle P  \right \rangle \to \left \langle P  \right \rangle \quad \text{or} \quad \left \langle \psi_{\epsilon} \left \lvert P  \right \rvert \psi_{\epsilon} \right \rangle = \left \langle \psi \left \lvert P  \right \rvert \psi \right \rangle.
\end{align*}

In terms of a /translation operator/ \(T \left( \epsilon \right)\),

\begin{align*}
T \left( \epsilon \right) \vert \psi \rangle = \vert \psi_{\epsilon} \rangle,
\end{align*}

\begin{align*}
\left \langle \psi \left \lvert T \left( \epsilon \right)^{\dagger} X T \left( \epsilon \right)  \right \rvert \psi \right \rangle = \left \langle \psi \left \lvert X  \right \rvert \psi \right \rangle + \epsilon,
\end{align*}

\begin{align*}
\left \langle \psi \left \lvert T \left( \epsilon \right)^{\dagger} P T \left( \epsilon \right)  \right\rvert \psi \right \rangle = \left \langle \psi \left \lvert P  \right \rvert \psi \right \rangle.
\end{align*}

In /coordinate basis/:

\begin{align*}
T \left( \epsilon \right) \vert x \rangle &= \vert x + \epsilon \rangle
\end{align*}

\begin{align*}
\vert \psi_{\epsilon} \rangle = T \left( \epsilon \right) \vert \psi \rangle &= T \left( \epsilon \right) \int_{-\infty}^{\infty} \vert x \rangle \left \langle x \vert \psi \right \rangle dx \\
&= \int_{-\infty}^{\infty} \vert x + \epsilon \rangle \left \langle x \vert \psi \right \rangle dx \xrightarrow[]{x^{\prime} = x + \epsilon} \\
&= \int_{-\infty}^{\infty} \vert x^{\prime} \rangle \left \langle x^{\prime} - \epsilon \vert \psi \right \rangle d x^{\prime}.
\end{align*}

Thus if \(\left \langle x \vert \psi \right \rangle = \psi \left( x \right)\) then

\begin{align*}
\left \langle x \left \lvert T \left( \epsilon \right)  \right \rvert \psi \right \rangle = \psi \left( x - \epsilon \right).
\end{align*}

Further

\begin{align*}
\left \langle \psi_{\epsilon} \left \lvert P  \right \rvert \psi_{\epsilon} \right \rangle &=
\int_{-\infty}^{\infty} \psi_{\epsilon}^{\ast} \left( x \right) \left( - i \hbar D_{x} \right) \psi_{\epsilon} \left( x \right) dx \\
&= \int_{-\infty}^{\infty} \psi^{\ast} \left( x - \epsilon \right) \left( - i \hbar D_{x} \right) \psi \left( x - \epsilon \right) dx \xrightarrow[]{x^{\prime} = x - \epsilon} \\
&= \int_{-\infty}^{\infty} \psi^{\ast} \left( x^{\prime} \right) \left( - i \hbar D_{x^{\prime}} \right) \psi \left( x^{\prime} \right) d x^{\prime} \\
&= \left \langle \psi \left \lvert P  \right \rvert \psi \right \rangle.
\end{align*}

While \(x \to x + \epsilon\) and \(p \to p\) are two /independent relations/ in classical mechanics/, in the quantum case we have: \(\left \langle x \left \lvert T \left( \epsilon \right)  \right \rvert \psi \right \rangle = \psi \left( x - \epsilon \right) \Longrightarrow \left \langle \psi_{\epsilon} \left \lvert P  \right \rvert \psi_{\epsilon} \right \rangle \left \langle \psi \left \lvert P  \right \rvert \psi \right \rangle\). The reason for this is that we should /actually/ demand the correspondence:

\begin{align*}
T \left( \epsilon \right) \vert x \rangle = \exp \left \lbrace i \epsilon g \left( x \right)/ \hbar \right \rbrace \vert x + \epsilon \rangle
\end{align*}

so that

\begin{align*}
\left \langle X  \right \rangle \xrightarrow[]{T \left( \epsilon \right)} \left \langle X  \right \rangle + \epsilon
\end{align*}

and

\begin{align*}
\left \langle P  \right \rangle \to \left \langle P  \right \rangle + \epsilon \left \langle f \left( X \right)  \right \rangle
\end{align*}

where \(f = g^{\prime}\).

\(T \left( \epsilon \right) = \exp \left \lbrace i \epsilon g \left( x \right)/ \hbar \right \rbrace \vert x + \epsilon \rangle\) only reduces to \(T \left( \epsilon \right) \vert x \rangle = \vert x + \epsilon \rangle\) on demanding \(\left \langle P  \right \rangle \to \left \langle P  \right \rangle\). (See =Exercise 11.2.1=).

The quantum correspondence for /translational invariance/ is defined by

\begin{align*}
\left \langle \psi \left \lvert H  \right \rvert \psi \right \rangle = \left \langle \psi_{\epsilon} \left \lvert H  \right \rvert \psi_{\epsilon} \right \rangle
\end{align*}

To derive the associated /conservation law/ we need the matrix elements of \(T \left( \epsilon \right)\). To order \(\epsilon\)

\begin{align*}
T \left( \epsilon \right) = I - \dfrac{i \epsilon}{\hbar} G,
\end{align*}

where the operator \(G\), called the /generator of translations/, is Hermitian.

\begin{align*}
\left \langle x \left \lvert T \left( \epsilon \right)  \right \rvert \psi \right \rangle = \psi \left( x - \epsilon \right) \Longrightarrow \psi \left( x \right) - \dfrac{i \epsilon}{\hbar} \left \langle x \left \lvert G  \right \rvert \psi \right \rangle = \psi \left( x \right) - \epsilon D_{x} \psi \Longrightarrow G = P,
\end{align*}

so

\begin{align*}
T \left( \epsilon \right) = I - \dfrac{i \epsilon}{\hbar} P.
\end{align*}

The /momentum operator/ is the generator of infinitesimal translations. The associated /conservation law/ is the /conservation of momentum/:

\begin{align*}
\left \langle \psi \left \lvert H  \right \rvert \psi \right \rangle &= \left \langle \psi_{\epsilon} \left \lvert H  \right \rvert \psi_{\epsilon} \right \rangle \\
&= \left \langle T \left( \epsilon \right) \psi \left \lvert H  \right \rvert T \left( \epsilon \right) \psi \right \rangle = \left \langle \psi \left \lvert T^{\dagger} \left( \epsilon \right) H T \left( \epsilon \right) \right \rvert \psi \right \rangle \\
&= \left \langle \psi \left \lvert \left( I + \dfrac{i \epsilon}{\hbar} P \right) H \left( I - \dfrac{i \epsilon}{\hbar} P \right)  \right \rvert \psi \right \rangle \\
&= \left \langle \psi \left \lvert H  \right \rvert \psi \right \rangle + \dfrac{i \epsilon}{\hbar} \left \langle \psi \left \lvert \left[ P, H \right]  \right \rvert \psi \right \rangle + \mathcal{O} \left( \epsilon^{2} \right).
\end{align*}

We must have:

\begin{align*}
\left \langle \psi \left \lvert \left[ P, H \right]  \right \rvert \psi \right \rangle = \left \langle \left[ P, H \right]  \right \rangle = 0 \Longrightarrow \left \langle D_{t} P  \right \rangle = 0.
\end{align*}

In the /passive transformation picture/ (in which the state vector in unaltered, but \(X\) and \(P\) are modified by \(T \left( \epsilon \right)\) - physically, the coordinate system, sources of external field if any, etc. moves to the /left/ by \(\epsilon\)), the quantum correspondence for classical translational invariance is

\begin{align*}
X \to T^{\dagger} \left( \epsilon \right) X T \left( \epsilon \right)
\end{align*}

\begin{align*}
P \to T^{\dagger} \left( \epsilon \right) P T \left( \epsilon \right)
\end{align*}

such that

\begin{align*}
T^{\dagger} \left( \epsilon \right) X T \left( \epsilon \right) = X + \epsilon I
\end{align*}

\begin{align*}
T^{\dagger} \left( \epsilon \right) P T \left( \epsilon \right) = P.
\end{align*}

The quantum correspondence for /translational invariance/ is defined by:

\begin{align*}
T^{\dagger} \left( \epsilon \right) H T \left( \epsilon \right) = H
\end{align*}

The explicit form for \(T \left( \epsilon \right)\) is same as in the active picture:

\begin{align*}
T \left( \epsilon \right) = I - \dfrac{i \epsilon}{\hbar} P,
\end{align*}

The /conservation of momentum/ follows from the requirement of translational invariance:

\begin{align*}
0 &= T^{\dagger} \left( \epsilon \right) H T \left( \epsilon \right) - H = \left( I + i \epsilon P/ \hbar \right) H \left( I - i \epsilon P / \hbar \right) - H \\
&= \dfrac{- i \epsilon}{\hbar} \left[ H, P \right] \Longrightarrow \left \langle D_{t} P  \right \rangle = 0.
\end{align*}

In the final step we have invoked Ehrenfest's theorem.

The operator \(T \left( a \right)\) corresponding to /finite translations/ \(a\) is found by dividing the interval \(a\) into \(N\) parts of size \(a/N\). As \(N \to \infty\), \(a/N\) becomes infinitesimal so that:

\begin{align*}
T \left( a/ N \right) = I - \dfrac{i a}{\hbar N} P,
\end{align*}

and a translation by \(a\) is equal to \(N\) translations by \(a/N\),

\begin{align*}
T \left( a \right) = \lim_{N \to \infty} \left( T \left( a/ N \right) \right)^{N} = \exp \left \lbrace - i a P / \hbar \right \rbrace,
\end{align*}

where we have used:

\begin{align*}
\exp \left \lbrace - a x  \right \rbrace = \lim_{N \to \infty} \left( 1 - \dfrac{a x}{N} \right)^{N}.
\end{align*}

It's a law bound move, \(P\) is the only operator so it acts like a c-number. In the \(X\) basis

\begin{align*}
T \left( a \right) \xrightarrow[]{X \text{ basis}} \exp \left \lbrace - a D_{x} \right \rbrace
\end{align*}

so that

\begin{align*}
\left \langle x \left \lvert T \left( a \right)  \right \rvert \psi \right \rangle = \psi \left( x \right) - D_{x} \psi a + D_{x}^{2} \psi \dfrac{\alpha^{2}}{2!} + \dotso.
\end{align*}

which is the full Taylor series for \(\psi \left( x - a \right)\) about the point \(x\). \(\exp \left \lbrace - i a P / \hbar \right \rbrace\) satisfies the /consistency condition/:

\begin{align*}
T \left( a \right) T \left( b \right) = \exp \left \lbrace - i a P/ \hbar  \right \rbrace \exp \left \lbrace - i b P / \hbar  \right \rbrace = \exp \left \lbrace - i \left( a + b \right) P / \hbar \right \rbrace = T \left( a + b \right),
\end{align*}

so that

\begin{align*}
T \left( a \right) T \left( b \right) \stackrel{?}{=} T \left( a + b \right),
\end{align*}

evaluates as affirmative.

For a system of \(N\) particles,

\begin{align*}
T \left( \epsilon \right) = I - \dfrac{i \epsilon}{\hbar} \sum_{i=1}^{N} P_{i} = I - \dfrac{i \epsilon}{\hbar} P,
\end{align*}

where \(P\) is the /total momentum operator/. The associated conservation law is the /conservation of total momentum/ a consequence of /translational invariance:

\begin{align*}
H \left( X, P \right) = T^{\dagger} \left( \epsilon \right) H \left( X, P \right) T \left( \epsilon \right) = H \left( X + \epsilon I, P \right)
\end{align*}

where the indices have been suppressed. For a single-particle the implication was that the particle was /free/, for a \(N\) particle system, the condition is merely that \(V\) be a function of the coordinate /differences/. *Any system whose parts interact with each other, but nothing external, will have this property.*

Translational invariance of \(H\) implies homogeneity of space: the same experiment repeated at two different places will give the same result (as seen by the local observers). Observations indicate that every known interaction - gravitational, weak, electromagnetic, and strong - is translationally invariant, in that every experiment, if repeated at a new site, will give the same result.

Time translational invariance of \(H\) implies homogeneity in time: the same experiment repeated at two different times gives the same result. Time translation invariance requires:

\begin{align*}
\left \langle D_t H  \right \rangle = 0.
\end{align*}

The associated conservation law is the /conservation of energy./ Observations indicate that every known interaction - gravitational, weak, electromagnetic, and strong - is time-translationally invariant, in that every experiment, if repeated at a different time, will give the same result.

An example of a discrete transformation is the /parity operation/. In the /active transformation picture/, classically, the parity operation corresponds to reflecting the state of the particle through the origin

\begin{align*}
x \xrightarrow[]{\text{parity}} - x,
\end{align*}

\begin{align*}
p \xrightarrow[]{\text{parity}} - p.
\end{align*}

In quantum theory, we define the action of the parity operator on the \(X\) basis as:

\begin{align*}
\Pi \vert x \rangle = \vert -x \rangle.
\end{align*}

We have:

\begin{align*}
\Pi \vert x \rangle = \vert -x \rangle \Longrightarrow \Pi \vert p \rangle = \vert -p \rangle.
\end{align*}

The action of the parity operator on an arbitrary ket is:

\begin{align*}
\Pi \vert \psi \rangle &= \Pi \int_{-\infty}^{\infty} \vert x \rangle \left \langle x \vert \psi \right \rangle dx \\
&= \int_{-\infty}^{\infty} \vert -x \rangle \left \langle x \vert \psi \right \rangle dx \\
&= \int_{-\infty}^{\infty} \vert x^{\prime} \rangle \left \langle - x^{\prime} \vert \psi \right \rangle d x^{\prime}.
\end{align*}

Therefore:

\begin{align*}
\left \langle x \vert \psi \right \rangle = \psi \left( x \right) = \psi \left( x \right) \Longrightarrow \left \langle x \left \lvert \Pi  \right \rvert \psi \right \rangle = \psi \left( -x \right).
\end{align*}

Applying the above to a momentum eigenket will furnish \(\Pi \vert p \rangle = \vert -p \rangle\). The eigenvalues of \(\Pi\) are \(\pm 1\), same as the exchange operator. Some of the properties of \(\Pi\) are:

\begin{align*}
\Pi^{2} = I,
\end{align*}

\begin{align*}
\Pi = \Pi^{-1},
\end{align*}

\begin{align*}
\text{The eigenvalues of } \Pi \text{ are} \pm 1,
\end{align*}

\begin{align*}
\Pi^{\dagger} = \Pi \quad \text{and} \quad \Pi^{\dagger} \Pi = I.
\end{align*}

\begin{align*}
\Pi^{-1} = \Pi^{\dagger} = \Pi.
\end{align*}

The eigenvectors with eigenvalue \(\pm 1\) are said to have even/odd parity. In the \(X\) basis, where

\begin{align*}
\psi \left( x \right) \xrightarrow[]{\Pi} \psi \left( -x \right),
\end{align*}

even-parity vectors have even wave functions and odd-parity vectors have odd wave functions. The same goes for the \(P\) basis since

\begin{align*}
\psi \left( p \right) \xrightarrow[]{\Pi} \psi \left( - p \right).
\end{align*}

In an arbitrary \(\Omega\) basis, \(\psi \left( \omega \right)\) need not be even or odd even if \(\vert \psi \rangle\) is a parity eigenstate (check this).

In the /passive transformation picture/, \(\Pi\) in terms of its action on the operators:

\begin{align*}
\Pi^{\dagger} X \Pi = - X,
\end{align*}

\begin{align*}
\Pi^{\dagger} P \Pi = - P.
\end{align*}

We say \(H \left( X, P \right)\) is parity invariant if

\begin{align*}
\Pi^{\dagger} H \left( X, P \right) \Pi = H \left( -X, -P \right) = H \left( X, P \right).
\end{align*}

In this case:

\begin{align*}
\left[ \Pi, H \right] = 0,
\end{align*}

and a common eigenbasis of \(\Pi\) and \(H\) can be found.
* Rotational Invariance and Angular Momentum
CLOSED: [2022-11-12 Sat 23:14]
:LOGBOOK:
CLOCK: [2022-10-26 Wed 12:42]--[2022-10-26 Wed 13:03] =>  0:21
:END:
:LOGBOOK:
CLOCK: [2022-11-26 Sat 10:39]--[2022-11-26 Sat 15:17] =>  4:38
CLOCK: [2022-11-26 Sat 04:22]--[2022-11-26 Sat 08:18] =>  3:56
CLOCK: [2022-11-22 Tue 08:19]--[2022-11-22 Tue 09:24] =>  1:05
:END:
** Infinitesimal translations in Hilbert space
The translation operator in Hilbert space along the direction \(\hat{e}\) is \(U \left[ T \left( \epsilon \hat{e} \right) \right] = I - \dfrac{i \epsilon}{\hbar} \hat{e} \cdot G\), where \(G\) is the generator of infinitesimal translations along \(\hat{e}\). The generators of infinitesimal translations along the \(x\) and \(y\) directions are, respectively,

\begin{align*}
P_{x} \xrightarrow[]{\text{coordinate basis}} - i \hbar \partial_{x},
\end{align*}

\begin{align*}
P_{y} \xrightarrow[]{\text{coordinate basis}} - i \hbar \partial_{y},
\end{align*}

\begin{align*}
P_{z} \xrightarrow[]{\text{coordinate basis}} - i \hbar \partial_{z},
\end{align*}

or

\begin{align*}
\vec{P} = P_{x} \vec{i} + P_{y} \vec{j} + P_{z} \vec{k}.
\end{align*}

\(\hat{n} \cdot \vec{P} \equiv P_{\hat{n}}\) is the generator of translations in the direction of the unit vector \(\hat{n}\).
** Finite translations in Hilbert space
Finite translation operators are found by exponentiation. Thus \(T \left( \vec{a} \right)\) which translates by \(\vec{a}\), is given by

\begin{align*}
U \left[T \left( \vec{a} \right) \right] = \exp \left \lbrace - i a P_{\hat{a}} / \hbar  \right \rbrace = \exp \left \lbrace -i a \hat{a} \cdot \vec{P}/ \hbar  \right \rbrace = \exp \left \lbrace - i \vec{a} \cdot \vec{P}/ \hbar  \right \rbrace
\end{align*}

where \(\hat{a} = \vec{a}/a\).

The law of combination for translation operators is

\begin{align*}
U \left[ T \left( \vec{b} \right) \right] U \left[ T \left( \vec{a} \right) \right] &= \exp \left \lbrace - i \vec{b} \cdot \vec{P}/ \hbar  \right \rbrace \exp \left \lbrace - i \vec{a} \cdot \vec{P}/ \hbar  \right \rbrace \\
&= \exp \left \lbrace - i \left( \vec{a} + \vec{b} \right) \cdot \vec{P}/ \hbar \right \rbrace \\
&= U \left[ T \left( \vec{a} + \vec{b} \right) \right].
\end{align*}

This is true because \(\left[ P_i, P_j \right] = 0\) and they behave just like \(c\) numbers.
** Translational invariance
A Hamiltonian with translational invariance satisfies along \(\hat{n}\) satisfies:

\begin{align*}
U^{\dagger} \left[ T_{\hat{n}} \right] H \left( X, P_{x}; Y, P_{y} \right) U \left[ T_{\hat{n}} \right] = H \left( X, P_{x}; Y, P_{y} \right) \Longrightarrow \left[ P_{\hat{n}}, H \right] = 0.
\end{align*}

i.e., there exists a common basis for \(P_{\hat{\theta}}\) and \(H\) or \(P_{\hat{\theta}}\) and \(H\) are simultaneously diagonalizable.
** Infinitesimal rotations in Hilbert space
The rotation operator in Hilbert space about the direction \(\hat{e}\) \(U \left[ R \left( \epsilon_{z} \hat{e} \right) \right] = I - \dfrac{i \epsilon}{\hbar} \hat{e} \cdot J\), where \(J\) is the generator of infinitestimal rotations about \(\hat{e}\).

\(U \left[ R \left( \epsilon\hat{e} \right) \right] = I - \dfrac{i \epsilon}{\hbar} \hat{e} \cdot J\) can be fed into the /passive transformation/ equations for an infinitesimal rotation:

\begin{align*}
U^{\dagger} \left[ R \right] X U \left[ R \right] = X - Y \epsilon_{z},
\end{align*}

\begin{align*}
U^{\dagger} \left[ R \right] Y U \left[ R \right] = X \epsilon_{z} + Y,
\end{align*}

\begin{align*}
U^{\dagger} \left[ R \right] P_{x} U \left[ R \right] = P_{x} - P_{y} \epsilon_{z},
\end{align*}

\begin{align*}
U^{\dagger} \left[ R \right] P_{y} U \left[ R \right] = P_{x} \epsilon_{z} + P_{y},
\end{align*}

to obtain

\begin{align*}
\left[ X, J_{z} \right] = - i \hbar Y,
\end{align*}

\begin{align*}
\left[ Y, J_{z} \right] = i \hbar X,
\end{align*}

\begin{align*}
\left[ P_{x}, J_{z} \right] = - i \hbar P_{y},
\end{align*}

\begin{align*}
\left[ P_{y}, J_{z} \right] = i \hbar P_{x}.
\end{align*}

\(J_{i}\) is called the /total angular momentum/. It decompses into a sum of the /orbital angular momentum/ \(L_{i}\) and the /spin angular momentum/ \(S_{i}\):

\begin{align*}
J_{i} = L_{i} + S_{i}.
\end{align*}

For the moment assume \(S_{i} = 0\) because we will descend to various coordinate bases. We will learn to do that for \(S_{i}\) later. \(S_{i} \neq 0\) and \(S_{i} = 0\) means we have ourselves a /vector wavefunction/ and a /scalar wavefunction/ respectively. The commutation relations above uniquely fix the generators of infinitesimal rotations about the \(x\), \(y\), and \(z\) directions.(=Exercise 12.2.2=) They are:

\begin{align*}
L_{x} &= Y P_{z} - Z P_{y}\\
&\xrightarrow[]{\text{rectangular coordinate basis}} - i \hbar \thinspace y \thinspace \partial_{z} + i \hbar \thinspace z \thinspace \partial_{y} \\
&\xrightarrow[]{\text{spherical coordinate basis}} i \hbar \thinspace \left( \sin \phi \thinspace \partial_{\theta} + \cos \phi \thinspace \cot \theta \thinspace \partial_{\phi} \right),
\end{align*}

\begin{align*}
L_{y} &= Z P_{x} - X P_{z} \\
& \xrightarrow[]{\text{rectangular coordinate basis}} - i \hbar \thinspace z \thinspace \partial_{x} + i \hbar \thinspace x \thinspace \partial_{z} \\
& \xrightarrow[]{\text{spherical coordinate basis}} i \hbar \left( - \cos \phi \thinspace \partial_{\theta} + \sin \phi \thinspace \cot \theta \thinspace \partial_{\phi} \right),
\end{align*}

\begin{align*}
L_{z} &= X P_{y} - Y P_{x} \\
& \xrightarrow[]{\text{rectangular coordinate basis}} - i \hbar \thinspace x \thinspace \partial_{y} + i \hbar \thinspace y \thinspace \partial_{x} \\
& \xrightarrow[]{\text{spherical coordinate basis}} - i \hbar \thinspace \partial_{\phi}.
\end{align*}

or

\begin{align*}
\vec{L} = L_{x} \vec{i} + L_{y} \vec{j} + L_{z} \vec{k}.
\end{align*}
** Commutator relations of the total angular momentum
The components of \(\vec{J}\) components satisfy the commutator relations:

\begin{align*}
\left[ J_{x}, J_{y} \right] = i \hbar J_{z}, \quad \left[ J_{y}, J_{z} \right] = i \hbar J_{x}, \quad \left[ J_{z}, J_{x} \right] = i \hbar J_{y}.
\end{align*}

Equivalently:

\begin{align*}
\left[ J_{i}, J_{j} \right] = i \hbar \sum_{k=1}^{3} \epsilon_{ijk} J_{k}.
\end{align*}

Equivalently still:

\begin{align*}
\vec{J} \times \vec{J} = i \hbar \vec{J}.
\end{align*}

\(J^{2}\) is called the /total angular momentum operator squared/:

\begin{align*}
J^{2} \equiv \vec{J} \cdot \vec{J} = J_{x}^{2} + J_{y}^{2} + J_{z}^{2}.
\end{align*}

It satisfies the commutator relations:

\begin{align*}
\left[ J^{2}, J_{x} \right] = 0, \quad \left[ J^{2}, J_{y} \right] = 0, \quad \left[ J^{2}, J_{z} \right] = 0.
\end{align*}
** Raising and lowering operators \(J_{\pm}\)
\(J_{\pm}\), called the /raising and lowering operators/ are defined as:

\begin{align*}
J_{\pm} = J_{x} \pm i J_{y}.
\end{align*}

They satisfy the commutator relations:

\begin{align*}
\left[ J_{z}, J_{\pm} \right] = \pm \hbar J_{\pm} \quad \text{and} \quad \left[ J^{2}, J_{\pm} \right] = 0.
\end{align*}

\(J_{\pm}\) raise/lower the eigenvalue of \(J_{z}\) by \(\hbar\) while leaving the eigenvalue of \(J^{2}\) alone.

** Eigenvalue problem of \(J_{z}\) and \(J^{2}\)
The solution to the eigenvalue problem of \(J_{z}\) and \(J^{2}\) is

\begin{align*}
J^{2} \vert jm \rangle = j \left( j + 1 \right) \hbar^{2} \vert jm \rangle, \quad j = 0, \thinspace 1/2, \thinspace 1, \thinspace 3/2, \thinspace \dotso
\end{align*}

\begin{align*}
J_{z} \vert jm \rangle = m \hbar \vert jm \rangle \quad m = j, \thinspace j-1, \thinspace j-2, \dotso, -j.
\end{align*}

The eigenvalue of \(J_{z}\) and \(J^{2}\) associated with its eigenket \(\vert jm \rangle\) is \(m \hbar\) and \(j \left( j + 1 \right) \hbar^{2}\) respectively. For /scalar wavefunctions/ \(\vec{J} \to \vec{L}\), half-integral values of \(j\) are discarded:

\begin{align*}
L^{2} \vert lm \rangle = l \left( l + 1 \right) \hbar^{2} \vert lm \rangle, \quad l = 0, \thinspace 1, \thinspace 2, \dotso
\end{align*}

\begin{align*}
L_{z} \vert lm \rangle = m \hbar \vert lm \rangle \quad m = l, \thinspace l-1, \thinspace l-2, \dotso, -l.
\end{align*}

\(m\) is called the /magnetic quantum number/. \(l\) is called the /azimuthal quantum number/.

Finding the eigenkets \(\vert jm \rangle\) corresponds to finding the matrix elements \(\left \langle j^{\prime} m^{\prime} \left \lvert J_{x} \right \rvert jm \right \rangle\), \(\left \langle j^{\prime} m^{\prime} \left \lvert J_{y} \right \rvert jm \right \rangle\), \(\left \langle j^{\prime} m^{\prime} \left \lvert J_{z} \right \rvert jm \right \rangle\) and \(\left \langle j^{\prime} m^{\prime} \left \lvert J^{2} \right \rvert jm \right \rangle\). The eigenket \(\vert jm \rangle\) satisfy the identity:

\begin{align*}
J_{\pm} \vert jm \rangle = \hbar \sqrt{j \left( j + 1 \right) - m \left( m \pm 1 \right)} \thinspace \vert j, m \pm 1 \rangle.
\end{align*}

Therefore:

\begin{align*}
\left \langle j^{\prime} m^{\prime} \left \lvert J_{x} \right \rvert jm \right \rangle &= \left \langle j^{\prime} m^{\prime} \left \lvert \dfrac{J_{+} + J_{-}}{2}  \right \rvert jm \right \rangle \\
&= \dfrac{\hbar}{2} \Big \lbrace \delta_{jj^{\prime}} \delta_{m^{\prime}, m+1} \sqrt{j \left( j+1 \right) - m \left( m + 1 \right)} \\
&+ \delta_{jj^{\prime}} \delta_{m^{\prime}, m-1} \sqrt{j \left( j+1 \right) - m \left( m - 1 \right)} \Big \rbrace,
\end{align*}

\begin{align*}
\left \langle j^{\prime} m^{\prime} \left \lvert J_{y} \right \rvert jm \right \rangle &= \left \langle j^{\prime} m^{\prime} \left \lvert \dfrac{J_{+} - J_{-}}{2i}  \right \rvert jm \right \rangle \\
&= \dfrac{\hbar}{2i} \Big \lbrace \delta_{jj^{\prime}} \delta_{m^{\prime}, m+1} \sqrt{j \left( j+1 \right) - m \left( m + 1 \right)} \\
&- \delta_{jj^{\prime}} \delta_{m^{\prime}, m-1} \sqrt{j \left( j+1 \right) - m \left( m - 1 \right)} \Big \rbrace,
\end{align*}

\begin{align*}
\left \langle j^{\prime} m^{\prime} \left \lvert J_{z} \right \rvert jm \right \rangle &= m \hbar \delta_{m, m^{\prime}},
\end{align*}

\begin{align*}
\left \langle j^{\prime} m^{\prime} \left \lvert J^{2}  \right \rvert jm \right \rangle &= j \left( j + 1 \right) \hbar^{2} \delta_{j, j^{\prime}}.
\end{align*}

\(J^{2}\) and \(J_{z}\) are diagonal in the \(\vert jm \rangle\) basis. \(J_{x}\) and \(J_{y}\) are /block diagonal/ in the \(\vert jm \rangle\) basis. This is because \(J_{\pm}\) do not change \(j\) when they act on \(\vert jm \rangle\). Since the \(J\)'s are all block diagonal, the blocks do not mix when we multiply them. /In particular when we consider a commutation relation such as/ \(\left[ J_x, J_y \right] = i \hbar J_{z}\), /it will be satisfied within each block./ If we denote the \((2j + 1) \times \left( 2j + 1 \right)\) block in \(J_{i}\), corresponding to a certain \(j\), by \(J_{i}^{(j)}\), then we have:

\begin{align*}
\left[ J_{x}^{(j)}, J_{y}^{(j)} \right] = i \hbar J_{z}^{(j)}, \quad j=0, \thinspace \dfrac{1}{2}, \thinspace 1, \thinspace \dotso.
\end{align*}

** Finite rotations in hilbert space
\(\hat{\theta} \cdot \vec{J} \equiv J_{\hat{\theta}}\) is the generator of rotations about the direction \(\hat{n}\). Finite rotation operators are found by exponentiation. Thus

\begin{align*}
U \left[ R \left( \vec{\theta} \right) \right] = \exp \left \lbrace - i \theta J_{\hat{\theta}} / \hbar  \right \rbrace = \exp \left \lbrace -i \theta \hat{\theta} \cdot \vec{J}/ \hbar  \right \rbrace = \exp \left \lbrace - i \vec{\theta} \cdot \vec{J}/ \hbar  \right \rbrace
\end{align*}

The law of combination for rotation operators is not analogous to one for translations:

\begin{align*}
U \left[ R \left( \vec{\vartheta} \right) \right] U \left[ R \left( \vec{\varphi} \right) \right]  &\neq \exp \left \lbrace - i \vec{\vartheta} \cdot \vec{J}/ \hbar  \right \rbrace \exp \left \lbrace - i \vec{\varphi} \cdot \vec{J}/ \hbar  \right \rbrace \\
&\neq \exp \left \lbrace - i \left( \vec{\varphi} + \vec{\vartheta} \right) \cdot \vec{J}/ \hbar \right \rbrace \\
&\neq U \left[ R \left( \vec{\varphi} + \vec{\vartheta} \right) \right].
\end{align*}

This is because \(\left[ J_{\vartheta}, J_{\varphi} \right] \neq 0\) and they behave like \(q\) numbers. If \(\vec{\vartheta} || \vec{\varphi}\) however, they behave like \(c\) numbers and \(U \left[ R \left( \vec{\vartheta} \right) \right] U \left[ R \left( \vec{\varphi} \right) \right] = U \left[ R \left( \vec{\vartheta} + \vec{\varphi} \right) \right]\).

/All/ rotation operators \(U \left[ R \left( \vec{\theta} \right) \right]\) are /block diagonal/. This is because \(J_{i}\) is block diagonal, and thus \(\vec{\theta} \cdot \vec{J}\) is block diagonal and its exponential is block diagonal.

The \((2j + 1)\) -dimensional block at a given \(j\) is denoted by \(D^{(j)} \left[ R \right]\). The block diagonal form of the rotation matrices implies that any vector \(\vert \psi_j \rangle\) in the subspace \(\mathbb{V}_{j}\) spanned by the \((2j + 1)\) vectors \(\vert j,j \rangle, \dotso, \vert j,-j \rangle\) goes into another element \(\vert \psi_{j}^{\prime} \rangle\) of \(\mathbb{V}_{j}\): \(\mathbb{V}_{j}\) are /irreducible, invariant subspaces/. This is because \(\left[ J^2, U \left[ R \right] \right] = 0\), so \(U \left[ R \right]\) (a rotation) cannot change the eigenvalue (magnitude of a vector) of \(J^{2}\): /each subspace contains states of a definite magnitude of angular momentum squared/ \(j \left( j + 1 \right) \hbar^{2}\). Thus if \(\vert \psi \rangle\) has components only in \(\mathbb{V}_{0}, \thinspace \mathbb{V}_{1}, \mathbb{V}_{2}, \dotso, \mathbb{V}_{j}\), we need the first \(j+1\) matrices \(D^{(j)}\). The block diagonal matrices representing the rotation operators \(U \left[ R \right]\) are said to provide an irreducible (matrix) representation of these operators.

The series representing \(D^{(j)}\) is:

\begin{align*}
D^{(j)} \left[ R \left( \vec{\theta} \right) \right] = \exp \left \lbrace - i \vec{\theta} \cdot \vec{J^{(j)}} / \hbar  \right \rbrace = \sum_{0}^{\infty} \left( \dfrac{-i \theta}{\hbar} \right)^{n} \left( \hat{\theta} \cdot \vec{J^{(j)}} \right)^{n} \dfrac{1}{n!}.
\end{align*}

\((\hat{\theta} \cdot \vec{J^{(j)}})^{n}\) for \(n > 2j\) can be written as a linear combination of the first \(2j\) powers of \(\hat{\theta} \cdot \vec{J}^{(j)}\) (See =Exercise 12.5.4=). Therefore:

\begin{align*}
D^{(j)} = \sum_{0}^{2j} f_{n} \left( \theta \right) \left( \hat{\theta} \cdot \vec{J}^{(j)} \right)^{n}.
\end{align*}

** \(L_{i}\), \(L^{2}\) eigenkets in coordinate basis: spherical harmonics_
We deal with \(J_{i} \to L_{i}\), \(J^{2} \to L^{2}\). Living at the extremity of the irreducible invariant subspace corresponding to \(l\) is \(\vert ll \rangle\) and it cannot be /raised/ for it will start toppling from the top:

\begin{align*}
L_{\pm} \vert ll \rangle = \vert 0 \rangle.
\end{align*}

We have the following representations for \(L_{\pm} = L_{x} \pm i L_{y}\) in spherical coordinates:

\begin{align*}
L_{\pm} \xrightarrow[]{\text{spherical coordinate basis}} \pm \hbar \exp \left \lbrace \pm i \phi  \right \rbrace \left( \partial_{\theta} \pm i \cot \theta \right) \partial_{\phi} \right),
\end{align*}

and for \(\vert ll \rangle\)

\begin{align*}
\vert ll \rangle \xrightarrow[]{\text{spherical coordinate basis}} \psi_{l}^{l} \left( r, \theta, \phi \right).
\end{align*}

Because \(L_{z} \to -i \hbar \partial_{\phi}\) and \(L_{z} \vert ll \rangle = l \hbar \vert ll \rangle\), we use an ansatz of the form:

\begin{align*}
\psi_{l}^{l} \left( r, \theta, \phi \right) = U_{l}^{l} \left( r, \theta \right) \exp \left \lbrace i l \phi  \right \rbrace.
\end{align*}

Feeding to \(L_{\pm} \vert ll \rangle = \vert 0 \rangle\) and descending to coordinate basis:

\begin{align*}
\hbar \exp \left \lbrace \pm i \phi  \right \rbrace \left( \partial_{\theta} \pm i \cot \theta \right) \partial_{\phi} \right) \left[ U_{l}^{l} \left( r, \theta \right) \exp \left \lbrace i l \phi  \right \rbrace \right] = 0.
\end{align*}

Simplification furnishes:

\begin{align*}
\left( \partial_{\theta} - l \cot \theta \right) U_{l}^{l} = 0,
\end{align*}

and is solved by:

\begin{align*}
U_{l}^{l} \left( r, \theta \right) = R \left( r \right) \left( \sin \theta \right)^{l}
\end{align*}

where \(R \left( r \right)\) is an arbitrary (normalizable) function of \(r\). Shave off that \(R (r)\); we'll pick it later. The solutions to \(L_{\pm} \vert ll \rangle = \vert 0 \rangle\) are:

\begin{align*}
\psi_{l}^{l} \left( r, \theta, \phi \right) = R \left( r \right) Y_{l}^{l} \left( \theta, \phi \right),
\end{align*}

where

\begin{align*}
Y_{l}^{l} \left( \theta, \phi \right) = \left( -1 \right)^{l} \left[ \dfrac{\left( 2l + 1 \right)!}{4 \pi} \right]^{1/2} \dfrac{1}{2^{l} l!} \left( \sin \theta \right)^{l} \exp \left \lbrace i l \phi \right \rbrace.
\end{align*}

We have:

\begin{align*}
\int \left \lvert Y_{l}^{l} \right \rvert^{2} d \Omega \equiv \int_{-1}^{1} \int_{0}^{2 \pi} \left \lvert Y_{l}^{l}  \right \rvert^{2} d \left( \cos \theta \right) d \phi = 1.
\end{align*}

From here on out, we can /lower/ and go wherever we want. To go to \(\vert lm \rangle\):

\begin{align*}
Y_{l}^{m} \left( \theta, \phi \right) = \left( -1 \right)^{l} \left[ \dfrac{(2l + 1)!}{4 \pi} \right]^{1/2} \dfrac{1}{2^{l} l!} &\left[ \dfrac{\left( l + m \right)!}{\left( 2l \right)! \left( l - m \right)!} \right]^{1/2} \\
&\times \exp \left \lbrace i m \phi  \right \rbrace \left( \sin \theta \right)^{-m} \qquad m \geq 0,
\end{align*}

\begin{align*}
Y_{l}^{m} \left( \theta, \phi \right) = \left( -1 \right)^{-m} \left( Y_{l}^{-m} \right)^{\ast} \qquad m \leq 0.
\end{align*}


These functions are called /spherical harmonics/ and satisfy the orthonormality conditions:

\begin{align*}
\int Y_{l}^{m}^{\ast} \left( \theta, \phi \right) Y_{l^{\prime}}^{m^{\prime}} \left( \theta, \phi \right) d \Omega = \delta_{ll^{\prime}} \delta_{m m^{\prime}}.
\end{align*}

The \(Y_{l}^{m}\) functions are mutually orthogonal because they are /nondegenerate/ eigenfunctions of \(L^{2}\) /and/ \(L_{z}\) which are Hermitian on single-valued functions of \(\theta\) and \(\phi\).

Closely related to the spherical harmonics are the /associated Legendre polynomials/ \(P_{l}^{m}\) (with \(0 \leq m \leq l\)) defined by:

\begin{align*}
Y_{l}^{m} \left( \theta, \phi \right) = \left[ \dfrac{\left( 2l + 1 \right) \left( l - m \right)!}{4 \pi \left( l + m \right)!} \right]^{1/2} \left( -1 \right)^{m} \exp \left \lbrace i m \phi \right \rbrace P_{l}^{m} \left( \cos \theta \right).
\end{align*}

If \(m = 0\), \(P_{l}^{0} \left( \cos \theta \right) \equiv P_{l} \left( \cos \theta \right)\) is called the a /Legendre polynomial/.

For large values of \(l\), the functions \(\left \lvert Y_{l}^{m} \right \rvert\) exhibit many classical features: \(\left \lvert Y_{l}^{l}  \right \rvert \propto \left \lvert \sin^{l} \theta \right \rvert\). For large \(l\), \(\left \lvert Y^{\pm l}_{l}  \right \rvert\) it is almost entirely confined to the \(x-y\) plane, as one would expect of a classical particle with all its angular momentum pointing along the \(z\) axis. \(\left \lvert Y_{l}^{0}  \right \rvert\) for large \(l\) is almost entirely confined to the \(z\) axis.

The first few spherical harmonics are:

\begin{align*}
Y_{0}^{0} = \left( 4 \pi \right)^{-1/2},
\end{align*}

\begin{align*}
Y_{1}^{\pm 1} = \mp \left( \dfrac{3}{8 \pi} \right)^{1/2} \sin \theta \exp \left \lbrace \pm i \phi  \right \rbrace,
\end{align*}

\begin{align*}
Y_{1}^{0} = \left( \dfrac{3}{4 \pi} \right)^{1/2} \cos \theta,
\end{align*}

\begin{align*}
Y_{2}^{\pm 2} = \left( \dfrac{15}{32 \pi} \right)^{1/2} \sin^{2} \theta \exp \left \lbrace \pm 2 i \phi  \right \rbrace,
\end{align*}

\begin{align*}
Y_{2}^{\pm 1} = \mp \left( \dfrac{15}{8 \pi} \right)^{1/2} \sin \theta \cos \theta \exp \left \lbrace \pm i \phi  \right \rbrace,
\end{align*}

\begin{align*}
Y_{2}^{0} = \left( \dfrac{5}{16 \pi} \right)^{1/2} \left( 3 \cos^{2} \theta - 1 \right).
\end{align*}

Any arbitrary \(\psi \left( r, \theta, \phi \right)\) may be expanded in terms of the spherical harmonics \(Y_{l}^{m} \left( \theta, \phi \right)\) using \(r\)-/dependent coefficients/:

\begin{align*}
\psi \left( r, \theta, \phi \right) = \sum_{l=0}^{\infty} \sum_{m=-l}^{l} C_{l}^{m} \left( r \right) Y_{l}^{m} \left( \theta, \phi \right),
\end{align*}

where

\begin{align*}
C_{l}^{m} \left( r \right) = \int Y_{l}^{m^{\ast}} \left( \theta, \phi \right) \psi \left( r, \theta, \phi \right) d \Omega.
\end{align*}

Assuming \(\psi\) is normalized to unity:

\begin{align*}
P \left( L^{2} = l \left( l + 1 \right) \hbar^{2}, L_{z} = m \hbar \right) = \int_{0}^{\infty} \left \lvert C_{l}^{m} \left( r \right)  \right \rvert^{2} r^{2} dr.
\end{align*}

\(C_{l}^{m}\) is the amplitude to find the particle at a radial distance \(r\) with angular momentum \((l,m)\).
** Rotational invariance
A Hamiltonian with rotational invariance along \(\hat{\theta}\) satisfies:

\begin{align*}
U^{\dagger} \left[ R_{\hat{\theta}} \right] H \left( X, P_{x}; Y, P_{y} \right) U \left[ R_{\hat{\theta}} \right] &= H \left( X, P_{x}; Y, P_{y} \right) \\
&\Jongrightarrow \left[ J_{\hat{\theta}}, H \right] = 0.
\end{align*}

1) There exists a common basis for \(J_{\hat{\theta}}\) and \(H\) or \(J_{\hat{\theta}}\) and \(H\) are simultaneously diagonalizable.
2) \(\left \langle J_{\hat{\theta}}  \right \rangle\) is a conserved quantity.

A Hamiltonian with rotational invariance under arbitrary rotations satisfies:

\begin{align*}
U^{\dagger} \left[ R \right] H U \left[ R \right] = H \Longrightarrow \left[ J_{i}, H \right] = \left[ J^{2}, H \right] = 0 \text{ for} \thinspace i = x, \thinspace y, \thinspace z.
\end{align*}

1) There exists a common basis for each of the components of \(\vec{J}\) and \(H\) and for \(J^{2}\) and \(H\). In other words, \(J_{x}\) and \(H\) or \(J_{y}\) and \(H\) or \(J_{z}\) and \(H\) or \(J^{2}\) and \(H\) are simultaneously diagnonalizable. Since \(\left[ J^2, J_i \right] = 0\), \(J^{2}\), \(J_{i}\) and \(H\) are simultaneously diagonalizable for a Hamiltonian that is rotationally invariant under arbitrary rotations.
2) \(\left \langle J_{x}  \right \rangle\), \(\left \langle J_{y}  \right \rangle\), \(\left \langle J_{z}  \right \rangle\), and \(\left \langle J^{2}  \right \rangle\) are conserved quantities.

Since \(\left[ \vec{J}, H \right] = 0\), \(H\) has the same form as \(J^{2}\):

1) \(H\) is diagonal (since \(\left[ H, J^2 \right] = 0\), \(\left[ H, J_z \right] = 0\)).
2) Within each block, \(H\) has the same eigenvalue \(E_{j}\) (since \(\left[ H, J_{\pm} \right] = 0\)), i.e., \(\mathbb{V}_{j}\) is an eigenspace of \(H\) with eigenvalue \(E_{j}\): /all states with a given/ \(j\) /are degenerate eigenkets of/ \(H\).

Arbitrary degenerate states are not accessible from a given degenerate state /only/ via rotations: the combined action of \(J_{\pm}\) and \(U \left[ R \right]\) is necessary when the magnetic quantum numbers differ. This is a purely quantum mechanical effect: in classical mechanics /all/ degenerate states from a given state are accessible via smooth rotations, but in quantum mechanics, you can be smooth with \(\vert jm \rangle\), but if you want to /change/ \(m\), you can only do it in fits and jumps using \(J_{\pm}\). \(j\) you cannot change, you're stuck in this subspace, remember? (Don't even begin!)

\(H\) is invariant under arbitrary rotations when \(V \left( r, \theta, \phi \right) = V \left( r \right)\). The time-independent Schrodinger equation is:

\begin{align*}
&-\dfrac{\hbar^2}{2 \mu} \left( r^{-2} \partial_{r} \thinspace r^{2} \thinspace \partial_{r} + r^{-2} \left( \sin \theta \right)^{-1} \partial_{\theta} \thinspace \sin \theta \thinspace \partial_{\theta} + r^{-2} \left( \sin \theta \right)^{-2} \partial_{\phi}^{2} \right) \psi_{E} \left( r, \theta, \phi \right) \\
&+ V(r) \psi_{E} \left( r, \theta, \phi \right) = E \psi_{E} \left( r, \theta, \phi \right).
\end{align*}

We seek the simultaneous eigenfunctions of \(H\), \(L^{2}\), and \(L_{z}\) in the coordinate basis so our ansatz is (picking out the \(R_{l}^{m} (r)\) from the trash; we discarded it while solving for the spherical harmonics remember?):

\begin{align*}
\psi_{Elm} \left( r, \theta, \phi \right) = R_{Elm} \left( r \right) Y_{l}^{m} \left( \theta, \phi \right).
\end{align*}

Feed it. You'll get the /radial equation/:

\begin{align*}
\left \lbrace - \dfrac{\hbar^{2}}{2 \mu} \left[ r^{-2} D_{r} r^{2} D_{r} - \dfrac{l \left( l + 1 \right)}{r^{2}} \right] + V(r) \right \rbrace R_{El} = E R_{El}.
\end{align*}

The /magnetic quantum number/ has dropped out: neither the energy nor the radial functions depends on it. The had concluded earlier that all states with a given \(j\) are degenerate eigenkets of \(H\). We have now verified it. \(H\) has \(2l + 1\) -fold degeneracy. Now recast \(R_{El}\) as \(R_{El} = U_{El}/r\). A necessary condition for

\begin{align*}
\int_{0}^{\infty} \left \lvert R_{El} \right \rvert^{2} r^{2} dr = \int_{0}^{\infty} \left \lvert U_{El}  \right \rvert^{2} dr
\end{align*}

to be normalizable to unity or the Dirac delta function is that

\begin{align*}
U_{El} \xrightarrow[]{r \to \infty} 0 \quad \text{ or } \quad U_{El} \xrightarrow[]{r \to \infty} \exp \left \lbrace i k r  \right \rbrace,
\end{align*}

corresponding to /bound/ and /unbound/ states respectively. With \(R_{El} = U_{El}/r\) the radial equation reduces to:


\begin{align*}
\left \lbrace D_{r}^{2} + \dfrac{2 \mu}{\hbar^{2}} \left[ E - V \left( r \right) - \dfrac{l \left( l + 1 \right) \hbar^{2}}{2 \mu r^{2}} \right]  \right \rbrace U_{El} = 0,
\end{align*}

and has the properties:

1) The independent variable \((r)\) goes from \(0\) to \(\infty\) and not from \(-\infty\) to \(\infty\).
2) In addition to the actual potential \(V (r)\), there is a /repulsive centrifugal barrier/, \(l \left( l + 1 \right) \hbar^{2}/ 2 \mu r^{2}\), in all but the \(l = 0\) states.
3) The boundary condition on \(U\) are different from the one-dimensional case. To see this start with a rewrite:

\begin{align*}
\left[ - \dfrac{\hbar^{2}}{2 \mu} D_{r}^{2} + V(r) + \dfrac{l \left( l + 1 \right) \hbar^{2}}{2 \mu r^{2}} \right] U_{El} \equiv D_{l} \left( r \right) U_{El} = E U_{El},
\end{align*}

and demand that \(U_{El}\) be such that \(D_{l}\) is Hermitian with respect to them. If \(U_{1}\) and \(U_{2}\) are two such functions, demand:

\begin{align*}
\int_{0}^{\infty} U_{1}^{\ast} \left( D_{l} U_{2} \right) dr = \left[ \int_{0}^{\infty} U_{2}^{\ast} \left( D_{l} U_{1} \right) dr \right]^{\ast} \equiv \int_{0}^{\infty} \left( D_{l} U_{1} \right)^{\ast} U_{2} dr.
\end{align*}

This reduces to (see =Exercise 12.6.3=):

\begin{align*}
\left( U_{1}^{\ast} D_{r} U_{2} - U_{2} D_{r} U_{1}^{\ast} \right) \vert_{0}^{\infty} = 0.
\end{align*}

Because \(U_{El} \xrightarrow[]{r \to \infty} 0 \quad \text{ or } \quad U_{El} \xrightarrow[]{r \to \infty} \exp \left \lbrace i k r  \right \rbrace\), Hermiticity of \(D_{l}\) hinges on

\begin{align*}
\left( U_{1}^{\ast} D_{r} U_{2} - U_{2} D_{r} U_{1}^{\ast} \right) \vert_{0}^{\infty} = 0 \to \left[ U_{1}^{\ast}(0) D_{r} U_{2}(0) - U_{2}(0) D_{r} U_{1}^{\ast}(0) \right] = 0.
\end{align*}

\begin{align*}
\left[ U_{1}^{\ast}(0) D_{r} U_{2}(0) - U_{2}(0) D_{r} U_{1}^{\ast}(0) \right] = 0 \Longrightarrow U_{El} \xrightarrow[]{r \to 0} c, \qquad c = \text{constant}.
\end{align*}

If \(c\) is non-zero, then

\begin{align*}
R \sim \dfrac{U}{r} \sim \dfrac{c}{r} \Longrightarrow \psi \sim \dfrac{c}{r} Y_{0}^{0}
\end{align*}

which violates Schrodinger equation at \(r = 0\) because (see =Exercise 12.6.4=):

\begin{align*}
\nabla^{2} \left( 1/r \right) = - 4 \pi \delta^{3} \left( \vec{r} \right).
\end{align*}

Thus unless \(V(r)\) contains a delta function at the origin (which we assume it does not, but will lift when we add a correction to the hydrogen atom) the choice \(c \neq 0\) is untenable. Thus \(c \to 0\), cause ours hands are tied. The Hermiticity condition reduces to:

\begin{align*}
\left[ U_{1}^{\ast}(0) D_{r} U_{2}(0) - U_{2}(0) D_{r} U_{1}^{\ast}(0) \right] = 0 \Longrightarrow U_{El} \xrightarrow[]{r \to 0} 0.
\end{align*}

/Assume/ \(V(r)\) falls slower than \(r^{-2}\).

In the \(r \to 0\) limit, the centrifugal barrier dominates the equation

\begin{align*}
D_{r}^{2} U_{l} \simeq \dfrac{l \left( l + 1 \right)}{r^{2}} U_{l} \qquad l \neq 0.
\end{align*}

\(E\) has been dropped from the subscript because it is inconsequential in this limit. Feeding \(U_{l} \sim r^{\alpha}\)

\begin{align*}
\alpha \left( \alpha - 1 \right) = l \left( l + 1 \right) \Longrightarrow \alpha = l+1 \text{ or } -l.
\end{align*}

Thus

\begin{align*}
U_{l} \sim
\begin{cases}
r^{l+1} \qquad \text{regular} \\
r^{-l} \qquad \text{irregular}
\end{cases}.
\end{align*}

Discard \(U_{l} \sim r^{-l}\) since then \(U(0) \neq 0\). Thus \(U_{l} \sim r^{l+1}\): as the angular momentum increases the particle should avoid the origin more and more.

In the \(r \to \infty\) limit, \(V(r)\) dominates the equation if it does not vanish in this limit, nothing general can be said.

/Assume/ \(r V \left( r \right) \to 0\) as \(r \to \infty\).

In the \(r \to \infty\) limit,

\begin{align*}
D_{r}^{2} U_{E} = - \left( \dfrac{2 \mu E}{\hbar^{2}} \right) U_{E}.
\end{align*}

\(l\) has been dropped from the subscript because it is inconsequential in this limit. There are two cases:

1) \(E > 0\): /scattering states/ - \(U_{E}\) oscillates as \(r \to \infty\).

The solution is:
\begin{align*}
U_{E} = A \exp \left \lbrace i k r  \right \rbrace + B \exp \left \lbrace - i k r  \right \rbrace, \qquad k = \left( \dfrac{2 \mu E}{\hbar^{2}} \right)^{1/2}.
\end{align*}

We assumed \(r V \left( r \right) \to 0\) as \(r \to \infty\) because if \(V (r) \sim r^{-1}\) or \(V (r) \sim r^{-s}, s>1\), there are /no scattering states/. An example is the Coulomb potential of equal and opposite charges \(e\) at a distance \(r\):

\begin{align*}
V(r) = - \dfrac{e^{2}}{r}.
\end{align*}

No matter how far away the particle is from the origin (the influence of the other particle), it is never /completely free/ of the Coulomb potential. If the fall of \(V(r)\) is even more sluggish than the Coulomb potential, /freedom/ is further restricted.
   
2) \(E < 0\): /bound states/ - \(U_{E}\) falls off exponentially as \(r \to \infty\).

With the transformation \(k \to i \kappa\) the solution is:

\begin{align*}
U_{E} \xrightarrow[]{r \to \infty} A \exp \left \lbrace - \kappa r  \right \rbrace + B \exp \left \lbrace + \kappa r \right \rbrace \qquad \kappa = \left( 2 \mu \left \lvert E  \right \rvert / \hbar^{2} \right)^{1/2}.
\end{align*}

\(B/A\) is not arbitrary, \(U_{E} \to 0 \text{ as } r \to 0\) and \(U_{E} \to 0 \text{ as } r \to \infty\) constrains them. For arbitrary \(E < 0\), both \(\exp \left \lbrace kr  \right \rbrace\) and \(\exp \left \lbrace - k r  \right \rbrace\) are present in \(U_{E}\). Only for certain discrete values of \(E\) will the \(\exp \left \lbrace \kappa r  \right \rbrace\) drop out: these are the allowed bound states.

The assumption \(r V \left( r \right) \to 0\) as \(r \to \infty\) is necessary for the solution above, else an \(r\) dependence will creep in on \(U_{E}\).

The energy eigenfunctions are normalizable to unity when \(E < 0\). Since the operator \(D_{l} (r)\) is /non-degenerate/ (see =Exercise 12.6.5=), we have:

\begin{align*}
\int_{0}^{\infty} U_{E^{\prime}l} \left( r \right) U_{El} \left( r \right) dr = \delta_{E E^{\prime}}
\end{align*}

and

\begin{align*}
\psi_{Elm} \left( r, \theta, \phi \right) = R_{El} \left( r \right) Y_{l}^{m} \left( \theta, \phi \right)
\end{align*}

obeys

\begin{align*}
\iiint \psi_{Elm}^{\ast} \left( r, \theta, \phi \right) \psi_{E^{\prime} l^{\prime} m^{\prime}} \left( r, \theta, \phi \right) \thinspace r^{2} \thinspace dr \thinspace d\Omega = \delta_{EE^{\prime}} \delta_{ll^{\prime}} \delta_{mm^{\prime}}.
\end{align*}

* The Hydrogen Atom
CLOSED: [2022-11-10 Thu 17:47]
:LOGBOOK:
CLOCK: [2022-11-09 Wed 12:52]--[2022-11-09 Wed 13:15] =>  0:23
CLOCK: [2022-11-09 Wed 12:39]--[2022-11-09 Wed 12:40] =>  0:01
:END:
:LOGBOOK:
CLOCK: [2022-11-26 Sat 15:49]--[2022-11-26 Sat 18:54] =>  3:05
:END:
** The eigenvalue problem
/Setup/: A two-body problem of an electron of charge \(-e\) and mass \(m\) and a proton of charge \(+e\) and mass \(M\). Using Jacobi coordinates we reduce the problem to the dynamics of a single /reduced mass/ \(\mu\):

\begin{align*}
\mu = \dfrac{m M}{m + M}.
\end{align*}

with coordinate \(\vec{r} = \vec{r}_{e}- \vec{r}_{p}\). To start with /assume/ \(M \to \infty\) so that the electron is moving in the field of the immobile proton. The potential energy of the electron in the Coulomb potential

\begin{align*}
\phi = \dfrac{e}{r},
\end{align*}

due to the proton is

\begin{align*}
V = -\dfrac{e^{2}}{r}.
\end{align*}

The Schrodinger equation is:

\begin{align*}
\left \lbrace D_{r}^{2} + \dfrac{2m}{\hbar^{2}} \left[ E + \dfrac{e^{2}}{r} - \dfrac{l \left( l + 1 \right) \hbar^2}{2 m r^{2}} \right]  \right \rbrace U_{El} = 0.
\end{align*}

The wavefunctions are:

\begin{align*}
\psi_{Elm} \left( r, \theta, \phi \right) = R_{El} \left( r \right) Y_{l}^{m} \left( \theta, \phi \right) = \dfrac{U_{El} (r)}{r} Y_{l}^{m} \left( \theta, \phi \right).
\end{align*}

We are looking for bound states so:

\begin{align*}
U_{El} \sim \exp \left \lbrace - \left( \dfrac{2 m W}{\hbar^{2}} \right)^{1/2} r \right \rbrace \quad \text{as} \quad r \to \infty, \quad \text{where} \quad W = - E.
\end{align*}

\(W\) is the /binding energy/ (which is the energy it would take to liberate the electron) and:

\begin{align*}
U_{El} \sim r^{l+1} \qquad r \to 0.
\end{align*}

With an auxiliary function \(v_{El}\) and 

\begin{align*}
\rho \equiv \left( \dfrac{2 m W}{\hbar^{2}} \right)^{1/2} r
\end{align*}

\begin{align*}
U_{El} = \exp \left \lbrace - \rho  \right \rbrace v_{El}.
\end{align*}

Feeding to the Schrodinger equation:

\begin{align*}
D_{\rho}^{2} v - 2 D_{\rho} v + \left[ \dfrac{e^{2} \lambda}{\rho} - \dfrac{l \left( l + 1 \right)}{\rho^{2}} \right] v = 0 \quad \text{where} \quad \lambda = \left(\dfrac{2 m}{\hbar^{2} W}\right)^{1/2}.
\end{align*}

Feed the ansatz

\begin{align*}
v_{El} = \rho^{l+1} \sum_{k=0}^{\infty} C_{k} \rho^{k}
\end{align*}

to obtain the recurrence:

\begin{align*}
C_{k+1} = \dfrac{-e^{2} \lambda + 2 \left( k + l + 1 \right)}{\left( k + l + 2 \right) \left( k + l + 1 \right)- l \left( l + 1 \right)} C_{k}.
\end{align*}
** The energy levels
We can't let

\begin{align*}
v_{El} = \rho^{l+1} \sum_{k=0}^{\infty} C_{k} \rho^{k}
\end{align*}

unroll forever via

\begin{align*}
C_{k+1} = \dfrac{-e^{2} \lambda + 2 \left( k + l + 1 \right)}{\left( k + l + 2 \right) \left( k + l + 1 \right)- l \left( l + 1 \right)} C_{k}.
\end{align*}

Remember \(\exp \left \lbrace - \rho  \right \rbrace\) can only kill /finite/ positive powers of \(\rho\)? We have to ask it to fold over somewhere; ask for a vanishing numerator:

\begin{align*}
e^{2} \lambda = 2 \left( k + l + 1 \right) \Longrightarrow E = - W = \dfrac{- m e^{4}}{2 \hbar^{2} \left( k + l + 1 \right)^{2}}, \quad k = 0, \thinspace 1, \thinspace 2, \dotso: l = 0, \thinspace 1, \thinspace 2, \dotso.
\end{align*}

Define the /principal quantum number/

\begin{align*}
n \equiv k + l + 1.
\end{align*}

The energy levels are:

\begin{align*}
E_{n} = \dfrac{- m e^{4}}{2 \hbar^{2} n^{2}}, \quad n = 1, \thinspace 2, \thinspace 3, \dotso.
\end{align*}

For each value of \(n\), \(l\) will hop over:

\begin{align*}
l = n - k - 1 = n - 1, \thinspace n - 2, \thinspace \dotso, 1 , 0.
\end{align*}

Isn't that strange? What this means is that the eigenkets of \(H\) in the  \(n-1\) irreducible invariant subspaces \(\mathbb{V}_{l} \quad l = 0, \thinspace 1, \thinspace \dotso, n -1\) in the Hilbert space of total angular momentum vectors are degenerate and have the eigenvalue \(E_{n}\). Note that this is different from the eigenkets of \(H\) being degenerate /within/ such a subspace which is a consequence of rotational invariance (\(\left[ H, \vec{L} \right] = 0\)). \(H\) /must contain more symmetries besides rotational invariance./ The degeneracy at each \(n\) is (a pass over all of these subspaces \(\mathbb{V}_{l}\), each of which hold \(2l + 1\) eigenkets of \(H\)):

\begin{align*}
\sum_{l=0}^{n-1} \left( 2l + 1 \right) = n^{2}.
\end{align*}

A natural unit of energy called a /Rydberg/ \((\text{Ry})\), for measuring the energy levels of hydrogen:

\begin{align*}
\text{Ry} = \dfrac{m e^{4}}{2 \hbar^{2}}.
\end{align*}

The energy levels in this unit are:

\begin{align*}
E_{n} = - \dfrac{\text{Ry}}{n^{2}}.
\end{align*}

** The wavefunctions
Consider a given \(n\) and \(l\). \(v_{l}\) is \(\rho^{l+1}\) times a polynomial of degree \(n-l-1\). This polynomial is called the /associated Laguerre polynomial/, \(L_{n-l-1}^{2l+1} \left( 2 \rho \right)\) which satisfy:

\begin{align*}
L_{p}^{k} \left( x \right) = \left( -1 \right)^{k} D_{x}^{k} L_{p+k}^{0}, \qquad L_{p}^{0} = \exp \left \lbrace x  \right \rbrace D_{x}^{p} \left(\exp \left \lbrace -x  \right \rbrace x^{p} \right).
\end{align*}

The corresponding radial function is:

\begin{align*}
R_{nl} \left( \rho \right) \sim \rho^{l} \exp \left \lbrace - \rho  \right \rbrace L_{n-l-1}^{2l+1} \left( 2 \rho \right).
\end{align*}

Now

\begin{align*}
\rho \equiv r \left( \dfrac{2 m W}{\hbar^{2}} \right)^{1/2} = r \left[ \dfrac{2m}{\hbar^{2}} \cdot \left( \dfrac{me^{4}}{2 \hbar^{2} n^{2}} \right) \right]^{1/2} = \left( \dfrac{me^{2}}{\hbar^{2}} \right) \dfrac{r}{n}.
\end{align*}

Defining the /Bohr radius/

\begin{align*}
a_{0} \equiv \dfrac{\hbar^{2}}{m e^{2}}
\end{align*}

\begin{align*}
R_{nl} \left( r \right) \sim \left( \dfrac{r}{n a_{0}} \right)^{l} \exp \left \lbrace - \dfrac{r}{n a_{0}}  \right \rbrace L_{n-l-1}^{2l+1} \left( \dfrac{2r}{n a_{0}} \right).
\end{align*}

/The Bohr radius provides a natural length scale for the hydrogen atom./ Consider the state described by:

\begin{align*}
\psi_{n, n-1, m} \propto r^{n-1} \exp \left \lbrace - \dfrac{r}{n a_{0}}  \right \rbrace Y_{n-1}^{m} \left( \theta, \phi \right).
\end{align*}

What is the probability of finding the electron in a spherical shell of radius \(r\) and thickness \(dr\)?

\begin{align*}
\int_{\Omega} P \left( \vec{r} \right) r^{2} \thinspace dr \thinspace d \Omega \propto \exp \left \lbrace - \dfrac{2r}{n a_{0}}  \right \rbrace r^{2n} dr
\end{align*}

The mode is found by demanding:

\begin{align*}
D_{r} \left( \exp \left \lbrace - \dfrac{2r}{n a_{0}}  \right \rbrace r^{2n} \right) = 0 \Longrightarrow r_{\text{max}} = n^{2} a_{0}.
\end{align*}

When \(n=1\), \(r_{\text{max}} = a_{0}\). Thus the Bohr radius gives the most probable value of \(r\) in the ground state. For \(l = n -1\), and \(n > 1\) the radial function grows as \(n^{2}\). For \(l \neq n - 1\), the radial function has \(n - l - 1\) zeros and the density in \(r\) has several bumps. In this case, a expectation value \(\left \langle r  \right \rangle_{nlm}\) characterizes the electron's whereabouts. Using the properties of the Laguerre polynomials \(L_{n-l-1}^{2l+1}\)

\begin{align*}
\left \langle r  \right \rangle_{nlm} = \dfrac{a_{0}}{2} \left[ 3 n^{2} - l \left( l + 1 \right) \right].
\end{align*}

Tack on a spherical harmonic to \(R_{nl} \left( r \right)\) and normalize to get a honest to god (approximate, there is a zoo of corrections coming up, hang tight) hydrogen wavefunction. For \(r \to \infty\) \(L\) is dominated by the highest power, \(r^{n-l-1}\) and

\begin{align*}
R_{nl} \sim r^{n-1} \exp \left \lbrace - \dfrac{r}{n a_{0}}  \right \rbrace \qquad \text{as } r \to \infty.
\end{align*}

For the ``maximum angular momentum" state \(l = n-1\) for a given \(n\), the form above is valid for /all/ \(r\) since \(L_{0}^{2l+1}\) is a constant. The first few normalized eigenfunctions \(\psi_{Elm} \equiv \psi_{nlm}\) are:

\begin{align*}
\psi_{1,0,0} = \left( \dfrac{1}{\pi a_{0}^{3}} \right)^{1/2} \exp \left \lbrace - \dfrac{r}{a_{0}}  \right \rbrace,
\end{align*}

\begin{align*}
\psi_{2,0,0} = \left( \dfrac{1}{32 \pi a_{0}^{3}} \right)^{1/2} \left( 2 - \dfrac{r}{a_{0}} \right) \exp \left \lbrace - \dfrac{r}{2 a_{0}}  \right \rbrace,
\end{align*}

\begin{align*}
\psi_{2,1,0} = \left( \dfrac{1}{32 \pi a_{0}^{3}} \right)^{1/2} \dfrac{r}{a_{0}} \exp \left \lbrace - \dfrac{r}{2 a_{0}}  \right \rbrace \cos \theta,
\end{align*}

\begin{align*}
\psi_{2,1,\pm 1} = \mp \left( \dfrac{1}{64 \pi a_{0}^{3}} \right)^{1/2} \dfrac{r}{a_{0}} \exp \left \lbrace - \dfrac{r}{2 a_{0}}  \right \rbrace \sin \theta \exp \left \lbrace \pm i \phi \right \rbrace.
\end{align*}
** Degeneracy of hydrogen spectrum
The Hydrogen atom Hamiltonian has other symmetries besides rotational invariance. The symmetries of \(H\) imply the conservation of the generators of the symmetries. Consequently, if there is an extra symmetry (besides rotational invariance) there must be some extra conserved quantities (besides angular momentum). This quantity is the quantum analogue \(\vec{N}\) of the /Runge-Lenz vector/

\begin{align*}
\vec{n} \equiv \dfrac{\vec{p} \times \vec{l}}{m} - \dfrac{e^{2}}{r} \vec{r}
\end{align*}

which in classical mechanics is a conserved quantity for the motion of a mass in a Coulomb potential. The conservation of \(\vec{n}\) implies that not only is the orbit confined to a plane perpendicular to \(\vec{l}\) (as in any rotationally invariant problem) it is also /closed/. \(\vec{N}\) is

\begin{align*}
\vec{N} \equiv \dfrac{1}{2m} \left[ \vec{P} \times \vec{L} - \vec{L} \times \vec{P} \right] - \dfrac{e^{2} \vec{R}}{\left( X^{2} + Y^{2} + Z^{2} \right)^{1/2}},
\end{align*}

and we have

\begin{align*}
\left[ \vec{N}, H \right] = 0.
\end{align*}

The conservation of \(\vec{L}\) implies that \(\left[ L_{\pm}, H \right] = 0\), which means it is possible to raise and lower the \(m\) values at a given \(l\) without changing the energy. Similarly, the conservation of \(\vec{N}\) implies that \(\left[ N_{\pm}, H \right] = 0\) which means it is possible to raise and lower the \(l\) values at a given \(n\) without changing the energy. We will construct \(N_{\pm}\) later.
** Numerical estimates
\begin{align*}
m c^{2} \text{ (rest energy of electron)} \simeq 0.5 \text{ M eV}
\end{align*}

\begin{align*}
Mc^{2} \text{ (rest energy of proton)} \simeq 1000 \text{ M eV}
\end{align*}

\begin{align*}
\dfrac{m}{M} \text{ (ratio of electron mass to proton mass)} \simeq \dfrac{1}{2000}
\end{align*}

\begin{align*}
\hbar \text{ (Planck's constant)} = 1.054 \times 10^{-27} \text{erg sec}
\end{align*}

\begin{align*}
\hbar c \text{ (totally dope thing to remember)} \simeq 2000 \text{ eV \textup{\AA}}
\end{align*}

\begin{align*}
\alpha \thinspace \text{(fine structure constant)} = \dfrac{e^{2}}{\hbar c} \simeq \dfrac{1}{137}
\end{align*}

\begin{align*}
a_{0} \text{ (Bohr radius)} \simeq \dfrac{\hbar^{2}}{m e^{2}} = \dfrac{\hbar c}{m c^{2}} \left( \dfrac{\hbar c}{e^{2}} \right) = \dfrac{\left( 2000 \right) \left( 137 \right)}{0.5 \times 10^{6}} \textup{\AA} \simeq 0.55 \textup{\AA}
\end{align*}

\begin{align*}
\text{Ry} \text{ (Unit of Energy)} &= \dfrac{me^{4}}{2 \hbar^{2}} = \dfrac{m c^{2}}{2} \left( \dfrac{e^{2}}{\hbar c} \right)^{2} \\
&= \dfrac{0.25 \times 10^{6}}{(137)^{2}} \text{ eV} \simeq 13.3 \text{ eV}.
\end{align*}

\begin{align*}
E_{n} \text{ (Energy)} = -\dfrac{me^4}{2 \hbar^{2}} \dfrac{1}{n^{2}} = -\dfrac{e^{2}}{2 a_{0}} \left( \dfrac{1}{n^{2}} \right) = \dfrac{-13.6}{n^{2}} \text{ eV}.
\end{align*}

The /Compton wavelength/ is the lower limit on how well a particle can be localized. In non-relativistic quantum mechanics this limit is \(0\). But in reality, as we try to localize the particle better and better, we use more and more energetic probes, say photons to be specific. To locate it to some \(\Delta X\), we need a photon of momentum

\begin{align*}
\Delta P \sim \dfrac{\hbar}{\Delta X}.
\end{align*}

Since the photon in massless, the corresponding energy is

\begin{align*}
\Delta E \sim \dfrac{\hbar c}{\Delta X},
\end{align*}

where we have used \(E^{2} = c^{2} p^{2} + m^{2} c^{4}\). We don't want this energy to exceed twice the rest energy of the particle because in that regime, relativity allows the production of a particle-antiparticle pair in the measurement process. So we demand:

\begin{align*}
\Delta E \lesssim 2 m c^{2} \Longrightarrow \dfrac{\hbar c}{\Delta X} \lesssim 2 m c^{2} \Longrightarrow \Delta X \gtrsim \dfrac{\hbar}{2 m c} \sim \dfrac{\hbar}{m c}.
\end{align*}

\begin{align*}
\lambda_{e} \text{ (Compton wavelength of electron)} &\equiv \dfrac{\hbar}{mc} = \dfrac{\hbar^{2}}{me^{2}} \centerdot \dfrac{e^{2}}{\hbar c} = a_{0} \alpha \\
&\simeq 0.5 \times \dfrac{1}{137} \textup{\AA} \simeq 4 \times 10^{-3} \textup{\AA}
\end{align*}

If we imagine the electron to be a spherical charge distribution, the Coulomb energy of the distribution (the energy it takes to assemble it) will be of the order \(e^{2}/r_{e}\), where \(r_{e}\) is the radius of the sphere. If we attribute the rest energy of the electron to this Coulomb energy, we arrive at the classical radius.

\begin{align*}
r_{e} \text{ (classical radius of the electron)} = \alpha \lambda_{e} = \dfrac{\hbar}{mc} \centerdot \dfrac{e^{2}}{\hbar c} = \dfrac{e^{2}}{m c^{2}} \simeq 3 \times 10^{-5} \textup{\AA}.
\end{align*}

#+begin_quote
*``In principle, one can measure the energy by simply weighing the atom."* - Ramamurthy Shankar.
#+end_quote

In practice, we measure /differences in energy/:
** Predictions
The /emission spectrum/ will have frequency \(\omega_{n n^{\prime}}\) corresponding to a transition between energy levels \(n\) and \(n^{\prime}\):

\begin{align*}
\omega_{n n^{\prime}} = \dfrac{E_{n} - E_{n^{\prime}}}{\hbar} = \dfrac{\text{Ry}}{\hbar} \left( \dfrac{1}{n^{\prime}^{2}} - \dfrac{1}{n^{2}} \right).
\end{align*}

For a fixed value of \(n^{\prime} = 1, \thinspace 2, \thinspace 3, \dotso\), we obtain a family of lines as we vary \(n\). The \(n^{\prime} = 1\) family is called the /Lyman series/, the \(n^{\prime} = 2\) family is called the /Balmer series/, the \(n^{\prime} = 3\) family is called the /Paschen series/, etc.

On applying an external perturbation \(H^{1}\) for a short time \(\epsilon\), the system goes from \(\vert nlm \rangle\) to

\begin{align*}
\vert \psi \left( \epsilon \right) \rangle &= \left[ I - \dfrac{i \epsilon}{\hbar} \left( H^{0} + H^{1} \right) \right] \vert nlm \rangle \\
&= \vert nlm \rangle - \left( \dfrac{i \epsilon E_{n}}{\hbar} + \dfrac{i \epsilon H^{1}}{\hbar} \right) \vert nlm \rangle.
\end{align*}

The probability of it being in a state \(\vert n^{\prime} l^{\prime} m^{\prime} \rangle\) (assuming \(\vert n^{\prime} l^{\prime} m^{\prime} \rangle\) is different from \(\vert n l m \rangle\)) is:

\begin{align*}
\left \lvert \left \langle n^{\prime} l^{\prime} m^{\prime} \vert \psi \left( \epsilon \right)  \right \rangle  \right \rvert^{2} = \left \lvert - \dfrac{i \epsilon}{\hbar} \left \langle n^{\prime} l^{\prime} m^{\prime} \left \lvert H^{1}  \right \rvert nlm \right \rangle  \right \rvert^{2}.
\end{align*}

Thus the transition rate between states \(\vert nlm \rangle\) and \(\vert n^{\prime} l^{\prime} m^{\prime} \rangle\) is controlled by the matrix element \(\left \langle n^{\prime} l^{\prime} m^{\prime} \left \lvert H^{1}  \right \rvert nlm \right \rangle\), which is calculable by the prescriptions of quantum theory and act as testable predictions.

Our treatment of the Hydrogen atom is to the most part impressively accurate. There are however corrections:

1) the proton is /not/ immobile, this is a two-body problem. Simply replace \(m\) with \(\mu = mM/(m+M)\), the reduced mass.
2) the kinetic energy of the electron is not \(m v^{2}/2 = p^{2}/2m\) in Einstein's theory, but instead \(mc^{2} \left[ \left( 1 - \frac{v^{2}}{c^{2}} \right)^{-1/2} - 1 \right]\). This is a correction of order \(\alpha^{2}\).
3) there are other corrections of the order \(\alpha^{2}\) that go by the name of /fine-structure corrections/.
4) there are relativistic corrections to all orders in \(\alpha\) which the Dirac equation takes into account.
5) there are tiny corrections due to quantum fluctuations of the electromagnetic field which are taken into account by the theory of Quantum Eletrodynamics.

After all of these are taken into account, the match between theory and experiment is spectacular.
* Spin
CLOSED: [2022-11-13 Sun 04:25]
:LOGBOOK:
CLOCK: [2022-11-10 Thu 19:58]--[2022-11-10 Thu 20:22] =>  0:24
:END:
:LOGBOOK:
CLOCK: [2022-11-27 Sun 17:20]--[2022-11-27 Sun 21:48] =>  4:28
:END:
** Spinor
There is a class of quantum phenomena that involve a quantum degree of freedom called /spin/ that has no classical counterpart. The best way to characterize spin is as a /form of angular momentum not associated with orbital motion/. It so because observations indicate that measuring the angular momentum of an electron that has no linear momentum gives a value \(\pm \hbar/2\). The spin of an electron (or anything else that has spin) is it's /intrinsic/ property, like mass, charge, etc. A direct consequence of this observation is that the wavefunction for an electron is not a scalar but in fact a vector. Consider a /vector valued wavefunction/ with \(n\) components. Under an infinitesimal rotation about the \(z\) direction /two/ things happen:

1) the values at each spatial point are re-assigned to the rotated point,
2) the components of the wavefunction get transformed into linear combinations of each other.

\(\vec{L}\) does the first, \(\vec{S}\) does the second and the whole thing is done by \(\vec{J} = \vec{L} + \vec{S}\): it is the generator of infinitesimal rotations for a vector-valued wavefunction. Therefore

\begin{align*}
\vert \psi^{\prime} \rangle = \left[ I - \dfrac{i \epsilon}{\hbar} J_{z} \right] \vert \psi \rangle.
\end{align*}

What is \(n\) and what is \(\vec{S}\)? Since \(J_{i}\) are generator of rotations, they must obey the consistency condition

\begin{align*}
\left[ J_{i}, J_{j} \right] = i \hbar \epsilon_{ijk} J_{k} \quad \text{or} \quad \left[ L_{i}, L_{j} \right] + \left[ S_{i}, S_{j} \right] = i \hbar \left[ \epsilon_{ijk} L_{k} + \epsilon_{ijk} S_{k} \right].
\end{align*}


But \(\left[ L_i, L_j \right] = i \hbar \epsilon_{ijk} L_{k}\) so \(\left[ S_{i}, S_{j} \right] = i \hbar \epsilon_{ijk} S_{k}\).

For an electron lacking linear momentum \(\vec{J} = \vec{S}\). Using the empirical fact that a measurement of \(J_{z} = S_{z}\) gives \(\pm \hbar/2\), we can assert that \(n = 2\) for an electron so that it is a two-component wavefunction - a /spinor/:

\begin{align*}
\vert \psi \rangle =
\begin{bmatrix}
\psi_{+} \left( x, y, z \right) \\
\psi_{-} \left( x, y, z \right)
\end{bmatrix}
\equiv
\psi_{+}
\begin{bmatrix}
1 \\
0 
\end{bmatrix}
+
\psi_{-}
\begin{bmatrix}
0 \\
1 
\end{bmatrix}.
\end{align*}

** Hilbert space for spin
The Hilbert space \(\mathbb{V}_{e}\) of the electron may be viewed as a direct product of an infinite-dimensional space \(\mathbb{V}_{0}\) which describes a particle with just orbital degrees of freedom, and a two-dimensional space \(\mathbb{V}_{s}\), which describes a particle with just spin degrees of freedom:

\begin{align*}
\mathbb{V}_{e} = \mathbb{V}_{0} \otimes \mathbb{V}_{s}.
\end{align*}

If the orbital and spin degrees of freedom evolve independently, meaning the Hamiltonian factorizes as:

\begin{align*}
H = H_{0} + H_{s}
\end{align*}

the state vector factorizes as:

\begin{align*}
\vert \psi \left( t \right) \rangle = \vert \psi_{0} \left( t \right) \rangle \otimes \vert \chi_{s} \left( t \right) \rangle.
\end{align*}

\(\vert \psi_{0} \left( t \right) \rangle\) lives in \(\mathbb{V}_{0}\) and \(\vert \chi_{s} \left( t \right) \rangle\) lives in \(\mathbb{V}_{s}\).
** Vectors in spin Hilbert space
The kets \(\vert s, s_z \rangle = \vert s, m \hbar \rangle \equiv \vert s, m \rangle\) form a complete basis that spans \(\mathbb{V}_{s}\).

\begin{align*}
\vert s, m \rangle = \vert 1/2, 1/2 \rangle \xrightarrow[]{S_{z} \text{basis}}
\begin{bmatrix}
1 \\
0 
\end{bmatrix}
\end{align*}

\begin{align*}
\vert s, m \rangle = \vert 1/2, -1/2 \rangle \xrightarrow[]{S_{z} \text{basis}}
\begin{bmatrix}
0 \\
1 
\end{bmatrix}
\end{align*}

A representation for \(\vert \chi \rangle\) in \(\mathbb{V}_{s}\) is:

\begin{align*}
\vert \chi \rangle = \alpha \vert 1/2, 1/2 \rangle + \beta \vert 1/2, -1/2 \rangle \xrightarrow[]{S_{z} \text{basis}}
\begin{bmatrix}
\alpha \\
\beta 
\end{bmatrix},
\end{align*}

with the normalization

\begin{align*}
1 = \left \langle \chi \vert \chi \right \rangle \xrightarrow[]{S_{z} \text{basis}} 1 = \left \lvert \alpha  \right \rvert^{2} + \left \lvert \beta  \right \rvert^{2}.
\end{align*}

The expectation value of \(\vec{S}\) in the eigenstates \(\vert \hat{n}, \pm \rangle\) of \(\hat{n} \cdot \vec{S}\) is:

\begin{align*}
\left \langle \vec{S} \right \rangle = \left \langle \hat{n}, \pm \left \lvert \vec{S} \right \rvert \hat{n}, \pm \right \rangle = \pm \left( \hbar/2 \right) \hat{n}.
\end{align*}

The kets \(\vert \hat{n}, + \rangle\), \(\vert \hat{n}, - \rangle\) are said to be states with spin up/down along the direction \(\hat{n}\). In the \(S_{z}\) basis \(\vert \hat{n}, + \rangle\), \(\vert \hat{n}, - \rangle\) have representations:

\begin{align*}
\vert \hat{n}, + \rangle \xrightarrow[]{S_{z} \text{basis}}
\begin{bmatrix}
\cos \left( \theta/2 \right) \exp \left \lbrace - i \phi/2  \right \rbrace \\
\sin \left( \theta/2 \right) \exp \left \lbrace i \phi/2 \right \rbrace
\end{bmatrix},
\end{align*}

\begin{align*}
\vert \hat{n}, - \rangle \xrightarrow[]{S_{z} \text{basis}}
\begin{bmatrix}
-\sin \left( \theta/2 \right) \exp \left \lbrace -i \phi/2  \right \rbrace \\
\cos \left( \theta/2 \right) \exp \left \lbrace i \phi/2  \right \rbrace
\end{bmatrix}.
\end{align*}
** Spin operators in spin Hilbert space: Pauli matrices
A representation of \(\vec{S}\) for an electron in the \(\vert sm \rangle\) basis is

\begin{align*}
S_{x} = \dfrac{\hbar}{2}
\begin{pmatrix}
0 & 1 \\
1 & 0
\end{pmatrix}
\quad
S_{y} = \dfrac{\hbar}{2}
\begin{pmatrix}
0 & -i \\
i & 0
\end{pmatrix}
\quad
S_{z} = \dfrac{\hbar}{2}
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}.
\end{align*}

These were just read off from the representations of matrices for \(\vec{J}\) in the \(\vert jm \rangle\) which are available. We introduce the /Pauli matrices/ \(\vec{\sigma}\): 

\begin{align*}
\sigma_{x} =
\begin{pmatrix}
0 & 1 \\
1 & 0
\end{pmatrix}
\quad
\sigma_{y} =
\begin{pmatrix}
0 & -i \\
i & 0
\end{pmatrix}
\quad
\sigma_{z} =
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}.
\end{align*}

so that the spin operators in \(\mathbb{V}_{s}\) become:

\begin{align*}
\vec{S} = \dfrac{\hbar}{2} \vec{\sigma}.
\end{align*}
** Rotation operators in spin Hilbert space
The rotation operator in \(\mathbb{V}_{s}\) in the \(S_{z}\) basis is:

\begin{align*}
U \left[ R \left( \vec{\theta} \right) \right] = \cos \left( \theta/2 \right) I - i \sin \left( \theta/2 \right) \hat{\theta} \cdot \vec{\sigma}.
\end{align*}

This result is a direct consequence of the property \((\hat{n} \cdot \vec{\sigma})^{2}\) of the Pauli matrices. It rotates a state vector in \(\mathbb{V}_{s}\) by an angle \(\theta\) about the direction \(\hat{\theta}\). Suppose we want to rotate the ket \(\vert 1/2, 1/2 \rangle\) so that it ends up at \(\vert \hat{n}, + \rangle\). \(\hat{n} = \left( \sin \theta \cos \phi, \sin \theta \sin \phi, \cos \theta \right)\) so we need:

\begin{align*}
\hat{\theta} = \dfrac{1}{\sin \theta} \left( - \sin \theta \sin \phi, \sin \theta \cos \phi, 0 \right) = \left( - \sin \phi, \cos \phi, 0 \right).
\end{align*}

The rotation matrix then is:

\begin{align*}
D \left[ R \left( \vec{\theta} \right) \right] =
\begin{pmatrix}
\cos \left( \theta/2 \right) & - \sin \left( \theta/2 \right) \exp \left \lbrace - i \phi  \right \rbrace \\
\sin \left( \theta/2 \right) \exp \left \lbrace i \phi \right \rbrace & \cos \left( \theta/2 \right)
\end{pmatrix}.
\end{align*}

Armed with this, arbitrary rotations in \(\mathbb{V}_{s}\) are accessible now.
** Orbital magnetic moment
The magnitude of the /magnetic moment/ \(\vec{\mu}\) for a particle of mass \(m\), charge \(q\), cruising in a circular orbit of radius \(r\) with velocity \(v\) is:

\begin{align*}
\mu = \dfrac{qv}{2 \pi r} \dfrac{\pi r^{2}}{c} = \dfrac{qvr}{2c} = \left( \dfrac{q}{2mc} \right) m v r = \dfrac{ql}{2mc}.
\end{align*}

where \(l\) is the magnitude of the angular momentum. This has been derived by analogy with the formula for the magnetic moment of a current carrying loop:

\begin{align*}
\qquad \vec{\mu} = \dfrac{I \cdot A}{c} \vec{e_{\bot}}.
\end{align*}

Here \(A\) is the area of the loop, \(c\) is the velocity of light, and \(\vec{e_{\bot}}\) is the unit vector perpendicular to the plane of the loop. Since \(\vec{\mu}\) and \(\vec{l}\) are parallel

\begin{align*}
\vec{\mu} = \left( \dfrac{q}{2 m c} \right) \vec{l}.
\end{align*}

The ratio of \(\mu\) to \(l\) is called the /gyromagnetic ratio/ \(\gamma\). In this case:

\begin{align*}
\gamma = \dfrac{q}{2 m c}.
\end{align*}

Why is it cruising anyway? Because there is a magnetic field \(\vec{B}\). At one time it was the case that \(\vec{\mu} || \vec{B}\). Then came along some pervert and nudged it. Now it /precesses/, cause it can't help it. The equation of motion is

\begin{align*}
\vec{T} = D_{t} \vec{l} = \vec{\mu} \times \vec{B} = \gamma \left( \vec{l} \times \vec{B} \right).
\end{align*}

In a small time \(\Delta t\),

\begin{align*}
\Delta \vec{l} = \gamma \left( \vec{l} \times \vec{B} \right) \Delta t \quad \text{or} \quad \Delta l = \gamma l B \sin \theta \Delta t.
\end{align*}

Since \(\Delta \vec{l}\) is perpendicular to \(\vec{l}\), the tip of \(\vec{l}\) vector moves by an angle

\begin{align*}
\Delta \phi = \left( \dfrac{-\Delta l}{l \sin \theta} \right) = \left( - \gamma B \right) \Delta t,
\end{align*}

i.e., precesses at a frequency:

\begin{align*}
\vec{\omega_{0}} = -\gamma \vec{B}.
\end{align*}

The interaction energy  is:

\begin{align*}
H_{\text{int}} \int T \left( \theta \right) d \theta = \int \mu B \sin \theta \thinspace d \theta = - \mu B \cos \theta = - \vec{\mu} \cdot \vec{B}
\end{align*}

The quantum mechanical Hamiltonian for a particle of mass \(m\) and charge \(q\) in a magnetic field is

\begin{align*}
H = \dfrac{(\vec{P} - q \vec{A}/c)^{2}}{2m} = \dfrac{\left \lvert \vec{P} \right \rvert^{2}}{2m} - \dfrac{q}{2mc} \left( \vec{P} \cdot \vec{A} + \vec{A} \cdot \vec{P} \right) + \dfrac{q^{2} \left \lvert \vec{A}  \right \rvert^2}{2mc^{2}}.
\end{align*}

If \(\vec{A} = \dfrac{B}{2} \left( -y \vec{i} + x \vec{j} \right)\) so that \(\nabla \times \vec{A} = \vec{B} = B \vec{k}\) is constant and along the \(z\) axis. We will drop the last term proportional to \(B^{2}\) by /assuming/ \(B\) is small. Now since \(\nabla \cdot \vec{A} = 0\)

\begin{align*}
\left( \vec{P} \cdot \vec{A} \right) \vert \psi \rangle &\to - i \hbar \nabla \cdot \left( A \psi \right) \\
&= i \hbar \left[ \left( \nabla \cdot \vec{A} \right) \psi + \vec{A} \cdot \nabla \psi \right] \\
&= \left( - i \hbar \vec{A} \cdot \nabla \right) \psi \to \left( \vec{A} \cdot \vec{P} \right) \vert \psi \rangle,
\end{align*}

so that the interaction Hamiltonian becomes:

\begin{align*}
H_{\text{int}} &= - \dfrac{q}{2mc} \left( 2 \vec{A} \cdot \vec{P} \right) \\
&= - \dfrac{q}{mc} \dfrac{B}{2} \left( - Y P_{x} + X P_{y} \right) \\
&= - \dfrac{q}{2mc} \vec{L} \cdot \vec{B} \equiv - \vec{\mu} \cdot \vec{B}.
\end{align*}

The interaction energy is the same as in the classical case. This allows us to make the correspondence:

\begin{align*}
\vec{\mu} = \dfrac{q}{2 m c} \vec{L}.
\end{align*}

\begin{align*}
\vec{\mu} = \dfrac{q}{2 m c} \vec{L} \xrightarrow[]{L_{z} \text{basis}} \dfrac{q}{2mc} L_{z} = \dfrac{q \hbar}{2 m c} \left( 0, \thinspace \pm 1, \pm 2, \dotso \right)
\end{align*}

The quantity \(q \hbar/ 2 m c\) is called the /Bohr magneton/ of the particle. The /electron Bohr magneton/, simply called the /Bohr magneton/, has a magnitude:

\begin{align*}
\dfrac{e \hbar}{2 m c} \simeq 0.6 \times 10^{-8} \text{ eV/G},
\end{align*}

where \(m\) is the mass of the electron and \(G\) stands for gauss. The /nucleon Bohr magneton/ is about 2000 times smaller:

\begin{align*}
\dfrac{e \hbar}{2 M c} \simeq 0.3 \times 10^{-11} \text{ eV/G},
\end{align*}

where \(M\) is the nucleon (proton or neutron) mass. By use of Ehrenfest theorem it is easily seen that \(\left \langle \vec{L}  \right \rangle\) precesses around the constant field \(\vec{B}\) just as \(\vec{l}\) would.
** Spin magnetic moment
We /assume/ that there is a /magnetic moment operator/ \(\vec{\mu}\) associated with the spin angular momentum. It is a operator of the spin Hilbert space:

\begin{align*}
\vec{\mu} = \gamma \vec{S}
\end{align*}

where \(\gamma\) is a constant. Since \(\gamma = e/2mc\) for the orbital case, we /assume/:

\begin{align*}
\vec{\mu} = g \left( \dfrac{e}{2mc} \right) \vec{S}
\end{align*}

where \(g\) is a constant. We also /assume/ that:

\begin{align*}
H_{\text{int}} &= - \vec{\mu} \cdot \vec{B} = \dfrac{ge}{2mc} \vec{S} \cdot \vec{B} \\
&= \left(\dfrac{g e \hbar}{4 m c}\right) \vec{\sigma} \cdot \vec{B}.
\end{align*}

Since \(e \hbar / 2 mc\) is the Bohr magneton, the inrinsic magnetic moment due to spin is \(g/2\) magnetons. We will /assume/ \(g=2\). Then

\begin{align*}
H_{\text{int}} = \left( \dfrac{e \hbar}{2 m c} \right) \vec{\sigma} \cdot \vec{B} = -\gamma \vec{S} \cdot \vec{B}, \qquad \gamma = \dfrac{-e}{mc}.
\end{align*}
** The propagator in spin Hilbert space
We have

\begin{align*}
\vert \psi \left( t \right) \rangle = U \left( t \right) \vert \psi \left( 0 \right) \rangle
\end{align*}

where

\begin{align*}
U \left( t \right) &= \exp \left \lbrace - i H t/ \hbar \right \rbrace \\
&= \exp \left \lbrace + i \gamma t \left( \vec{S} \cdot \vec{B} \right)/ \hbar \right \rbrace
\end{align*}

Comparison with \(\exp \left \lbrace - i \vec{\theta} \cdot \vec{S}/ \hbar \right \rbrace\), which is the operator that rotates by \(\vec{\theta}\), the /effect of/ \(U \left( t \right)\) /is clearly to rotate the state by an angle/:

\begin{align*}
\vec{\theta} \left( t \right) = - \gamma \vec{B} t.
\end{align*}

Thus \(\left \langle \vec{S}  \right \rangle\) will precess around \(\vec{B}\) at a frequency \(\vec{\omega}_{0} = - \gamma \vec{B}\). Naturally, if there is no magnetic field, the spin stands still.
** Paramagnetic resonance
Say we had a magnetic field:

\begin{align*}
\vec{B} = B \cos \left(\omega t\right) \vec{i} - B \sin \left(\omega t \right) \vec{j} + B_{0} \vec{k} \qquad \left( B \lll B_{0} \right).
\end{align*}

and at \(t = 0\),

\begin{align*}
\vec{\mu} \left( 0 \right) = \mu \vec{k}.
\end{align*}

We escape the lab frame of reference and mount one that's spinning with frequency \(\vec{\omega} = \omega \vec{k}\). In this rotating frame, the rotating component of \(\vec{B}\) gets frozen along the \(x\) axis and the precession frequency about \(\vec{k}\) will be

\begin{align*}
\omega_{r} = - \gamma B_{0} \vec{k} - \vec{\omega} = - \gamma \left( \vec{B}_{0} + \vec{\omega}/ \gamma \right)
\end{align*}

so that the effective, time-independent field is:

\begin{align*}
\vec{B}_{r} = B \vec{i}_{r} + \left( B_{0} - \omega/ \gamma \right) \vec{k}_{r}
\end{align*}

where \(\vec{i}_{r}\) is the unit vector in the \(x\) direction in the rotating frame and \(\vec{k}_{r} = \vec{k}\) of course. In this frame, \(\vec{\mu}\) will precess around \(\vec{B}_{r}\) at a frequency

\begin{align*}
\vec{\omega}_{r} = - \gamma \vec{B}_{r},
\end{align*}

where

\begin{align*}
\left \lvert \vec{\omega}_{r} \right \rvert = \omega_{r} = \gamma \left[ B^{2} + \left( B_{0} - \omega/ \gamma \right)^{2} \right]^{1/2}.
\end{align*}

We have

\begin{align*}
\mu_{z} \left( t \right) &= \mu \cos^{2} \alpha + \mu \sin^{2} \alpha \cos \omega_{r} t \\
&= \mu_{z} \left( 0 \right) \left[ \dfrac{\left( \omega_{0} - \omega \right)^{2}}{\left( \omega_{0} - \omega \right)^{2} + \gamma^{2} B^{2}} + \dfrac{\gamma^{2} B^{2} \cos \omega_{r} t}{\left( \omega_{0} - \omega \right)^{2} + \gamma^{2} B^{2}} \right].
\end{align*}

This formula is applicable in lab frame too since \(\mu_{z}(t)\) is invariant under rotations about \(z\).

At /paramagnetic resonance/ \(\omega = \omega_{0}\), \(\vec{B}_{r} = B \vec{i}_{r}\), \(\alpha = \pi/2\), and \(\mu_{z}\) oscillates with the largest amplitude \(\mu\) at a frequency \(\gamma B\). The behavriour for \(\omega > \omega_{0}\) is obvious.

A \(90^{\circ}\) /pulse/ is when we apply the rotating field at the resonance  frequency for a time \(\tau\) such that \(\gamma B \tau = \pi/2\). It will swing the magnetic moment into the \(x-y\) plane (in either frame). Thereafter \(\vec{\mu}\) will precess around \(B_{0} \vec{k}\) at the frequency \(\omega_{0}\) in the lab frame. A \(180^{\circ}\) pulse, i.e., \(\tau = \pi/ \gamma B\), the pulse will reverse the sign of \(\vec{\mu}\) and leave it pointing down the \(z\) axis, where it will stay (in either frame).

These results for the classical moment \(\vec{\mu}\) apply to the expectation value \(\left \langle \vec{\mu}  \right \rangle\) in the quantum problem.
** Spin and orbital degrees of freedom combined
Suppose we have a separable \(H\):

\begin{align*}
H = H_{o} + H_{s}
\end{align*}

The time evolution of the spin and orbital degrees of freedom decouple so that the energy eigenstates factorizes:

\begin{align*}
\vert \psi \rangle = \vert \psi_{0} \rangle \otimes \vert \chi_{s} \rangle.
\end{align*}

If \(H\) is /not/ separable however, say when

\begin{align*}
H = H_{\text{Coulomb}} + a \vec{L} \cdot \vec{S}
\end{align*}

the spin and orbital degrees of freedom are coupled in their time evolution. The eigenstates of \(H\) will not be simply products of orbital and spin parts, but instead superpositions of such states that diagonalize \(\vec{L} \cdot \vec{S}\).
** Zeeman effect
The Hamiltonian of the Hydrogen atom is separable, where the Coulomb interaction is independent of spin:

\begin{align*}
H = H_{o}.
\end{align*}

Here the spin is a constant in time, and there is doubling of eigenkets:

\begin{align*}
\vert nlmm_{s} = 1/2 \rangle \xrightarrow[]{RS_{z} \text{basis}}
\psi_{nlm} \left( r, \theta, \phi \right)
\begin{bmatrix}
1 \\
0 
\end{bmatrix}
\end{align*}

\begin{align*}
\vert nlmm_{s} = -1/2 \rangle \xrightarrow[]{RS_{z} \text{basis}} \psi_{nlm} \left( r, \theta, \phi \right)
\begin{bmatrix}
0 \\
1 
\end{bmatrix}.
\end{align*}

Now suppose we turn on a weak magnetic field \(\vec{B} = B \vec{k}\). Both the proton and the electron couple to \(\vec{B}\) but as a first approximation we ignore the coupling of the proton's intrinsic and orbital magnetic moments (of order \(m/M\) and \((m/M)^{2}\) relative to the electron). The Hamiltonian now is:

\begin{align*}
H = H_{\text{Coulomb}} - \left( \dfrac{-e B}{2 m c} \right) L_{z} - \left( \dfrac{-eB}{mc} \right) S_{z}.
\end{align*}

The rotational invariance of the Hamiltonian stays intact: the eigenkets \(\vert nlmm_s \rangle\) /still/ diagnonalize new \(H\). Degeneracies are broken however via changing eigenvalues:

\begin{align*}
H \vert nlmm_{s} \rangle = \left[ \dfrac{- \text{Ry}}{n^{2}} + \dfrac{e B \hbar}{2 m c} \left( m + 2 m_{s} \right) \right] \vert nlmm_{s} \rangle.
\end{align*}

The \(2\) -fold degeneracy of the ground state is broken to yield two different energy levels:

\begin{align*}
E_{n=1} = - \text{Ry} \pm \dfrac{e \hbar B}{2 m c}.
\end{align*}

The \(8\) -fold degeneracy of the first excited state splits into five level:

\begin{align*}
E_{n=2} = - \dfrac{\text{Ry}}{4} + \dfrac{e B \hbar}{2 m c} \times
\begin{bmatrix}
2 \left( m=1, m_{s} = 1/2 \right) \\
1 \left( m = 0, m_{s} = 1/2 \right) \left( l = 0 \text{ or } 1 \right) \\
0 \left( m = 1, m_{s} = -1/2, \text{ or } m=-1, m_{s} = 1/2 \right) \\
-1 \left( m=0, m_{s} = -1/2 \right) \left( l = 0 \text{ or } 1 \right) \\
-2 \left( m = -1, m_{s} = - 1/2 \right)
\end{bmatrix}.
\end{align*}

The is called /Zeeman splitting/ or the /Zeeman effect/.
** Stern-Gerlach (SG) experiment
* Addition of Angular Momenta
:LOGBOOK:
CLOCK: [2022-11-13 Sun 17:04]--[2022-11-13 Sun 17:10] =>  0:06
:END:
:LOGBOOK:
CLOCK: [2022-11-30 Wed 14:11]--[2022-11-30 Wed 17:11] =>  3:00
CLOCK: [2022-11-28 Mon 21:23]--[2022-11-29 Tue 12:04] => 14:41
:END:
** The general problem
Consider two angular momenta \(\vec{J_{1}}\) and \(\vec{J_{2}}\). What are the eigenvalues and eigenkets of \(J^{2}\) and \(J_{z}\), where \(\vec{J} = \vec{J_{1}} + \vec{J_{2}}\)?

In the /product basis/ made of kets \(\vert j_1 m_1, j_2 m_2 \rangle\), \(J_{z}\) is diagonal. Its spectrum is degenerate. These product kets separate out into degenerate subspaces in which the sum of the magnetic quantum numbers \(m = m_{1} + m_{2}\) is invariant. In each degenerate eigenspace of \(J_{z}\), one has to take the available product kets and form linear combinations out of them to form a new basis in which \(J^{2}\) is diagonal.

What are the allowed values of \(j\)? Without loss of generality assume \(j_{1} > j_{2}\). \(j\) can take on values \(j_{1} + j_{2},j_{1} + j_{2} - 1, \dotso, j_{1} - j_{2}\), so that the number of total-\(j\) kets is:

\begin{align*}
\sum_{j=j_{1}-j_{2}}^{j_{1} + j_{2}} \left( 2j + 1 \right) = \sum_{j=0}^{j_{1}+j_{2}} \left( 2j + 1 \right) - \sum_{j=0}^{j_{1}-j_{2}-1} \left( 2j + 1 \right) = \left( 2j_{1} + 1 \right) \left( 2 j_{2} + 1 \right)
\end{align*}

same as the number of product kets \((2j_{1} + 1) \left( 2 j_{2} + 1 \right)\). Thus:

\begin{align*}
j_{1} \otimes j_{2} = \left( j_{1} + j_{2} \right) \oplus \left( j_{1} + j_{2} - 1 \right) \oplus \dotso \oplus \left( j_{1} - j_{2} \right).
\end{align*}

The total-\(j\) kets are:

\begin{align*}
\vert jm, j_{1} j_{2} \rangle \quad \text{with} \quad j_{1} + j_{2} \geq j \geq j_{1} - j_{2}, \qquad j \geq m \geq -j.
\end{align*}

The top state of a total-\(j\) ket with \(j = j_{1} + j_{2}\) and \(m = j_{1} + j_{2}\) can be built out of only /one/ product ket:

\begin{align*}
\vert j_{1} + j_{2}, j_{1} + j_{2} \rangle = \vert j_{1} j_{1}, j_{2} j_{2} \rangle.
\end{align*}

The action of \(J_{-}\) on \(\vert j_{1} + j_{2}, j_{1} + j_{2} \rangle\) is

\begin{align*}
J_{-} \vert j_{1} + j_{2}, j_{1} + j_{2} \rangle = \hbar \sqrt{2 \left( j_{1} + j_{2} \right)} \vert j_{1} + j_{2}, j_{1} + j_{2} - 1 \rangle.
\end{align*}

Therefore

\begin{align*}
\vert j_{1} + j_{2}, j_{1} + j_{2} - 1 \rangle &= \dfrac{1}{\hbar \sqrt{2 \left( j_{1} + j_{2} \right)}} \thinspace J_{-} \vert j_{1} + j_{2}, j_{1} + j_{2} \rangle \\
&= \dfrac{1}{\hbar \sqrt{2 \left( j_{1} + j_{2} \right)}} \left( J_{1-} + J_{2-} \right) \vert j_{1} + j_{2}, j_{1} + j_{2} \rangle \\
&= \sqrt{\dfrac{j_{1}}{j_{1} + j_{2}}} \thinspace \thinspace \vert j_{1} -1 + j_{2}, j_{1} + j_{2} \rangle \\
&+ \sqrt{\dfrac{j_{2}}{j_{1} + j_{2}}} \vert j_{1} + j_{2}, j_{1} + j_{2} - 1 \rangle \\
&= \sqrt{\dfrac{j_{1}}{j_{1} + j_{2}}} \thinspace \vert j_{1} \left( j_{1} -1 \right), j_{2} j_{2} \rangle \\
&+ \sqrt{\dfrac{j_{2}}{j_{1} + j_{2}}} \thinspace \vert j_{1} j_{1}, j_{2} \left( j_{2} - 1 \right) \rangle
\end{align*}

The top state of a total-\(j\) ket \(j = j_{1} + j_{2} - 1\) with \(m = j_{1} + j_{2} - 1\) can be built out of /two/ product ket: \(\vert j_1 j_1, j_2 \left( j_2 - 1 \right) \rangle\) and \(\vert j_{1} \left( j_{1} - 1 \right), j_{2} j_{2} \rangle\). We have two conditions:

1) A linear combination of these kets must be normalized to unity,
2) It must be orthogonal to the ket \(\vert (j_{1}+j_{2})(j_{1}+j_{2}-1) , j_1 j_2 \rangle\).

By inspection:

\begin{align*}
\vert j_{1} + j_{2} - 1, j_{1} + j_{2} - 1 \rangle &= \sqrt{\dfrac{j_{1}}{j_{1} + j_{2}}} \vert j_{1} j_{1}, j_{2} \left( j_{2} - 1 \right) \rangle \\
&- \sqrt{\dfrac{j_{2}}{j_{1} + j_{2}}} \vert j_{1} \left( j_{1} - 1 \right), j_{2} j_{2} \rangle
\end{align*}

The overall sign is fixed by the requirement that the coefficient of the product ket with \(m_{1} = j_{1}\) be positive.

The top state of a total-\(j\) ket with \(j = j_{1} + j_{2} - 2\) and \(m = j_{1} + j_{2} - 2\) can be built out of /three/ product kets: \(\vert j_1 j_1, j_2 \left( j_2 - 2 \right) \rangle\), \(\vert j_1 \left( j_{1} - 2 \right), j_2 j_2 \rangle\), and \(\vert j_1 \left( j_{1} - 1 \right), j_2 \left( j_2 - 1 \right) \rangle\). We have three conditions:

1) A linear combination of these kets must be normalized to unity,
2) It must be orthogonal to \(\vert (j_{1}+j_{2})(j_{1}+j_{2}-2) , j_1 j_2 \rangle\),
3) It must be orthogonal to \(\vert (j_{1}+j_{2}-1)(j_{1}+j_{2}-2) , j_1 j_2 \rangle\).

It is clear that there are always enough constraints to determine the top states of each \(j\), and once the top states are known, the rest can be obtained by use of \(J_{-}\).
** Clebsch-Gordan (CG) coefficients
The completeness of the product kets allows us to write the total-\(j\) kets as:

\begin{align*}
\vert jm, j_{1} j_{2} \rangle = \sum_{m_{1}, m_{2}} \vert j_{1} m_{1}, j_{2} m_{2} \rangle \left \langle j_{1} m_{1}, j_{2} m_{2} \vert jm, j_{1} j_{2} \right \rangle
\end{align*}

The coefficients of the expansion:

\begin{align*}
\left \langle j_{1} m_{1}, j_{2} m_{2} \left \lvert jm, j_{1} j_{2}  \right \rvert  \right \rangle \equiv \left \langle j_{1} m_{1}, j_{2} m_{2} \vert jm \right \rangle
\end{align*}

are called /Clebsch-Gordan coefficients/ or /vector addition coefficients/. The Clebsch-Gordan coefficients have the properties:

1) \(\left \langle j_1 m_1, j_2 m_2 \vert jm \right \rangle \neq 0\) only if \(j_{1} - j_{2} \leq j \leq j_{1} + j_{2}\) (/triangle inequality/,
2) \(\left \langle j_1 m_1, j_2 m_2 \vert jm \right \rangle \neq 0\) only if \(m_{1} + m_{2} = m\),
3) they are real (convention)
4) \(\left \langle j_1 j_1, j_2 \left( j - j_1 \right) \vert jj \right \rangle\) is positive (conventional)
5) \(\left \langle j_1 m_1, j_2 m_2 \vert jm \right \rangle = \left( -1 \right)^{j_{1} + j_{2} - j} \left \langle j_{1} \left( - m_{1} \right), j_{2} \left( -m_{2} \right)  \vert j \left( -m \right) \right \rangle\)

The fifth property halves the work we have to do: we start at the top state and work our way down to \(m = 0\) (or \(1/2\) if \(j\) is half-integral). The coefficients of the negative \(m\) states are then determined by this relation.

A matrix made up of the CG-coefficients is orthogonal and unitary. This follows from the fact that it relates one orthonormal basis to another. If we invert the matrix, we can write the product kets in terms of the total-\(j\) kets. The coefficients in this expansion are also CG coefficients:

\begin{align*}
\left \langle jm \vert j_{1} m_{1}, j_{2} m_{2} \right \rangle = \left \langle j_{1} m_{1}, j_{2} m_{2} \vert jm \right \rangle^{\ast} = \left \langle j_{1} m_{1}, j_{2} m_{2} \vert jm \right \rangle.
\end{align*}
** Addition of \(L\) and \(S\)
The total angular momentum \(\vec{J} = \vec{L} + \vec{S}\) can have maximum value of \(j = l + s\) and a minimum value \(j = l - s\). We wish to express the total-\(j\) states \(\vert jm, ls \rangle\) in terms of product states \(\vert l m_o, s m_{s} \rangle\), where \(m_{o}\) is the orbital magnetic quantum number and \(m_{s}\) is the spin magnetic quantum number.

We expand the total-\(j\) states as:

\begin{align*}
\vert jm, l s \rangle = \sum_{m_{1}, m_{2}} \vert l m_{o}, s m_{s} \rangle \left \langle l m_{o}, s m_{s} \vert jm, l s \right \rangle
\end{align*}

The Clebsch-Gordan coefficients are:

\begin{align*}
\left \langle l m_{o}, s m_{s} \left \lvert jm, ls \right \rangle \equiv \left \langle l m_{o}, s m_{s} \left \lvert jm \right \rangle.
\end{align*}

As an example consider an electron bound to a proton in a state of orbital angular momentum \(l\). Since the electron has spin \(1/2\), its total angular momentum \(\vec{J} = \vec{L} + \vec{S}\) can have values of \(j = l \pm 1/2\). We wish to express the total-\(j\) states in terms of product states \(\vert l m_{o}, s m_{s} \rangle\). Since \(m_{s} = \pm 1/2\), at each \(m\) there will be at the most two eligible product kets. Let

\begin{align*}
\vert j = l+1/2, m \rangle = \alpha \vert l, m-1/2; 1/2, 1/2 \rangle + \beta \vert l, m+1/2; 1/2, -1/2 \rangle
\end{align*}

\begin{align*}
\vert j = l - 1/2, m \rangle = \alpha^{\prime} \vert l, m-1/2; 1/2, 1/2 \rangle + \beta^{\prime} \vert l, m + 1/2; 1/2, -1/2 \rangle
\end{align*}

The requirement that these states be orthonormal tells us that

\begin{align*}
\alpha^{2} + \beta^{2} = 1
\end{align*}

\begin{align*}
\alpha^{\prime}^{2} + \beta^{\prime}^{2} = 1
\end{align*}

\begin{align*}
\alpha \alpha^{\prime} + \beta \beta^{\prime} = 0.
\end{align*}

We need one more constraint. We do so by demanding:

\begin{align*}
J^{2} \vert j= l+1/2, m \rangle = \hbar^{2} \left( l + 1/2 \right) \left( l + 3/2 \right) \vert j=l+1/2, m \rangle.
\end{align*}

Writing

\begin{align*}
J^{2} = L^{2} + S^{2} + 2 L_{z} S_{z} + L_{-} S_{+} + L_{+} S_{-}
\end{align*}

we can deduce that (see =Exercise 15.2.4=)

\begin{align*}
\dfrac{\beta}{\alpha} = \left( \dfrac{l + 1/2 - m}{l + 1/2 + m} \right)^{1/2}.
\end{align*}

The previous condition, this, and the convention for the overall sign fix \(\vert j = l \pm 1/2, m \rangle\). (see =Exercise 15.2.4=)

\begin{align*}
\vert j = l \pm 1/2, m \rangle &= \dfrac{1}{\sqrt{2l + 1}} \Big [ \pm \sqrt{l + 1/2 \pm m} \thinspace \vert l, m-1/2; 1/2, 1/2 \rangle \\
&+ \sqrt{l + 1/2 \mp m} \thinspace \vert l, m + 1/2; 1/2, -1/2 \rangle \Big ]
\end{align*}

If the Hamiltonian contains just the Coulomb interaction, or, in addition, an interaction with a weak constant magnetic field, the product basis is adequate. The total-\(j\) basis is useful when considering the /spin-orbit interaction/ where the operator \(\vec{L} \cdot \vec{S} = \dfrac{1}{2} \left( J^{2} - L^{2} - S^{2} \right)\) enters the Hamiltonian.
** Irreducible tensor operators
A /first-rank tensor/ \(\vert T^{(1)} \rangle\) is just a vector \(\vert V \rangle\) and is an element of vector space \(\mathbb{V}^{n}(R)\), i.e., may be written as:

\begin{align*}
\vert V \rangle = \sum_{i=1}^{n} v_{i} \vert i \rangle,
\end{align*}

where the kets \(\vert i \rangle\) form a basis for \(\mathbb{V}^{n}(R)\) and \(v_{i}\) are the components along these kets.

A /tensor operator/ of rank 1 is just a vector operator:

\begin{align*}
\vec{V} = \sum_{i=1}^{n} V_{i} \vert i \rangle.
\end{align*}

The operator \(V_{i}\) defined from \(\mathbb{V}^{n}(R)\) to \(\mathbb{V}^{n}(R)\) /transform like vectors/, i.e., under \(V_{i} \to U^{\dagger} V_{i} U\) respond as do the vector component \(v_{i}\) or equivalently, under \(V_{i} \to U V_{i} U^{\dagger}\), respond as do the basis kets \(\vert i \rangle\).

A /second-rank tensor/ \(\vert T^{(2)} \rangle\) is an element of the direct product space \(\mathbb{V}^{3}(R) \otimes \mathbb{V}^{3}(R)\), i.e., may be written as:

\begin{align*}
\vert T^{(2)} \rangle = \sum_{i=1}^{3} \sum_{j=1}^{3} t_{ij} \vert i \rangle \otimes \vert j \rangle.
\end{align*}

where the nine kets \(\vert i \rangle \otimes \vert j \rangle\) for a basis for \(\mathbb{V}^{3}(R) \otimes \mathbb{V}^{3}(R)\) and \(t_{ij}\) are the components along these kets.

A /tensor operator/ of rank 2 is:

\begin{align*}
\vert T^{(2)} \rangle = \sum_{i=1}^{3} \sum_{j=1}^{3} T_{ij} \vert i \rangle \otimes \vert j \rangle.
\end{align*}

The operator \(T_{ij}\) defined from \(\mathbb{V}^{n}(R) \otimes \mathbb{V}^{n}(R)\) to \(\mathbb{V}^{n}(R) \otimes \mathbb{V}^{n}(R)\) /transform like vectors/, i.e., under \(T_{ij} \to U^{\dagger} T_{ij} U\) respond as do the vector component \(T_{ij}\) or equivalently, under \(T_{ij} \to U T_{ij} U^{\dagger}\), respond as do the basis kets \(\vert i \rangle \otimes \vert j \rangle\).

Higher ranks may similarly be defined. These are called /Cartesian tensors/.

Another class of tensors are the /spherical tensor operators/. A spherical tensor operator of rank \(k\) has \(2k + 1\) components \(T_{k}^{q}\), \(q = +k, \left( k-1 \right), \dotso, -k\), which, under \(T_{k}^{q} \to U T_{k}^{q} U^{\dagger}\) respond like the angular momentum eigenkets \(\vert j = k, m=q \rangle = \vert kq \rangle\):

\begin{align*}
U \left[ R \right] T_{k}^{q} U^{\dagger} \left[ R \right] = \sum_{q^{\prime}} D_{q^{\prime} q}^{(k)} T_{k}^{q^{\prime}}.
\end{align*}

Since the \(2k + 1\) kets \(\vert kq \rangle\) transform irreducibly, so do the operators \(T_{k}^{q}\). For this reason, they are also called /irreducible tensor operators/. We have the identities (see =Exercise 15.3.1=):

\begin{align*}
\left[ J_{\pm}, T_{k}^{q} \right] = \pm \hbar \left[ \left( k \mp q \right) \left( k \pm q + 1 \right) \right]^{1/2} T_{k}^{q \pm 1},
\end{align*}

\begin{align*}
\left[ J_{z}, T_{k}^{q} \right] = \hbar q T_{k}^{q}.
\end{align*}

Commuting a \(J\) with \(T_{k}^{q}\) is like letting \(J\) act on the ket \(\vert kq \rangle\). Let \(U \left[ R \right] T_{k}^{q}\) act on the ket \(\vert \alpha l m \rangle\):

\begin{align*}
U \left[ R \right] T_{k}^{q} \vert jm \rangle &= U \left[ R \right] T_{k}^{q} U^{\dagger} \left[ R \right] U \left[ R \right] \vert jm \rangle \\
&= \sum_{q^{\prime}} D_{q^{\prime}q}^{(k)} T_{k}^{q^{\prime}} \sum_{m^{\prime}} D_{m^{\prime}m}^{(j)} \vert jm^{\prime} \rangle \\
&= \sum_{q^{\prime}} \sum_{m^{\prime}} D_{q^{\prime}q}^{(k)} D_{m^{\prime} m}^{(j)} T_{k}^{q^{\prime}} \vert j m^{\prime} \rangle.
\end{align*}

\(T_{k}^{q} \vert jm \rangle\) responds to rotations like the product ket \(\vert kq \rangle \otimes \vert jm \rangle\). /Thus, when we act on a state with/ \(T_{k}^{q}\), /we add angular momentum/ \((k,q)\) /to the state/. In other words, an irreducible operator \(T_{k}^{q}\) imparts a definite amount of angular momentum \((k,q)\) to the state it acts on. Thus, the matrix elements of \(T_{k}^{q}\) between angular momentum eigenkets is:

\begin{align*}
\left \langle \alpha^{\prime} j^{\prime} m^{\prime} \left \lvert T_{k}^{q}  \right \rvert \alpha j m \right \rangle = 0 \quad \text{unless} \quad k + j \geq j^{\prime} \geq \left \lvert k-j \right \rvert, \quad m^{\prime} = m+q.
\end{align*}

This is because \(T_{k}^{q} \vert \alpha j m \rangle\) contains only those angular momenta that can be obtained by adding \((k,q)\) and \((j,m)\); so \(\vert \alpha^{\prime} j^{\prime} m^{\prime} \rangle\) is orthogonal to \(T_{k}^{q} \vert jm \rangle\) unless \((j^{\prime}, m^{\prime})\) is one of the possible results of adding \((k, q)\) and \((j,m)\). The equation above is an example of a /selection rule/.

In general

\begin{align*}
\left \langle \alpha_{2} j_{2} m_{2} \left \lvert T_{k}^q  \right \rvert \alpha_{1} j_{1} m_{1} \right \rangle = \left \langle \alpha_{2} j_{2} \left \lvert T_{k}  \right \rvert \alpha_{1} j_{1} \right \rangle \cdot \left \langle j_{2} m_{2} \vert kq, j_{1} m_{1} \right \rangle.
\end{align*}

This is called the /Wigner-Eckart theorem/. It seperates the dependence of the matrix element on spatial orientation (on \(m_{2}\), \(m_{1}\), and \(q\)) from the rest. The former is expressed entirely in terms of the CG coefficients.
* The Variational and WKB Methods                          
* Time-Independent Perturbation Theory
:LOGBOOK:
CLOCK: [2022-11-25 Fri 01:08]--[2022-11-25 Fri 03:17] =>  2:09
CLOCK: [2022-11-24 Thu 23:27]--[2022-11-25 Fri 00:06] =>  0:39
CLOCK: [2022-11-13 Sun 22:08]--[2022-11-13 Sun 23:57] =>  1:49
:END:
** Non-degenerate perturbation theory

We want to solve:

\begin{align*}
H \vert n \rangle = E_{n} \vert n \rangle, \qquad H = H^{0} + H^{1}.
\end{align*}

\(H^{0}\) is called the /unperturbed Hamiltonian/ and \(H^{1}\) is called a /perturbation/.

To proceed we /assume/:

1) \(H\) is /non-degenerate/.
2) the eigenkets and eigenvalues of \(H\) may be expanded in a /perturbation series/:

  \begin{align*}
  \vert n \rangle = \sum_{k} \vert n^{k} \rangle = \vert n^{0} \rangle +   \vert n^{1} \rangle + \vert n^{2} \rangle + \dotso,
   \end{align*} 

   \begin{align*}
   E_{n} = \sum_{k} E_{n}^{k} = E_{n}^{0} + E_{n}^{1} + E_{n}^{2} + \dotso.
   \end{align*}  

3) the perturbation \(H^{1}\) is /small/ i.e.,

   \begin{align*}
   \vert n^{k-1} \rangle \gg \vert n^{k} \rangle \quad \text{and} \quad    E_{n}^{k-1} \gg E_{n}^{k} \quad \text{for} \quad k \geq 1.
 \end{align*}  

4) There exists solutions for

   \begin{align*}
   H^{0} \vert n^{0} \rangle = E_{n}^{0} \vert n^{0} \rangle.
 \end{align*}  

5) there exists a one-to-one map \(\vert n^{0} \rangle \mapsto \vert n \rangle\) such that

   \begin{align*}
   H^{0} \vert n^{0} \rangle = E_{n}^{0} \vert n^{0} \rangle    \Longrightarrow H \vert n \rangle = E_{n} \vert n \rangle;
 \end{align*}  

With these assumptions \(H \vert n \rangle = E_{n} \vert n \rangle\) becomes:

\begin{align*}
\left( H^{0} + H^{1} \right) \left[ \vert n^{0} \rangle + \vert n^{1} \rangle + \dotso \right] = \left( E_{n}^{0} + E_{n}^{1} + \dotso \right) \left[ \vert n^{0} \rangle + \vert n^{1} \rangle + \dotso \right].
\end{align*}

To /zeroth-order/:

\begin{align*}
H^{0} \vert n^{0} \rangle = E_{n}^{0} \vert n^{0} \rangle.
\end{align*}

\(E_{n}^{0}\) and \(\vert n^0 \rangle\) are known by assumption.

To /first-order/:

\begin{align*}
H^{0} \vert n^{1} \rangle + H^{1} \vert n^{0} \rangle = E_{n}^{0} \vert n^{1} \rangle + E_{n}^{1} \vert n^{0} \rangle,
\end{align*}

so that:

\begin{align*}
E_{n}^{1} = \left \langle n^{0} \left \lvert H^{1}  \right \rvert n^{0} \right \rangle, \quad \text{and} \quad \vert n^{1} \rangle = \sum_{m}^{\prime} \vert m^0 \rangle  \dfrac{\left \langle m^{0} \left \lvert H^1  \right \rvert n^{0} \right \rangle}{E_{n}^{0}-E_{m}^{0}}.
\end{align*}

In determining \(\vert n^1 \rangle\), we have demanded that \(\vert n \rangle\) be normalized /to first order/.

To /second-order/:

\begin{align*}
H^{0} \vert n^{2} \rangle + H^{1} \vert n^{1} \rangle = E_{n}^{0} \vert n^{2} \rangle + E_{n}^{1} \vert n^{1} \rangle + E_{n}^{2} \vert n^{0} \rangle,
\end{align*}

so that:

\begin{align*}
E_{n}^{2} = \sum_{m}^{\prime} \dfrac{\left \lvert \left \langle n^{0} \left \lvert H^{1}  \right \rvert m^{0} \right \rangle  \right \rvert^{2}}{E_{n}^{0} - E_{m}^{0}},
\end{align*}

and

\begin{align*}
\vert n^{2} \rangle = \sum_{m}^{\prime} \sum^{\prime}_{l} \vert m^{0} \rangle \dfrac{\left \langle m^{0} \left \lvert H^{1}  \right \rvert l^{0} \right \rangle \left \langle l^{0} \left \lvert H^1  \right \rvert n^{0} \right \rangle}{\left(E_{n}^{0}-E_{m}^{0}\right)\left( E_{n}^{0} - E_{l}^{0}\right)}
- \sum_{m}^{\prime} \vert m^{0} \rangle \dfrac{\left \langle m^{0} \left \lvert H^{1}  \right \rvert n^{0} \right \rangle \left \langle n^{0} \left \lvert H^1  \right \rvert n^{0} \right \rangle}{ \left( E_{n}^{0} - E_{m}^{0} \right)^{2}}.
\end{align*}

In determining \(\vert n^2 \rangle\), we have demanded that \(\vert n \rangle\) be normalized /to second order/.

Suppose there exists operator \(\Omega\) such that

\begin{align*}
H^{1} = \left[ \Omega, H^{0} \right].
\end{align*}

Then

\begin{align*}
E_{n}^{2} &= \sum_{m}^{\prime} \dfrac{\left \langle n^{0} \left \lvert H^1  \right \rvert m^{0} \right \rangle \left \langle m^{0} \left \lvert \Omega H^{0} - H^{0} \Omega \right \rvert n^{0} \right \rangle}{E_{n}^{0} - E_{m}^{0}} \\
&= \sum_{m}^{\prime} \left \langle n^{0} \left \lvert H^1  \right \rvert m^{0} \right \rangle \left \langle m^{0} \left \lvert \Omega \right \rvert n^{0} \right \rangle \\
&= \left \langle n^{0} \left \lvert H^{1} \Omega \right \rvert n^{0} \right \rangle - \left \langle n^{0} \left \lvert H^{1}  \right \rvert n^{0} \right \rangle \left \langle n^{0} \left \lvert \Omega  \right \rvert n^{0} \right \rangle
\end{align*}

Suppose there exists operator \(\Omega\) such that

\begin{align*}
H^{1} \vert n^{0} \rangle = \left[ \Omega, H^{0} \right] \vert n^{0} \rangle
\end{align*}

for a given \(\vert n^0 \rangle\). Then for /this value of/ \(n\):

\begin{align*}
E_{n}^{2} = \left \langle n^{0} \left \lvert H^{1} \Omega \right \rvert n^{0} \right \rangle - \left \langle n^{0} \left \lvert H^{1}  \right \rvert n^{0} \right \rangle \left \langle n^{0} \left \lvert \Omega  \right \rvert n^{0} \right \rangle.
\end{align*}

Demanding \(\vert n^0 \rangle \gg \vert n^1 \rangle\) is equivalent to the condition

\begin{align*}
\left \lvert \dfrac{\left \langle m^{0} \left \lvert H^1  \right \rvert n^{0} \right \rangle}{E_{n}^{0}-E_{m}^{0}}  \right \rvert \ll 1.
\end{align*}

The condition has dependence on:

1) the absolute size of \(H^{1}\);
2) the matrix elements of \(H^{1}\) between unperturbed states;
3) the energy difference between the levels.
** Selection rules
:LOGBOOK:
CLOCK: [2022-11-25 Fri 04:02]--[2022-11-25 Fri 06:00] =>  1:58
:END:

\begin{align*}
\left[ \Omega, H^{1} \right] = 0 \Longrightarrow \left \langle \alpha_{2} \omega_{2} \left \lvert H^{1}  \right \rvert \alpha_{1} \omega_{1} \right \rangle = 0 \quad \text{unless} \quad \omega_{1} = \omega_{2}.
\end{align*}

#+NAME: Wigner-Eckart Theorem
#+begin_theorem latex
Given a tensor operator \(T^{(k)}\) and two states of angular momenta \(j\) and \(j^{\prime}\), there exists a constant \(\left \langle j \left \lvert \lvert T^{(k)}  \right \rvert \rvert j^{\prime} \right \rangle\) such that for all \(m\), \(m^{\prime}\), and \(q\), the following equation is satisfied:

\begin{align*}
\left \langle j m \left \lvert T_{q}^{(k)}  \right \rvert j^{\prime} m^{\prime} \right \rangle = \left \langle j^{\prime} m^{\prime} k q \left \vert j m \right \rangle \left \langle j \left \lvert \vert T^{(k)}  \vert \right \rvert j^{\prime} \right \rangle,
\end{align*}

where

1) \(T_q(k)\) is the q-th component of the spherical tensor operator \(T^{(k)}\) of rank \(k\),
2) \(\vert jm \rangle\) denotes an eigenstate of total angular momentum \(J^{2}\) and its \(z\) component \(J_{z}\),
3) \(\left \langle j^{\prime} m^{\prime} k q \left \vert j m \right \rangle\) is the /Clebsch-Gordan coefficient/ for coupling \(j^{\prime}\) with \(k\) to get \(j\),
4) \(\left \langle j \left \lvert \left \lvert T^{(k)}  \right \rvert  \right \rvert j^{\prime} \right \rangle\) denotes some value that does not depend on \(m\), \(m^{\prime}\), nor \(q\) and is referred to as the /reduced matrix element/.
#+end_theorem


If \(\left[ \Omega, H^{1} \right] = 0\), then \(\left \langle \alpha_2 \omega_2 \left \lvert H^{1} \right \rvert \alpha_1 \omega_1 \right \rangle\) unless \(\omega_{1} = \omega_{2}\).

By *Wigner-Eckart Theorem*

\begin{align*}
\left \langle \alpha_{2} j_{2} m_2 \left \lvert T_{k}^{q} \right \rvert \alpha_{1} j_{1} m_{1} \right \rangle = 0 \quad \text{unless}
\begin{cases}
j_{1} + k \geq j_{2} \geq \left \lvert j_{1} - k  \right \rvert \\
m_{2} = m_{1} + q
\end{cases},
\end{align*}

where \(T_{k}^{q}\) is a tensor operator carrying angular momentum \((k,q)\). In words, the matrix element vanishes unless \(\vert \alpha_2 j_2 m_2 \rangle\) has the angular momentum that obtains when we add to \((j_{1} m_{1})\) the angular momentum \((kq)\)imparted by the operator. This is called the /angular momentum selection rule/.

If \(H^{1} = \lambda Z \sim T_{1}^{0}\),

\begin{align*}
\left \langle \alpha_{2} j_{2} m_{2} \left \lvert Z \right \rvert \alpha_{1} j_{1} m_{1} \right \rangle = 0 \quad \text{unless}
\begin{cases}
j_{2} = j_{1} + 1, \thinspace j_{1}, \thinspace j_{1} - 1 \\
m_{2} = m_{1}
\end{cases}.
\end{align*}

If \(H^{1} = \lambda X \text{ or } \lambda Y (\sim T_{1}^{\pm1})\),

\begin{align*}
\left \langle \alpha_{2} j_{2} m_{2} \left \lvert X \text{ or } Y \right \rvert \alpha_{1} j_{1} m_{1} \right \rangle = 0 \text{ unless }
\begin{cases}
j_{2} = j_{1} + 1, \thinspace j_{1}, j_{1} - 1 \\
m_{2} = m_{1} \pm 1.
\end{cases}
\end{align*}

The matrix element of \(\Omega\) between eigenstates of the parity operator vanishes unless they have opposite parity:

\begin{align*}
\Pi^{\dagger} \Omega \Pi = - \Omega.
\end{align*}

This is called the /parity selection rule/.

Combination of the angular momentum selection rule and parity selection rule yield the /dipole selection rule/:

\begin{align*}
\left \langle \alpha_{2} j_{2} m_{2} \left \lvert Z \right \rvert \alpha_{1} j_{1} m_{1} \right \rangle = 0 \quad &\text{ unless }
\begin{cases}
j_{2} = j_{1} \pm 1 \\
m_{2} = m_{1}
\end{cases}, \\
\left \langle \alpha_{2} j_{2} m_{2} \left \lvert X \text{ or } Y \right \rvert \alpha_{1} j_{1} m_{1} \right \rangle = 0 &\text{ unless }
\begin{cases}
j_{2} = j_{1} \pm 1 \\
m_{2} = m_{1} \pm 1.
\end{cases}.
\end{align*}

(States of orbital angular momentum \(l\) have definite parity \((-1)^{l}\)).

The response of the hydrogen atom ground state to a constant external electric field \(E = \mathcal{E} \vec{k}\) is called the *Stark Effect*.

\begin{align*}
H^{1} = e Z \mathcal{E} = - \mu_{e} \cdot E, \quad \mu_{e} = e \left( \vec{r}_{2} - \vec{r}_{1} \right) = - e \vec{r}.
\end{align*}

The first-order shift in energy:

\begin{align*}
E_{100}^{1} = \left \langle 100 \left \lvert e Z \mathcal{E} \right \rvert 100 \right \rangle = \left \langle 100 \left \lvert - \vec{\mu} \cdot \vec{E} \right \rvert 100 \right \rangle = - \left \langle 100 \left \lvert \mu  \right \rvert 100 \right \rangle \cdot E = 0.
\end{align*}

Bounds for the second order shift in energy are obtained as:

\begin{align*}
\left \lvert E_{100}^{2} \right \rvert \leq \dfrac{e^{2} \mathcal{E}^{2}}{\left \lvert E_{1}^{0} - E_{2}^{0} \right \rvert} \sum_{nlm}^{\prime} \left \lvert \left \langle nlm \left \lvert Z  \right \rvert 100 \right \rangle  \right \rvert^{2},
\end{align*}

since

\begin{align*}
E_{100}^{2} = \sum_{nlm}^{\prime} \dfrac{e^{2} \mathcal{E}^{2} \left \lvert \left \langle nlm \left \lvert Z  \right \rvert 100 \right \rangle  \right \rvert^2}{E_{100}^{0}-E_{nlm}^{0}},
\end{align*}

where

\begin{align*}
E_{100}^{0} - E_{nlm}^{0} = - \text{Ry} \left( 1 - \dfrac{1}{n^{2}} \right) = \text{Ry} \left( \dfrac{1-n^{2}}{n^{2}} \right) :
\end{align*}

and the magnitude of the energy denominator grows with \(n\). Now

\begin{align*}
&\sum_{nlm}^{\prime} \left \lvert \left \langle nlm \left \lvert Z  \right \rvert 100 \right \rangle  \right \rvert^{2} \\
&= \sum_{nlm}^{\prime} \left \langle 100 \left \lvert Z  \right \rvert nlm \right \rangle \left \langle nlm \left \lvert Z  \right \rvert 100 \right \rangle \\
&= \sum_{nlm}^{\prime} \left \langle 100 \left \lvert Z  \right \rvert nlm \right \rangle \left \langle nlm \left \lvert Z  \right \rvert 100 \right \rangle - \left \langle 100 \left \lvert Z  \right \rvert 100 \right \rangle^{2} \\
&= \left \langle 100 \left \lvert Z^{2}  \right \rvert 100 \right \rangle - \left \langle 100 \left \lvert Z  \right \rvert 100 \right \rangle^{2} \\
&= a_{0}^{2} - 0 = a_{0}^{2}.
\end{align*}

\begin{align*}
\left \lvert E_{100}^{2} \right \rvert &\leq \dfrac{e^{2} \mathcal{E}^{3}}{\left \lvert \left( e^{2}/ 2 a_{0} \right) \left( 1 - 1/4 \right) \right \rvert} a_{0}^{2} \\
&\leq \dfrac{8 a_{0}^{3} \mathcal{E}^{2}}{3}.
\end{align*}

Keeping just the first term yields a lower bound:

\begin{align*}
\left \lvert E_{100}^{2}  \right \rvert \geq \dfrac{e^{2} \mathcal{E}^{2}}{3 e^{2}/ 8 a_{0}} \left \lvert \left \langle 210 \left \lvert Z  \right \rvert 100 \right \rangle  \right \rvert^{2}
\end{align*}

With

\begin{align*}
\left \lvert \left \langle 210 \left \lvert Z  \right \rvert 100 \right \rangle  \right \rvert^{2} = \dfrac{2^{15} a_{0}^{2}}{3^{10}} \simeq 0.55 a_{0}^{2},
\end{align*}
\begin{equation*}


}
\end{equation*}

\begin{align*}
\left \lvert E_{100}^{2} \right \rvert \geq \left( 0.55 \right) \dfrac{8}{3} \mathcal{E}^{2} a_{0}^{3}.
\end{align*}

Therefore:

\begin{align*}
\left( 0.55 \right) \dfrac{8}{3} \mathcal{E}^{2} a_{0}^{3} \leq \left \lvert E_{100}^{2}  \right \rvert \leq \dfrac{8 a_{0}^{3} \mathcal{E}^{2}}{3}.
\end{align*}

Suppose that

\begin{align*}
H^{1} \vert 100 \rangle = \left[ \Omega, H^{0} \right] \vert 100 \rangle.
\end{align*}

\begin{align*}
\Omega \xrightarrow[]{\text{coordinate basis}} - \dfrac{m a_{0} e \mathcal{E}}{\hbar^{2}} \left( \dfrac{r^{2} \cos \theta}{2} + a_{0} r \cos \theta \right).
\end{align*}

The second order shift in energy is

\begin{align*}
\left \lvert E_{100}^{2} \right \rvert &= \left \lvert \left \langle 100 \left \lvert H^{1} \Omega  \right \rvert 100 \right \rangle - 0  \right \rvert \\
&= \left \lvert \left \langle 100 \left \lvert e Z \mathcal{E} \Omega  \right \rvert 100 \right \rangle  \right \rvert \\
&= \dfrac{9}{4} a_{0}^{3} \mathcal{E}^{2} = \dfrac{8}{3} a_{0}^{3} \mathcal{E}^{2} \cdot \left( \dfrac{27}{32} \right) \\
&= \left( 0.84 \right) \dfrac{8}{3} a_{0}^{3} \mathcal{E}^{2}.
\end{align*}

\(E_{100}^{2}\) represents the interaction of the induced dipole moment with the applied field. Imagine two charges \(\pm q\) separated by a distance \(x\) along \(E\). The work done on the system as \(x\) changes by \(dx\) is

\begin{align*}
dW &= - q \mathcal{E} dx \\
&= - \mathcal{E} d \mu.
\end{align*}

/Assuming/ that the induced moment is proportional to \(\vec{E}\):

\begin{align*}
\vec{\mu} = \alpha \vec{E},
\end{align*}

(where \(\alpha\) is called the /polarizability/), then

\begin{align*}
d W = - \alpha \mathcal{E} d \mathcal{E},
\end{align*}

or

\begin{align*}
W = - \dfrac{1}{2} \alpha \mathcal{E}^{2} = \left \langle 100 \left \lvert H^{1}  \right \rvert 100 \right \rangle = E_{100}^{2}.
\end{align*}

Using \(\left \lvert E_{100}^{2} \right \rvert = \left( 0.84 \right) \dfrac{8}{3} a_{0}^{3} \mathcal{E}^{2}\),

\begin{align*}
\alpha = \dfrac{18}{4} a_{0}^{3} \simeq \dfrac{18}{4} \left( 0.5 \textup{\AA} \right)^{3} \simeq 0.56 \textup{\AA}^{3}.
\end{align*}

/The second-order shift in the ground state energy is *always* negative (unless it vanishes). Since \(E_{0}^{2}\) measures the energy shift due to the first-order change in the ground -state state vector, we conclude that the system changes its configuration so as to lower its energy of interaction with the external field.
** Degenerate perturbation theory.
Without loss of generality, assume that \(H^{0}\) has a /degenerate subspace/ and \(H^{0} + H^{1}\) is non-degenerate in this subspace. In a basis that diagonalizes \(H^{1}\) *within the degenerate subspace*

\begin{align*}
\vert n^{1} \rangle = \sum_{m}^{\prime} \vert m^0 \rangle  \dfrac{\left \langle m^{0} \left \lvert H^1  \right \rvert n^{0} \right \rangle}{E_{n}^{0}-E_{m}^{0}}
\end{align*}

has a \(0/0\) form whenever \(\vert n^0 \rangle\) and \(\vert m^0 \rangle\) belong to the degenerate subspace and a divergence is avoided.

Such a basis need not be the full Hilbert space, only a basis within the degenerate subspace that diagonalizes \(H^{1}\).

For the Stark effect (\(H^{1} = e \mathcal{E} Z\)) in the \(n=2\) level of hydrogen, the selection rules tell us that only two of the \(16\) matrix elements are non-zero:

\begin{align*}
H^{1} \to
\begin{pmatrix}
0 & \Delta & 0 & 0  \\
\Delta & 0 & 0 & 0  \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{pmatrix},
\end{align*}

where the rows are ordered as \((nlm) = 200, \thinspace 210, \thinspace 211, \thinspace 21 -1\) and

\begin{align*}
\Delta = \left \langle 200 \left \lvert e \mathcal{E} Z \right \rvert 210 \right \rangle = - 3 e \mathcal{E} a_{0}.
\end{align*}

* Time-Dependent Perturbation Theory                       
* Scattering Theory                                        
* The Dirac Equation                                       
* Path Integrals: Part II                                  
