:PROPERTIES:
:ID:       7ed363af-27d6-4ab2-ac7a-3c99eee0e89c
:END:
#+TITLE: Scientific method
#+FILETAGS: :concept:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org

The *scientific method* consists of the following steps:

#+NAME: The scientific method
#+begin_steps
1) Ask a question about a natural phenomenon
2) Make observations of the phenomenon
3) Formulate a hypothesis that tentatively answers the question
4) Predict logical, observable consequences of the hypothesis that have not yet been investigated
5) Test the hypothesis's predictions by an experiment, observational study, field study, or simulation
6) Draw a conclusion from data gathered in the experiment, or revise the hypothesis or form a new one and repeat the process
7) Write a descriptive method of observation and the results or conclusions reached
8) Have peers with experience researching the same phenomenon evaluate the results
#+end_steps

Observations play a role in the second and fifth steps of the scientific method. However, the need for reproducibility requires that observations by different observers can be comparable. Human sense impressions are subjective and qualitative, making them difficult to record or compare. The use of measurement was developed to allow recording and comparison of observations made at different times and places, by different people. The measurement consists of using observation to compare the phenomenon being observed to a standard unit. The standard unit can be an artifact, process, or definition which can be duplicated or shared by all observers. In measurement, the number of standard units which is equal to the observation is counted. Measurement reduces an observation to a number that can be recorded, and two observations which result in the same number are equal within the resolution of the process.

Human senses are limited and subject to errors in perception, such as optical illusions. Scientific instruments were developed to aid human abilities of observation, such as weighing scales, clocks, telescopes, microscopes, thermometers, cameras, and tape recorders, and also translate into perceptible form events that are unobservable by the senses, such as indicator dyes, voltmeters, spectrometers, infrared cameras, oscilloscopes, interferometers, Geiger counters, and radio receivers.

One problem encountered throughout scientific fields is that the observation may affect the process being observed, resulting in a different outcome than if the process was unobserved. This is called the observer effect. For example, it is not normally possible to check the air pressure in an automobile tire without letting out some of the air, thereby changing the pressure. However, in most fields of science, it is possible to reduce the effects of observation to insignificance by using better instruments.

Considered as a physical process itself, all forms of observation (human or instrumental) involve amplification and are thus thermodynamically irreversible processes, increasing entropy.


