:PROPERTIES:
:ID:       c9833db0-2485-449b-8960-5bfdcfc9366e
:END:
#+TITLE: ICML Code of Conduct
#+FILETAGS: :fleeting:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org
#+DATE: [2020-07-09 Thu]

The open exchange of ideas, the freedom of thought and expression, and respectful scientific debate are central to the goals of this conference on machine learning; this requires a community and an environment that recognizes and respects the inherent worth of every person.

*Who* All participants---attendees, organizers, reviewers, speakers, sponsors, and volunteers at our conference, workshops, and conference-sponsored social events---are required to agree with this code of conduct both during the event and on official communication channels, including social media. Organizers will enforce this code, and we expect cooperation from all participants to help ensure a safe and productive environment for everybody.

*Scope* The conference commits itself to providing an experience for all participants that is free from harassment, bullying, discrimination, and retaliation for all participants. This includes offensive comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), politics, technology choices, or any other personal characteristics. Bullying, intimidation, personal attacks, harassment, sustained disruption of talks or other events, and behavior that interferes with another's full participation will not be tolerated. This includes sexual harassment, stalking, following, harassing photography or recording, inappropriate physical contact, unwelcome sexual attention, public vulgar exchanges, and diminutive characterizations, which are all unwelcome in this community.

This Code of Conduct applies to the actual meeting sites and conference venues where ICML business is being conducted, including both physical and official virtual engagement platforms, including video, virtual streaming, and chat-based interaction. ICML is not responsible for non-sponsored activity or behavior that may occur at non-sponsored locations such as hotels, restaurants, or locations not otherwise a sanctioned space for ICML sponsored events (including virtual spaces). ICML will not actively monitor social media platforms, but will follow up on issues of harassment and violations of the code of conduct that occur on those platforms that are specifically related to the ICML program, during the course of ICML, if and when they are brought to our attention.

Sponsors are equally subject to this Code of Conduct. In particular, sponsors should not use images, activities, or other materials that are of a sexual, racial, or otherwise offensive nature. Booth staff (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment. This code applies both to official sponsors as well as any organization that uses the conference name as branding as part of its activities at or around the conference.

*Outcomes* Participants asked by any member of the community to stop any such behavior are expected to comply immediately. If a participant engages in such behavior, the conference organizers may take any action they deem appropriate, including: a formal or informal warning to the offender, expulsion from the conference with no refund, barring from participation in future conferences or their organization, reporting the incident to the offender’s local institution or funding agencies, or reporting the incident to local law enforcement. A response of "just joking" will not be accepted; behavior can be harassing without an intent to offend. If action is taken, an appeals process will be made available.


*Reporting* If you have concerns related to your inclusion at that conference, or observe someone else's difficulties, or have any other concerns related to inclusion, please contact the Diversity and Inclusion co-chairs or the Conference HR Liaison.

The Diversity and Inclusion co-chairs can be reached by email at =diversity-chairs@icml.cc=. The HR Liaison can be reached via the ICML Hotline at either =ICMLhotline@gmail.com= or *858-208-3810*. Conference volunteers will also have this contact information and can assist with connecting you to the co-chairs or the HR Liaison. Complaints and violations will be handled at the discretion of the Diversity & Inclusion co-chairs, general chair, HR Liaison, and the conference board. Reports made during the conference will be responded to in less than 24 hours; those at other times in less than two weeks. We are prepared and eager to help participants contact relevant help services, to escort them to a safe location, or to otherwise assist those experiencing harassment to feel safe for the duration of the conference. We gratefully accept feedback from the community on policy and actions; please contact us.

