:PROPERTIES:
:ID:       fa0e3aa2-347e-48b9-9cb7-e9f0be897281
:END:
#+TITLE: Random variable
#+FILETAGS: :literature:spop:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org

The entity under investigation is a *random variable* \(x\), which has a set of possible outcomes \(\mathcal{S} \equiv\{x_{1}, x_{2}, \cdots\}\). The outcomes may be discrete as in the case of a coin toss, \(S_{\text{coin}}=\{ \text{head}, \text{tail} \}\), or a dice throw, \(\mathcal{S}_{\text {dice }}=\{1,2,3,4,5,6\}\), or continuous as for the velocity of a particle in a gas, \(\mathcal{S}_{\vec{v}}=\left\{-\infty<v_{x}, v_{y}, v_{z}<\infty\right\}\), or the energy of an electron in a metal at zero temperature, \(\mathcal{S}_{\epsilon}=\left\{0 \leq \epsilon \leq \epsilon_{F}\right\}\). An event is any subset of outcomes \(E\subset \mathcal{S}\), and is assigned a probability \(p(E)\), for example, \(p_{\text {dice }}(\{1\})=1 / 6\), or \(p_{\text {dice }}(\{1,3\})=1 / 3\). From an axiomatic point of view, the probabilities must satisfy the following conditions:

(i) Positivity. \(p(E) \geq 0\), that is, all probabilities must be real and non-negative.

(ii) Additivity. \(p(A \, \text{or} \, B)=p(A)+p(B)\), if \(A\) and \(B\) are disconnected events.

(iii) Normalization. \(p(\mathcal{S})=1\), that is, the random variable must have some outcome in \(\mathcal{S}\).