:PROPERTIES:
:ID:       392e8ccd-8871-45e2-a04f-c0b80e1e74b2
:END:
#+TITLE: Muller-Hartmann and Zittartz estimate
#+FILETAGS: :problem:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
8. Muller-Hartmann and Zittartz estimate of the interfacial energy of the d=2 Ising model on a square lattice: (image reference)
(a) Consider an interface on the square lattice with periodic boundary conditions in one direction. Ignoring islands and overhangs, the configurations can be labelled by heights h_{n} for 1 \leq n \leq L. Show that for an anisotropic Ising model of interactions (K_{x}, K_{y}), the energy of an interface along the x-direction is

\begin{align*}
-\beta \mathcal{H}=-2 K_{y} L-2 K_{x} \sum_{n}\left|h_{n+1}-h_{n}\right|
\end{align*}

(b) Write down a column-to-column transfer matrix \langle h|T| h^{\prime}\rangle, and diagonalize it.

(c) Obtain the interface free energy using the result in (b), or by any other method.

(d) Find the condition between K_{x} and K_{y} for which the interfacial free energy vanishes. Does this correspond to the critical boundary of the original 2 d Ising model as computed in the previous problem?

* Solution

* Related Concepts
