:PROPERTIES:
:ID:       9b3da111-adc6-4e06-a50c-9a87f404ccae
:END:
#+TITLE: BTHVN 2020 The Complete Works Tracklist
#+FILETAGS: :concept:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org
* Orchestral Music
** Modern Instruments
- CD1 :: Symphonies Nos. 1 & 2 · Overtures "Prometheus" & "Leonore" No. 3 (1:10:52)
- CD2 :: Symphonies Nos. 3 & 4 (1:22:40)
- CD3 :: Symphonies Nos. 5 & 6 · "Coriolan" Overture (1:22:53)
- CD4 :: Symphonies Nos. 7 & 8 · Wellington's Victory · Overture "Zur Namensfeier" (1:19:03)
- CD5 :: Symphony No. 9 (1:06:51)
** Vienna Cycle
- CD6 :: Symphonies Nos. 1 & 2 · Music To "Egmont" (1:25:35)
- CD7 :: Symphonies Nos. 3 & 4 (1:24:48)
- CD8 :: Symphonies Nos. 5 & 7 (1:12:07)
- CD9 :: Symphonies Nos. 6 & 8 (1:12:14)
- CD10 :: Symphony No. 9 (1:10:46)
** Period Instruments
- CD11 :: Symphonies Nos. 1 & 2 (57:31)
- CD12 :: Symphonies Nos. 3 & 4 (1:06:39)
- CD13 :: Symphonies Nos. 5 & 6 (1:12:50)
- CD14 :: Symphonies Nos. 7 & 8 (1:02:49)
- CD15 :: Symphony No. 9 · Choral Fantasy (1:17:48)
** Concertos
- CD16 :: Piano Concertos 1 & 2; Piano Concerto WoO 4 (1:24:39)
- CD17 :: Piano Concertos Nos. 3 & 4 (1:09:09)
- CD18 :: Piano Concerto No. 5 · Violin Concerto (1:26:33)
- CD19 :: Violin Concerto · Violin Romances · Romance Cantabile (1:08:59)
- CD20 :: Piano Concertos 2 & 3 · Piano Rondo WoO 6 (1:16:55)
- CD21 :: Piano Concertos 3 & 4 · Choral Fantasy (1:26:23)
- CD22 :: Piano Concerto No. 5 · Piano Concerto In D (1:23:27)
- CD23 :: Triple Concerto · Violin Concerto Movement · Cadenzas (1:23:41)
* Music For The Stage
- CD24 :: Ritterballett · The Creatures Of Prometheus (1:06:06)
- CD25 :: Dances And Marches (1:21:13)
- CD26 :: Egmont · The Ruins Of Athens · Gratulations-Menuett (1:22:41)
- CD27 :: King Stephen · The Consecration Of The House · Tarpeja · Leonore Prohoska (1:16:17)
- CD28 :: Leonore (beg.) (58:46)
- CD29 :: Leonore (cont.) (1:18:06)
- CD30 :: Fidelio (beg.) (1:08:24)
- CD31 :: Fidelio (cont.) · Overture "Leonore" No. 1 · Arias, Choruses & Scenes WoO 91, 94, 97 & Unv 15 (1:23:35)
* Keyboard Music
- CD32 :: Piano Sonatas Nos. 1-3 (1:05:21)
- CD33 :: Piano Sonatas Nos. 4-6 & 8 (1:25:37)
- CD34 :: Piano Sonatas Nos. 7, 9-11 (1:18:57)
- CD35 :: Piano Sonatas Nos. 12-15 & 19 (1:22:26)
- CD36 :: Piano Sonatas Nos. 16-18 & 20 (1:20:53)
- CD37 :: Piano Sonatas Nos. 21-25 (1:23:30)
- CD38 :: Piano Sonatas Nos. 26, 27 & 29 (1:20:10)
- CD39 :: Piano Sonatas Nos. 28 & 29 (1:03:21)
- CD40 :: Piano Sonatas Nos. 30-32 (1:02:09)
- CD41 :: Named Piano Sonatas: No. 8 "Pathétique" · No. 14 "Moonlight" ·No. 17 "The Tempest" · No. 21 "Waldstein" (1:21:44)
- CD42 :: Named Piano Sonatas: No. 23 "Apassionata" · No. 26 "Les Adieux" · No. 29 "Hammerklavier" (1:08:54)
- CD43 :: Last Piano Sonatas: Nos. 30-32 (1:07:57)
- CD44 :: Bagatelles Opp. 33, 199, 126 · WoO 54, 56, 59, 60, 81 & 214 (1:06:59)
- CD45 :: Electoral Sonatas WoO 47 · Sonata Movements Op. 129, WoO 48-53 & 57 (1:16:54)
- CD46 :: Dances: Op. 89, WoO 10, 11, 13, 82-86 & 218 · Miscellaneous Works Opp. 51, 77, WoO 55, 61, 61a & 215 (1:18:11)
- CD47 :: Variations: WoO 63-66 & 68-71 (1:18:44)
- CD48 :: Variations: Opp. 34, 35, WoO 72, 73 &75-77 (1:22:18)
- CD49 :: Variations: Opp. 76, 120 & WoO 78-80 (1:24:16)
- CD50 :: Diabelli Variations · "Eroica" Variations (1:19:32)
- CD51 :: Works For Piano Duet: Opp. 6, 45, 134, WoO 67 & 74 · Other Solo Works: Opp. 39, WoO 31, 33, 64 & Hess 107 (1:25:11)
* Chamber Music
- CD52 :: Duos: Violin Sonatas Nos. 1-4 (1:13:07)
- CD53 :: Duos: Violin Sonatas 5 & 6 · Variations · Rondo · 6 German Dances (1:12:47)
- CD54 :: Duos: Violin Sonatas 7 & 9 (1:10:35)
- CD55 :: Duos: Violin Sonatas Nos. 8-10 (1:23:11)
- CD56 :: Duos: Cello Sonatas Nos. 1 & 2 · Variations Op. 66 & WoO 46 (1:05:25)
- CD57 :: Duos: Cello Sonatas Nos. 3-5 · Variations WoO 45 (1:12:15)
- CD58 :: Duos: Flute Duos Opp. 105, 107 & WoO 26 (1:11:59)
- CD59 :: Duos: Other Duos Op. 17, WoO 32, 34, 35, 43ab & 44ab (1:06:08)
- CD60 :: Trios: Piano Trios Nos. 1, 2 & 9 · Trio Movement Unv 9 (1:24:54)
- CD61 :: Trios: Piano Trios Nos. 3, 5 & 6 (1:19:57)
- CD62 :: Trios: Piano Trios Nos. 7, 8, 10 & 11 (1:16:02)
- CD63 :: Trios: Piano Trios No. 47 & Trio in E, Op. 38 (1:23:06)
- CD64 :: Trios: Chamber Music - Trios With Wind Instruments Op. 87, WoO 28 & 37 (55:48)
- CD65 :: Trios: String Trios Nos. 1 & 2 (1:06:14)
- CD66 :: Trios: String Trios Nos. 3-5 (1:13:06)
- CD67 :: Trios: String Trios WoO 9, 15 & Hess 29 · Serenade Op. 25 (49:07)
- CD68 :: Quartets: String Quartets Nos. 1-3 (1:12:26)
- CD69 :: Quartets: String Quartets Nos. 4-6 (1:13:17)
- CD70 :: Quartets: String Quartets Nos. 7 & 8 (1:01:45)
- CD71 :: Quartets: String Quartets Nos. 9 & 10 (59:00)
- CD72 :: Quartets: String Quartets Nos. 11, 13 & Gross Fuge (1:18:12)
- CD73 :: Quartets: String Quartets Nos. 12 & 14 (1:14:12)
- CD74 :: Quartets: String Quartets Nos. 15 & 16 (1:07:33)
- CD75 :: Quartets: String Quartets Nos. 12 & 15 (1:15:07)
- CD76 :: Quartets: String Quartets Nos. 13 & 14 (1:26:13)
- CD77 :: Quartets: String Quartets Nos. 16, Hess 32 & 34 · Minuet WoO 209 · Preludes & Fugues Hess 30 & 31 (1:19:15)
- CD78 :: Quartets: Piano Quartets WoO 36 · 3 Equali WoO 30 (1:03:47)
- CD79 :: Quintets: Opp. 16, 29, 137 · WoO 208, Hess 38 & Unv 7 (1:18:26)
- CD80 :: Quintets & Sextets: Opp. 4 & 104 · Wind Sextets Op. 71 & WoO 29 (1:21:06)
- CD81 :: Sextet, Septet & Octets: Sextet Op. 81b · Septet Op. 20 · Octets Op. 103 & WoO 25 (1:24:32)
* Lieders & Partsongs
- CD82 :: Lieder (I) (1:15:43)
- CD83 :: Lieder (II) (1:22:57)
- CD84 :: Lieder (III) (1:02:51)
- CD85 :: Partsongs: WoO 95, 99 & 102-106 · Canons & Musical Jokes (1:09:50)
* Folksong Settings
- CD86 :: 25 Scottish Songs Op. 108 (1:16:01)
- CD87 :: 25 Irish Songs WoO 152 (Except Nos. 20, 23 & 24) (1:13:39)
- CD88 :: 25 Irish Songs WoO 152 Nos. 20, 23 & 24 · 20 Irish Songs WoO 153 (1:06:56)
- CD89 :: 12 Irish Songs WoO 154 · Songs of Various Nationalities WoO 157 (1:14:37)
- CD90 :: 26 Welsh Songs WoO 155 (1:17:18)
- CD91 :: 25 Scottish Songs WoO 156 · 7 British Songs WoO 158b · 6 Songs Of Various Nationalities WoO 158c (1:02:15)
- CD92 :: 23 Songs of Various Nationalities WoO 158a (48:14)
* Vocal Works With Orchestra
- CD93 :: Works For Solo Voices With Orchestra: Opp. 65, 116, 118, 121b, 122; WoO 89, 90, 92, 92a, 93 (1:19:22)
- CD94 :: Cantatas: Emperor Cantatas WoO 87 & 88 (1:11:37)
- CD95 :: Cantatas & Masses: Der Glorreiche Augenblick · Meeresstille Und Glückliche Fahrt · Mass in C (1:23:28)
- CD96 :: Missa Solemnis (Period Instruments) (1:11:38)
- CD97 :: Missa Solemnis (Modern Instruments) (1:26:04)
- CD98 :: Oratorio: Christus Am Ölberge Op. 85 (56:07)
* Rarities
- CD99 :: Solo Piano & Arrangements For Piano (1:12:38)
- CD100 :: Chamber Music (1:19:51)
- CD101 :: Contrapuntal Studies & Doubtful Works (1:18:36)
* Classic Performances
- CD102 :: Symphony No. 9 / Scherchen • Symphonies Nos. 3, 5, 7 - Excerpts / Karajan · Nikisch · R. Strauss · Van Kempen • Overtures "Leonore" Nos. 2 & 3 / Busch · Klemperer (1:24:23)
- CD103 :: Symphony No. 5 · Gross Fuge · Overtures "Egmont", "Coriolan" & "Leonore" No. 3 / Fürtwangler (1:24:09)
- CD104 :: Symphonies Nos. 5 & 6 / Erich Kleiber (1:13:04)
- CD105 :: Symphony No. 9 · Overture "Egmont" / Fricsay (1:07:28)
- CD106 :: Piano Concerto No. 3 / A. Fischer · Violin Concerto / Schneiderhan (1:13:04)
- CD107 :: Piano Sonatas Nos. 8, 23, 30 & 31 / Arrau · Kempff · Schnabel (1:22:38)
- CD108 :: Piano Sonatas Nos. 11, 18, 28 & 31 / Backhaus · Haskil · Richter · Serkin (1:25:50)
- CD109 :: Piano Sonatas Nos. 4, 15 & 32 / Gulda · Michelangeli · Pogorelich (1:23:26)
- CD110 :: Cello Sonatas Nos. 3 & 5 / Fournier & Kempff · Rostropovich & Richter • Piano Trio No. 7 "Archduke" / Gilels, Kogan & Rostropovich (1:23:43)
- CD111 :: String Quartets Nos. 13 & 16 · Grosse Fugue / Busch Quartet · Hollywood String Quartet · The Lindsays (1:17:01)
- CD112 :: String Quartets Nos. 6 & 15 / Quartetto Italiano (1:14:57)
- CD113 :: Lieder / Bartoli · Pavarotti · Schreier • Fidelio / Böhm · Fricsay · Karajan · Maazel · Solti (1:25:45)
* Period Instrument Performances
- CD114 :: Piano Concertos Nos. 1 & 2 · Piano Rondo WoO 6 / Levin & Gardiner (1:15:05)
- CD115 :: Piano Concertos No. 4 / Levin & Gardiner • Violin Concerto · Romance No. 2 / Zehetmair & Brüggen (1:23:09)
- CD116 :: Piano Sonatas Nos. 8, 14 & 17 / Lubin • Lieder / Von Otter & Tan • Horn Sonata / Halstead & Levin (1:25:19)
- CD117 :: Piano Trio No. 5 "Ghost" / Queyras, Sepec & Staier • String Quartet No. 9 / Schuppanzigh-Quartett • Op. 16 / Levin & AAMCE (1:22:42)
- CD118 :: Chamber Versions Of Symphony No. 2 & Piano Concerto No. 4 / Levin • Ah! Perfido / Tilling & McCreesh (1:26:16)
