:PROPERTIES:
:ID:       313e79a3-cba7-4a99-898b-aa074cb01b40
:END:
#+TITLE: Symmetry breaking fields
#+FILETAGS: :problem:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
7. Symmetry breaking fields: Let us investigate adding a term

\begin{align*}
-\beta \mathcal{H}_{p}=h_{p} \int \mathrm{d}^{2} \mathbf{x} \cos (p \theta(\mathbf{x}))
\end{align*}

to the XY model. There are a number of possible causes for such a symmetry breaking field: $p=1$ is the usual "magnetic field", $p=2,3,4$, and 6 could be due to couplings to an underlying lattice of rectangular, hexagonal, square, or triangular symmetry respectively. As $h_{p} \rightarrow \infty$, the spin becomes discrete, taking one of $p$ possible values, and the model becomes equivalent to the previously discussed clock models.

(a) Assume that we are in the low-temperature phase so that vortices are absent, i.e. the vortex fugacity $y$ is zero (in the RG sense). In this case, we can ignore the angular nature of $\theta$ and replace it with a scalar field $\phi$, leading to the partition function

\begin{align*}
Z=\int D \phi(x) \exp \left\{-\int \mathrm{d}^{2} \mathbf{x}\left
[
\frac{K}{2}(\nabla \phi)^{2}+h_{p} \cos (p \phi)\right]\right\}
\end{align*}

This is known as the sine-Gordon model, and is equivalent to the roughening transition of a previous problem. Use similar methods to obtain the recursion relations for $h_{p}$ and $K$.

(b) Show that once vortices are included, the recursion relations are

\begin{align*}
\begin{aligned}
\frac{\mathrm{d} h_{p}}{\mathrm{~d} \ell} & =\left(2-\frac{p^{2}}{4 \pi K}\right) h_{p} \\
\frac{\mathrm{d} K^{-1}}{\mathrm{~d} \ell} & =-\frac{\pi p^{2} h_{p}^{2}}{2} K^{-2}+4 \pi^{3} y^{2} \\
\frac{\mathrm{d} y}{\mathrm{~d} \ell} & =(2-\pi K) y
\end{aligned}
\end{align*}

(c) Show that the above RG equations are only valid for $\frac{8 \pi}{p^{2}}<K^{-1}<\frac{\pi}{2}$, and thus only apply for $p>4$. Sketch possible phase diagrams for $p>4$ and $p<4$. In fact $p=4$ is rather special as there is a marginal operator $h_{4}$, and the transition to the four-fold phase (cubic anisotropy) has continuously varying critical exponents!

* Solution

* Related Concepts
