:PROPERTIES:
:ID:       07317a1a-4c89-4bb7-9bb5-66b92e15c0de
:END:
#+TITLE: Fluctuations around a tricritical point
#+FILETAGS: :problem:critical:
#+SETUPFILE: ../../setupfile.org

* Problem Statement

4. Fluctuations around a tricritical point: As shown in a previous problem, the Hamiltonian

\begin{align*}
\beta \mathcal{H}=\int \mathrm{d}^{d} \mathbf{x}\left
[
\frac{K}{2}(\nabla m)^{2}+\frac{t}{2} m^{2}+u m^{4}+v m^{6}\right]
\end{align*}

with \(u=0\) and \(v>0\) describes a tricritical point.

(a) Calculate the heat capacity singularity as \(t \rightarrow 0\) by the saddle point approximation.

(b) Include both longitudinal and transverse fluctuations by setting

\begin{align*}
\vec{m}(\mathbf{x})=\left(\bar{m}+\phi_{\ell}(\mathbf{x})\right) \hat{e}_{\ell}+\sum_{\alpha=2}^{n} \phi_{t}^{\alpha}(\mathbf{x}) \hat{e}_{\alpha}
\end{align*}

and expanding \(\beta \mathcal{H}\) to quadratic order in \(\phi\).

(c) Calculate the longitudinal and transverse correlation functions.

(d) Compute the first correction to the saddle point free energy from fluctuations.

(e) Find the fluctuation correction to the heat capacity.

(f) By comparing the results from parts (a) and (e) for \(t<0\) obtain a Ginzburg criterion, and the upper critical dimension for validity of mean-field theory at a tricritical point.
(g) A generalized multicritical point is described by replacing the term \(v m^{6}\) with \(u_{2 n} m^{2 n}\). Use simple power counting to find the upper critical dimension of this multicritical point.

* Solution

* Related Concepts

