:PROPERTIES:
:ID:       3b1841a7-ac29-45d7-868b-efddb08005de
:END:
#+TITLE: Floating-point arithmetic
#+FILETAGS: :concept:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org

In computing, floating-point arithmetic (FP) is arithmetic that represents subsets of real numbers using an integer with a fixed precision, called the significand, scaled by an integer exponent of a fixed base. Numbers of this form are called floating-point numbers. 

#+NAME: Floating-point number
#+BEGIN_EXAMPLE
12.345 is a floating-point number. Its base is 10, precision is 5, significand is 12345, and exponent is 1.
#+END_EXAMPLE

#+NAME: Significand
#+begin_definition latex
To find the significand of a floating-point number (in base 10):
1) shift the radix point so that all significant digits of the number are to the left of the radix point
2) get rid of the radix point and everything to its right
#+end_definition

In the example above, the exponent is 1 because the [[id:ec67185a-ec8e-45ee-9b67-51c040970e32][scientific notation]] convention is assumed. In scientific notation (base-10) 12.345 is represented as \(1.2345 \times 10^{1}\). Therefore, given the /significand/ \( s \), the /precision/ \( p \) is the /precision/ (), \( b \) is the /base/, and \( e \) is the /exponent/.

\[
\frac{s}{b^{(p-1)}} \times b^{e}
\]

{\displaystyle 12.345=\!\underbrace {12345} _{\text{significand}}\!\times \!\underbrace {10} _{\text{base}}\!\!\!\!\!\!\!\overbrace {{}^{-3}} ^{\text{exponent}}}

However, unlike 12.345, 12.3456 is not a floating-point number in base ten with five digits of precision—it needs six digits of precision; the nearest floating-point number with only five digits is 12.346. In practice, most floating-point systems use base two, though base ten (decimal floating point) is also common.

Floating-point arithmetic operations, such as addition and division, approximate the corresponding real number arithmetic operations by rounding any result that is not a floating-point number itself to a nearby floating-point number.[1]: 22 [2]: 10  For example, in a floating-point arithmetic with five base-ten digits of precision, the sum 12.345 + 1.0001 = 13.3451 might be rounded to 13.345.

The term floating point refers to the fact that the number's radix point can "float" anywhere to the left, right, or between the significant digits of the number. This position is indicated by the exponent, so floating point can be considered a form of scientific notation.

A floating-point system can be used to represent, with a fixed number of digits, numbers of very different orders of magnitude — such as the number of meters between galaxies or between protons in an atom. For this reason, floating-point arithmetic is often used to allow very small and very large real numbers that require fast processing times. The result of this dynamic range is that the numbers that can be represented are not uniformly spaced; the difference between two consecutive representable numbers varies with their exponent.[3]
Single-precision floating-point numbers on a number line: the green lines mark representable values.
Augmented version above showing both signs of representable values

Over the years, a variety of floating-point representations have been used in computers. In 1985, the IEEE 754 Standard for Floating-Point Arithmetic was established, and since the 1990s, the most commonly encountered representations are those defined by the IEEE.

The speed of floating-point operations, commonly measured in terms of FLOPS, is an important characteristic of a computer system, especially for applications that involve intensive mathematical calculations.

A floating-point unit (FPU, colloquially a math coprocessor) is a part of a computer system specially designed to carry out operations on floating-point numbers. 
