:PROPERTIES:
:ID:       bc954e6a-362d-4efb-8060-9fe0f3cc3d42
:END:
#+TITLE: Irreversibility
#+FILETAGS: :literature: :SPOP:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org

The second law is an empirical formulation of the vast number of everyday observations that support the existence of an arrow of time. Reconciling the reversibility of laws of physics governing the microscopic domain with the observed irreversibility of macroscopic phenomena is a fundamental problem. Of course, not all microscopic laws of physics are reversible: weak nuclear interactions violate [[id:63b40e84-f67e-4620-a2fd-ca7405f31000][time reversal symmetry]], and the collapse of the quantum [[id:94b5c991-5475-42ea-b225-2e4d988ba72a][Wave function]] in the act of observation is irreversible. The former interactions in fact do not play any significant role in everyday observations that lead to the second law. The irreversible collapse of the wave function may itself be an artifact of treating macroscopic observers and microscopic observables distinctly /(the time-dependent Schrödinger equation is fully time reversible. If it is possible to write a complicated wave function that includes the observing apparatus - possibly the whole Universe, it is hard to see how any irreversibility may occur)/. There are proponents of the view that the reversibility of the currently accepted microscopic equations of motion (classical or quantum) is indicative of their inadequacy. However, the advent of powerful computers has made it possible to simulate the evolution of collections of large numbers of particles, governed by classical, reversible equations of motion. Although simulations are currently limited to relatively small numbers of particles \((10^6)\), they do exhibit the irreversible macroscopic behaviors similar to those observed in nature (typically involving \(10^{23}\) particles). For example, particles initially occupying one half of a box proceed to irreversibly, and uniformly, occupy the whole box. (This has nothing to do with limitations of computational accuracy; the same macroscopic irreversibility is observed in exactly reversible integer-based simulations, such as with cellular automata.) Thus the origin of the observed irreversibilities should be sought in the classical evolution of large collections of particles.

[[id:1d6a703e-1e34-4c07-8d66-c80b6b4bb1ef][The Boltzmann equation]] is the first formula we have encountered that is clearly not time reversible, as indicated by [[id:4bb6b4c9-8592-4b78-bf5a-57b0a99a8ece][The H-theorem]] (\( \mathrm{D}_t \mathrm{H} \leq 0 \)). We can thus ask the question of how we obtained this result from the Hamiltonian equations of motion. The key to this, of course, resides in the physically motivated approximations used to obtain the Boltzmann equation

\begin{align*}
\big[\partial_t - \partial_{\vec{q}_1} U \cdot \partial_{\vec{p}_1} &+ (\vec{p}_1/m) \cdot \partial_{\vec{q}_1}\big]\, f_1 \\
&= -\int \mathrm{d}^3 \vec{p}_2\,\mathrm{d}^2 \Omega \, \lvert \mathrm{D}_\Omega \sigma \rvert \lvert \vec{v}_1 - \vec{v}_2 \rvert\,\big[f_1(\vec{p}_1,\,\vec{q}_1,\,t)\,f_1(\vec{p}_2,\,\vec{q}_1,\,t) - f_1(\vec{p}_1^{\thinspace \prime},\,\vec{q}_1,\,t)\,f_1(\vec{p}_2^{\thinspace \prime},\,\vec{q}_1,\,t)\big]. \tag{1}
\end{align*}

The first steps of the approximation were dropping the three-body collision term on the right-hand side of the second of the first two equations of the [[id:0f74dbc6-6e75-44b9-8c93-eebb92805033][The BBGKY hierarchy]] and the implicit coarse graining of the resolution in the spatial and temporal scales. Neither of these steps explicitly violates time reversal symmetry. The next step in getting to the Boltzmann equation is to replace the two-body density \(f_2(\text{b})\), /evaluated before the collision/, with the product of two one-body densities according to

\[
f_2(\vec{p}_1,\,\vec{q}_1,\,\vec{p}_2,\,\vec{q}_2,\,t) \longrightarrow f_1(\vec{p}_1,\,\vec{q}_1,\,t) f_1(\vec{p}_2,\,\vec{q}_2,\,t), \qquad |\vec{q}_2 - \vec{q}_1| \gg d \tag{2}
\]

*This treats the two-body densities before and after the collision differently.* We could alternatively have expressed 

\begin{align*}
\mathrm{D}_t f_1 \rvert_{\text{coll.}} = \int \mathrm{d}^3\vec{p}_2\,\mathrm{d}^2 \Omega\,\lvert \mathrm{D}_{\Omega} \sigma \rvert\,\lvert \vec{v}_1 - \vec{v}_2 \rvert \big[ f_2(\vec{p}_1^{\thinspace \prime},\,\vec{q}_1,\,\vec{p}_2^{\thinspace \prime},\,\vec{b},\,-;\,t) - f_2(\vec{p}_1,\,\vec{q}_1,\,\vec{p}_2,\,\vec{b},\,-;\,t) \big]. \tag{3}
\end{align*}

in terms of the two-body densities \(f_2(+)\) /evaluated after the collision/. Replacing \(f_2\) with the product of two one-particle densities would then lead to the opposite conclusion, with \(\mathrm{dH} / \mathrm{d} t \geq 0\)! For a system in equilibrium, it is hard to justify one choice over the other. However, once the system is out of equilibrium, the coordinates after the collision are more likely to be correlated, and hence the substitution of (2) for \(f_2\) does not make sense. Time reversal symmetry implies that there should also be subtle correlations in \(f_2(-)\) that are ignored in the so-called assumption of molecular chaos. *Thus, it is the assumption of molecular chaos that violates time-reversal symmetry.* 

While the assumption of molecular chaos before (but not after) collisions is the key to the irreversibility of the Boltzmann equation, the resulting loss of information is best justified in terms of the coarse graining of space and time: the [[id:a2da6b4b-5ecc-4ad5-9268-33aeab1643f6][Liouville's equation]] and its descendants ([[id:0f74dbc6-6e75-44b9-8c93-eebb92805033][The BBBGKY hierarchy]]) contain precise information about the evolution of a pure state. This information, however, is inevitably transported to shorter scales. A useful image is that of mixing two immiscible fluids. While the two fluids remain distinct at each point, the transitions in space from one to the next occur at finer resolution on subsequent mixing. At some point, a finite resolution in any measuring apparatus will prevent keeping track of the two components. In the Boltzmann equation, the precise information of the pure state is lost at the scale of collisions. The resulting one-body density, the marginal of the [[id:21d62749-69ab-4e25-b366-eb6ff17a2f09][phase space density]], only describes space and time resolutions longer than those of a two-body collision, becoming more and more probabilistic as further information is lost and entropy is gained.
