:PROPERTIES:
:ID:       4bb6b4c9-8592-4b78-bf5a-57b0a99a8ece
:END:
#+TITLE: The H-theorem
#+FILETAGS: :literature: :SPOP:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org

The steady state solutions for the full [[id:21d62749-69ab-4e25-b366-eb6ff17a2f09][phase space density]] \(\rho_N\) are not attractors of generic non-equilibrium densities because of [[id:63b40e84-f67e-4620-a2fd-ca7405f31000][Time reversal symmetry]]. The exact marginal \(\rho_1\) must necessarily reflect this property of \(\rho_N\) as well. However, an approximate \(\rho_1\) need not necessarily have the property of time reversal symmetry. The *H-theorem* states that a marginal \(\rho_1\), governed by [[id:1d6a703e-1e34-4c07-8d66-c80b6b4bb1ef][the Boltzmann equation]], does in fact non-reversibly approach an equilibrium form.

#+NAME: The H-theorem
#+begin_theorem latex
Let \( \mathrm{H}(t) \equiv \int \mathrm{d}^3 \vec{p} \, \mathrm{d}^3 \vec{q} \, f_1(\vec{p},\, \vec{q},\,t) \ln f_1(\vec{p},\,\vec{q},\,t) \). If \(f_1(\vec{p},\,\vec{q},\,t)\) satisfies the Boltzmann equation, then \(\mathrm{D}_t \mathrm{H} \leq 0\).
#+end_theorem

The function \(\mathrm{H}(t)\) is related to the [[id:dd01339d-fd5c-42dc-8a95-246f3f37fcb2][information content]] of the one-particle PDF. Up to an overall constant, the information content of \(\rho_1=f_1 / N\) is given by \(I [\,\rho_1\,] = \langle \ln \rho_1 \rangle\), which is clearly similar to \(\mathrm{H}(t)\). Also see [[id:bc954e6a-362d-4efb-8060-9fe0f3cc3d42][Irreversibility]].

* Proof
The time derivative of \(\mathrm{H}\) is

\begin{align*}
\mathrm{D}_t \mathrm{H} = \int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 \partial_t f_1 (\ln f_1+1) = \int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 \ln f_1 \partial_t f_1,
\end{align*}

since \(\int \mathrm{d} V_1 f_1=N \int \mathrm{d} \Gamma \rho=N\) is time-independent. Using [[id:1d6a703e-1e34-4c07-8d66-c80b6b4bb1ef][the Boltzmann equation]], we obtain

\begin{align*}
\mathrm{D}_t \mathrm{H} = & \int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 \ln f_1 \big (\partial_{\vec{q}_1} U \cdot \partial_{\vec{p}_1} f_1-(\vec{p}_1/m) \cdot \partial_{\vec{q}_1} f_1 \big ) \\
&\quad -\int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 \mathrm{~d}^3 \vec{p}_2 \mathrm{~d}^2 \vec{b} |\vec{v}_1-\vec{v}_2| \big [f_1(\vec{p}_1, \vec{q}_1) f_1(\vec{p}_2, \vec{q}_1) - f_1(\vec{p}_1^{\prime}, \vec{q}_1) f_1(\vec{p}_2^{\prime}, \vec{q}_1) \big ] \ln f_1(\vec{p}_1, \vec{q}_1)
\end{align*}

The streaming terms in the above expression vanish:

\begin{align*}
\int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 \ln f_1 \partial_{\vec{q}_1} U \cdot \partial_{\vec{p}_1} f_1 & =-\int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 f_1 \partial_{\vec{q}_1} U \cdot \frac{1}{f_1} \partial_{\vec{p}_1} f_1 =\int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 f_1 \partial_{\vec{p}_1} \cdot \partial_{\vec{q}_1} U=0,
\end{align*}

and

\begin{align*}
\int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 \ln f_1 \frac{\vec{p}_1}{m} \cdot \partial_{\vec{q}_1} f_1=-\int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 f_1 \frac{\vec{p}_1}{m} \cdot \frac{1}{f_1} \partial_{\vec{q}_1} f_1=\int \mathrm{d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{q}_1 f_1 \partial_{\vec{q}_1} \cdot \frac{\vec{p}_1}{m}=0 .
\end{align*}

Therefore


\begin{align*}
\mathrm{D}_t \mathrm{H} = -\int \mathrm{~d}^3 \vec{q}_1 \mathrm{d}^3 \vec{p}_1 &\mathrm{~d}^3 \vec{p}_2 \mathrm{~d}^2 \vec{b} |\vec{v}_1-\vec{v}_2| \\
&\times \big [f_1(\vec{p}_1, \vec{q}, t) f_1(\vec{p}_2, \vec{q}, t) - f_1(\vec{p}_1^{\prime}, \vec{q}, t) f_1(\vec{p}_2^{\prime}, \vec{q}, t) \big ] \ln f_1(\vec{p}_1, \vec{q}, t), \tag{1}
\end{align*}

Relabelling indices \( 1 \to 2 \) and \( 2 \to 1 \) leaves the integral invariant. Averaging the resulting expression and (1) yields

\begin{align*}
\mathrm{D}_t \mathrm{H} = -\frac{1}{2} \int \mathrm{d}^3 \vec{q} &\mathrm{~d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{p}_2 \mathrm{~d}^2 \vec{b} |\vec{v}_1-\vec{v}_2| \\
&\times \big [f_1(\vec{p}_1, \vec{q}, t) f_1(\vec{p}_2, \vec{q}, t) -f_1(\vec{p}_1{ }^{\prime}, \vec{q}, t) f_1(\vec{p}_2{ }^{\prime}, \vec{q}, t) \big ] \ln \bigl(f_1(\vec{p}_1, \vec{q}, t) f_1(\vec{p}_2, \vec{q}, t)\bigr). \tag{2}
\end{align*}

Next, we [[id:9b149a74-f823-4dc5-8aa3-cba9d7879fa0][change coordinates]] \((\vec{p}_1, \vec{p}_2, \vec{b}) \to (\vec{p}_1{ }^{\prime}, \vec{p}_2{ }^{\prime}, \vec{b}^{\prime})\). The explicit functional forms describing this transformation are complicated because of the dependence of the solid angle \(\hat{\Omega}\) in

\[
\left\{\begin{array}{l}
\vec{p}_1^{\thinspace \prime} = 2^{-1} \, \big(\vec{p}_1 + \vec{p}_2 + |\vec{p}_1 - \vec{p}_2| \, \hat{\Omega}(\vec{b})\big), \\
\vec{p}_2^{\thinspace \prime} = 2^{-1} \, \big(\vec{p}_1 + \vec{p}_2 - |\vec{p}_1 - \vec{p}_2| \, \hat{\Omega}(\vec{b})\big).
\end{array}\right. \tag{3}
\]

on \(\vec{b}\) and \(|\vec{p}_2-\vec{p}_1|\) (see [[id:262c680c-027d-40b7-9087-8f245fd0b294][collision integral in the Boltzmann equation]]). However, time reversal symmetry guarantees that the [[id:dad8b579-a898-43e8-a65c-78b8848b00fa][Jacobian]] of the transformation is unity. In terms of the new coordinates

\begin{align*}
\mathrm{D}_t \mathrm{H} = -\frac{1}{2} \int \mathrm{d}^3 \vec{q} &\mathrm{~d}^3 \vec{p}_1{}^{\prime} \mathrm{~d}^3 \vec{p}_2{}^{\prime} \mathrm{~d}^2 \vec{b} |\vec{v}_1-\vec{v}_2| \\
&\times \big [f_1(\vec{p}_1 (\vec{p}_1{ }^{\prime}, \vec{p}_2{ }^{\prime}, \vec{b}^{\prime}),\, \vec{q},\,t) f_1(\vec{p}_2 (\vec{p}_1{ }^{\prime},\vec{p}_2{ }^{\prime}, \vec{b}^{\prime}),\,\vec{q},\, t) - f_1(\vec{p}_1{ }^{\prime}, \vec{q}, t) f_1(\vec{p}_2{ }^{\prime}, \vec{q}, t) \big ] \\
&\times \ln \bigl(f_1(\vec{p}_1 (\vec{p}_1{ }^{\prime}, \vec{p}_2{ }^{\prime}, \vec{b}^{\prime}),\, \vec{q},\,t) f_1(\vec{p}_2 (\vec{p}_1{ }^{\prime}, \vec{p}_2{ }^{\prime}, \vec{b}^{\prime}),\,\vec{q},\,t)\bigr). \tag{4}
\end{align*}

Note that the collisions are elastic so \(|\vec{v}_1- \vec{v}_2|= |\vec{v}_1{ }^{\prime}-\vec{v}_2{ }^{\prime}|\) ([[id:e70c7b74-1486-414a-a074-ad58c8578e1e][conservation of momentum]]). Relabelling \( \vec{p} \to \vec{p}{}^{\prime} \) and \( \vec{p}{}^{\prime} \to \vec{p} \) leaves the integral invariant since the functional dependence of \((\vec{p}_1, \vec{p}_2, \vec{b})\) on \((\vec{p}_1{ }^{\prime}, \vec{p}_2{ }^{\prime}, \vec{b}^{\prime})\) is exactly the same as its inverse. Averaging the resulting expression and (4) yields

\begin{align*}
\mathrm{D}_t \mathrm{H} = -\frac{1}{2} \int \mathrm{d}^3 \vec{q} &\mathrm{~d}^3 \vec{p}_1{}^{\prime} \mathrm{~d}^3 \vec{p}_2{}^{\prime} \mathrm{~d}^2 \vec{b} |\vec{v}_1-\vec{v}_2| \\
&\times \big [f_1(\vec{p}_1{ }^{\prime}, \vec{q}, t) f_1(\vec{p}_2{ }^{\prime}, \vec{q}, t) - f_1(\vec{p}_1,\, \vec{q},\,t) f_1(\vec{p}_2,\,\vec{q},\, t) \big ] \ln \bigl(f_1(\vec{p}_1{}^{\prime},\, \vec{q},\,t) f_1(\vec{p}_2{}^{\prime},\,\vec{q},\,t)\bigr). \tag{5}
\end{align*}

Averaging Eqs. (2) and (5) results in

\begin{align*}
\mathrm{D}_t \mathrm{H} = -\frac{1}{4} \int \mathrm{d}^3 \vec{q} \mathrm{~d}^3 \vec{p}_1 \mathrm{~d}^3 \vec{p}_2 & \mathrm{~d}^2 \vec{b} |\vec{v}_1-\vec{v}_2| \\
&\times 
\big [f_1(\vec{p}_1) f_1(\vec{p}_2)-f_1(\vec{p}_1{ }^{\prime}) f_1(\vec{p}_2{ }^{\prime}) \big ] 
\big[\ln (f_1(\vec{p}_1) f_1(\vec{p}_2))-\ln (f_1(\vec{p}_1{ }^{\prime}) f_1(\vec{p}_2{ }^{\prime})) \big].
\end{align*}

If \(f_1(\vec{p}_1) f_1(\vec{p}_2)>\) \(f_1(\vec{p}_1{ }^{\prime}) f_1(\vec{p}_2{ }^{\prime})\), both terms in square brackets are positive, while both are negative if \(f_1(\vec{p}_1) f_1(\vec{p}_2)<f_1(\vec{p}_1^{\prime}) f_1(\vec{p}_2{ }^{\prime})\). In either case, their product is positive. The positivity of the integrand above establishes the validity of the H-theorem, \( \mathrm{D}_t \mathrm{H} \leq 0 \).