:PROPERTIES:
:ID:       9335e759-e3b3-4f74-b0f0-875441acf012
:END:
#+TITLE: Cayley trees
#+FILETAGS: :problem:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
14. Cayley trees: Consider a hierarchical lattice in which each site at one level is connected to z sites at the level below. Thus the n-th level of the tree has z^{n} sites.
(a) For z=2, obtain a recursion relation for the probability P_{n}(p) that the top site of a tree of n levels is connected to some site at the bottom level.
(b) Find the limiting behavior of P(p) for infinitely many levels, and give the exponent \beta for this tree.
(c) In a mean-field approximation, P(p) for a lattice of coordination number z is calculated self-consistently, in a manner similar to the above. Give the mean-field estimates for p_{c} and the exponent \beta.
(d) The one-dimensional chain corresponds to z=1. Find the probability that endpoints of an open chain of N+1 sites are connected, and hence deduce the correlation length \xi.

* Solution

* Related Concepts
