:PROPERTIES:
:ID:       83b25f6f-7ad3-48ba-91d6-a6b9ab5ad4b8
:CUSTOM_ID: 8/2c
:END:
#+TITLE: Matrix models - Part (c): Small fluctuations and expansion
#+FILETAGS: :problem:part:spof:
#+SETUPFILE: ~/.config/emacs/setup/setupfile.org

* Problem Statement

Consider small fluctuations about the ordered state $M(\mathbf{x})=I$. Show that $\sigma$ can be expanded in powers of $\pi$ as

\begin{align*}
\sigma=I-\frac{1}{2} \pi \pi^{T}+\cdots
\end{align*}

Use the orthogonality constraint to integrate out $\sigma$, and obtain an expression for $\beta H$ to fourth order in $\pi$. Note that there are two distinct types of fourth order terms. Do not include terms generated by the argument of the delta function. As shown for the nonlinear $\sigma$ model in the text, these terms do not affect the results at lowest order.

* Context

This is part (c) of problem 8-2 on Matrix models from Kardar's Statistical Physics of Fields.

* Navigation

- [[8/2][Main Problem: Matrix models]]
- [[8/2b][Previous: Part (b) - Symmetric and anti-symmetric matrices]]
- [[8/2d][Next: Part (d) - Goldstone modes]]

* Solution

* Related Concepts