:PROPERTIES:
:ID:       0aa79c47-ac7c-433e-bf69-767f50cc30f5
:CUSTOM_ID: 5/1
:END:
#+TITLE: Longitudinal susceptibility
#+FILETAGS: :problem:main:spof:
#+SETUPFILE: ../../setupfile.org

1. Longitudinal susceptibility: While there is no reason for the longitudinal susceptibility to diverge at the mean-field level, it in fact does so due to fluctuations in dimensions \(d<4\). This problem is intended to show you the origin of this divergence in perturbation theory. There are actually a number of subtleties in this calculation
which you are instructed to ignore at various steps. You may want to think about why they are justified.

Consider the Landau-Ginzburg Hamiltonian:

\begin{align*}
\beta \mathcal{H}=\int \mathrm{d}^{d} \mathbf{x}\left
[
\frac{K}{2}(\nabla \vec{m})^{2}+\frac{t}{2} \vec{m}^{2}+u\left(\vec{m}^{2}\right)^{2}\right]
\end{align*}

describing an \(n\)-component magnetization vector \(\vec{m}(\mathbf{x})\), in the ordered phase for \(t<0\).

(a) Let \(\vec{m}(\mathbf{x})=\left(\bar{m}+\phi_{\ell}(\mathbf{x})\right) \hat{e}_{\ell}+\vec{\phi}_{t}(\mathbf{x}) \hat{e}_{t}\), and expand \(\beta \mathcal{H}\) keeping all terms in the expansion.

(b) Regard the quadratic terms in \(\phi_{\ell}\) and \(\vec{\phi}_{t}\) as an unperturbed Hamiltonian \(\beta \mathcal{H}_{0}\), and the lowest order term coupling \(\phi_{\ell}\) and \(\vec{\phi}_{t}\) as a perturbation \(U\); i.e.

\begin{align*}
U=4 u \bar{m} \int \mathrm{d}^{d} \mathbf{x} \phi_{\ell}(\mathbf{x}) \vec{\phi}_{t}(\mathbf{x})^{2}
\end{align*}

Write \(U\) in Fourier space in terms of \(\phi_{\ell}(\mathbf{q})\) and \(\vec{\phi}_{t}(\mathbf{q})\).

(c) Calculate the Gaussian (bare) expectation values \(\left\langle\phi_{\ell}(\mathbf{q}) \phi_{\ell}\left(\mathbf{q}^{\prime}\right)\right\rangle_{0}\) and \(\left\langle\phi_{t, \alpha}(\mathbf{q}) \phi_{t, \beta}\left(\mathbf{q}^{\prime}\right)\right\rangle_{0}\), and the corresponding momentum dependent susceptibilities \(\chi_{\ell}(\mathbf{q})_{0}\) and \(\chi_{t}(\mathbf{q})_{0}\).

(d) Calculate \(\left\langle\vec{\phi}_{t}\left(\mathbf{q}_{1}\right) \cdot \vec{\phi}_{t}\left(\mathbf{q}_{2}\right) \vec{\phi}_{t}\left(\mathbf{q}_{1}^{\prime}\right) \cdot \vec{\phi}_{t}\left(\mathbf{q}_{2}^{\prime}\right)\right\rangle_{0}\) using Wick's theorem. (Don't forget that \(\vec{\phi}_{t}\) is an \((n-1)\) component vector.)

(e) Write down the expression for \(\left\langle\phi_{\ell}(\mathbf{q}) \phi_{\ell}\left(\mathbf{q}^{\prime}\right)\right\rangle\) to second order in the perturbation \(U\). Note that since \(U\) is odd in \(\phi_{\ell}\), only two terms at the second order are non-zero.

(f) Using the form of \(U\) in Fourier space, write the correction term as a product of two four-point expectation values similar to those of part (d). Note that only connected terms for the longitudinal four-point function should be included.

(g) Ignore the disconnected term obtained in (d) (i.e. the part proportional to ( \(n-\) \(1\)^{2}\) ), and write down the expression for \(\chi_{\ell}(\mathbf{q})\) in second order perturbation theory.

(h) Show that for \(d<4\), the correction term diverges as \(q^{d-4}\) for \(q \rightarrow 0\), implying an infinite longitudinal susceptibility.

* Navigation
- **First Part**: [[id:c9c8d962-6018-4959-8e66-a9b516013cca][Hamiltonian Expansion]]

* Solution

* Related Concepts

