:PROPERTIES:
:ID:       20cd0d61-7d2f-445a-b4b1-41599831b064
:END:
#+TITLE: Roughening and duality
#+FILETAGS: :problem:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
4. Roughening and duality: Consider a discretized version of the Hamiltonian in the previous problem, in which for each site $i$ of a square lattice there is an integer valued height $h_{i}$. The Hamiltonian is

\begin{align*}
\beta \mathcal{H}=\frac{K}{2} \sum_{\langle i, j\rangle}\left|h_{i}-h_{j}\right|^{\infty}
\end{align*}

where the " \infty " power means that there is no energy cost for $\Delta h=0$; an energy cost of $K / 2$ for $\Delta h= \pm 1$; and $\Delta h= \pm 2$ or higher are not allowed for neighboring sites. (This is known as the restricted solid on solid (RSOS) model.)

(a) Construct the dual model either diagrammatically, or by following these steps:

(i) Change from the $N$ site variables $h_{i}$, to the $2 N$ bond variables $n_{i j}=h_{i}-h_{j}$. Show that the sum of $n_{i j}$ around any plaquette is constrained to be zero.

(ii) Impose the constraints by using the identity $\int_{0}^{2 \pi} \mathrm{d} \theta \mathrm{e}^{\mathrm{i} \theta n} / 2 \pi=\delta_{n, 0}$, for integer $n$.

(iii) After imposing the constraints, you can sum freely over the bond variables $n_{i j}$ to obtain a dual interaction $\tilde{v}\left(\theta_{i}-\theta_{j}\right)$ between dual variables $\theta_{i}$ on neighboring plaquettes.
(b) Show that for large $K$, the dual problem is just the XY model. Is this conclusion consistent with the renormalization group results of the previous problem? (Also note the connection with the loop model considered in the problems of the previous chapter.)

(c) Does the one dimensional version of this Hamiltonian, i.e. a 2d interface with

\begin{align*}
-\beta \mathcal{H}=-\frac{K}{2} \sum_{i}\left|h_{i}-h_{i+1}\right|^{\infty}
\end{align*}

have a roughening transition?

* Solution

* Related Concepts
