:PROPERTIES:
:ID:       91fdba71-8f1a-425e-bc65-86ff42cc6b47
:CUSTOM_ID: 7/16
:END:
#+TITLE: Position-space renormalization group
#+FILETAGS: :problem:main:spof:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
16. Position-space renormalization group (PSRG): In the Migdal-Kadanoff approximation, a decimation is performed after bonds are moved to connect the remaining sites in a one-dimensional geometry. For a PSRG rescaling factor b on a d-dimensional hypercubic lattice, the retained sites are connected by b^{d-1} strands in parallel, each strand having b bonds in series. This scheme is naturally exact for d=1, and becomes progressively worse in higher dimensions.
(a) Apply the above scheme to b=d=2, and compare the resulting estimates of p_{c} and y_{t}=1 / \nu to the exact values for the square lattice ( p_{c}=1 / 2 and y_{t}=3 / 4 ).
(b) Find the limiting values of p_{c} and y_{t} for large d. (It can be shown that \nu=1 / 2 exactly, above an upper critical dimension d_{u}=6.)
(c) In an alternative PSRG scheme, first b^{d-1} bonds are connected in parallel, the resulting groups are then joined in series. Repeat the above calculations with this scheme.

* Navigation
- **First Part**: [[id:4730dc56-c8eb-4a25-a0a1-33630e74fc16][Migdal-Kadanoff Scheme]]

* Solution

* Related Concepts
