:PROPERTIES:
:ID:       c0e2e030-7b97-4849-a4f6-3162e4f9f3cd
:CUSTOM_ID: 1-5
:END:
#+TITLE: Critical behavior of a gas
#+FILETAGS: :problem:main:spof:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
Critical behavior of a gas: The pressure \(P\) of a gas is related to its density \(n=N / V\), and temperature \(T\) by the truncated expansion
\begin{align*}
P=k_{\mathrm{B}} T n-\frac{b}{2} n^{2}+\frac{c}{6} n^{3}
\end{align*}
where \(b\) and \(c\) are assumed to be positive, temperature independent constants.

(a) Locate the critical temperature \(T_{c}\) below which this equation must be invalid, and the corresponding density \(n_{c}\) and pressure \(P_{c}\) of the critical point. Hence find the ratio \(k_{\mathrm{B}} T_{c} n_{c} / P_{c}\).

(b) Calculate the isothermal compressibility \(\kappa_{T}=-\left.\frac{1}{V} \frac{\partial V}{\partial P}\right|_{T}\), and sketch its behavior as a function of \(T\) for \(n=n_{c}\).

(c) On the critical isotherm give an expression for \(\left(P-P_{c}\right)\) as a function of \(\left(n-n_{c}\right)\).
(d) The instability in the isotherms for \(T<T_{c}\) is avoided by phase separation into a liquid of density \(n_{+}\)and gas of density \(n_{-}\). For temperatures close to \(T_{c}\), these densities behave as \(n_{ \pm} \approx n_{c}(1 \pm \delta)\). Using a Maxwell construction, or otherwise, find an implicit equation for \(\delta(T)\), and indicate its behavior for \(\left(T_{c}-T\right) \rightarrow 0\). (Hint: Along an isotherm, variations of chemical potential obey \(\mathrm{d} \mu=\mathrm{d} P / n\).)

(e) Now consider a gas obeying Dieterici's equation of state:
\begin{align*}
P(v-b)=k_{\mathrm{B}} T \exp \left(-\frac{a}{k_{\mathrm{B}} T v}\right)
\end{align*}
where \(v=V / N\). Find the ratio \(P v / k_{\mathrm{B}} T\) at its critical point.

(f) Calculate the isothermal compressibility \(\kappa_{T}\) for \(v=v_{c}\) as a function of \(T-T_{c}\) for the Dieterici gas.

(g) On the Dieterici critical isotherm expand the pressure to the lowest non-zero order in \(\left(v-v_{c}\right)\).

* Navigation
- **First Part**: [[id:10537825-5563-4f3b-a1b2-0325ecac73bd][Critical Point Properties]]

* Solution

* Related Concepts
