:PROPERTIES:
:ID:       7ad7b251-321e-49b7-ac9d-30fc6ab101b0
:CUSTOM_ID: 7-2
:END:
#+TITLE: Potts model I
#+FILETAGS: :problem:main:spof:
#+SETUPFILE: ../../setupfile.org

* Problem Statement
2. Potts model I: Consider Potts spins s_{i}=(1,2, \cdots, q), interacting via the Hamiltonian -\beta \mathcal{H}=K \sum_{\langle i j\rangle} \delta_{s_{i}, s_{j}}.

(a) To treat this problem graphically at high temperatures, the Boltzmann weight for each bond is written as

\begin{align*}
\exp \left(K \delta_{s_{i}, s_{j}\right)=C(K)\left
[
1+T(K) g\left(s_{i}, s_{j}\right)\right]
\end{align*}

with g\left(s, s^{\prime}\right)=q \delta_{s, s^{\prime}}-1. Find C(K) and T(K).

(b) Show that
\begin{align*}
\begin{gathered}
\sum_{s=1}^{q} g\left(s, s^{\prime}\right)=0, \sum_{s=1}^{q} g\left(s_{1}, s\right) g\left(s, s_{2}\right)=q g\left(s_{1}, s_{2}\right) \\text { and } \sum_{s, s^{\prime}}^{q} g\left(s, s^{\prime}\right) g\left(s^{\prime}, s\right)=q^{2}(q-1)
\end{gathered}
\end{align*}

(c) Use the above results to calculate the free energy, and the correlation function \langle g\left(s_{m}, s_{n}\right)\rangle for a one-dimensional chain.

(d) Calculate the partition function on the square lattice to order of T^{4}. Also calculate the first term in the low-temperature expansion of this problem.

(e) By comparing the first terms in low- and high-temperature series, find a duality rule for Potts models. Don't worry about higher order graphs, they will work out! Assuming a single transition temperature, find the value of K_{c}(q).

(f) How do the higher order terms in the high-temperature series for the Potts model differ from those of the Ising model? What is the fundamental difference that sets apart the graphs for q=2 ? (This is ultimately the reason why only the Ising model is solvable.)

* Navigation
- **First Part**: [[id:4f3ca6aa-1dcc-4e74-81ef-0d6b014ee556][Boltzmann Weight Decomposition]]

* Solution

* Related Concepts
