:PROPERTIES:
:ID:       ba4848ab-8c40-4dcd-86fd-d049b8b45246
:CUSTOM_ID: 1/6
:END:
#+TITLE: Magnetic thin films
#+FILETAGS: :problem:main:spof:
#+SETUPFILE: ../../setupfile.org

Magnetic thin films: A crystalline film (simple cubic) is obtained by depositing a finite number of layers \(n\). Each atom has a three component (Heisenberg) spin, and they interact through the Hamiltonian
\begin{align*}
-\beta \mathcal{H}=\sum_{\alpha=1}^{n} \sum_{\langle i, j\rangle} J_{H} \vec{s}_{i}^{\alpha} \cdot \vec{s}_{j}^{\alpha}+\sum_{\alpha=1}^{n-1} \sum_{i} J_{V} \vec{s}_{i}^{\alpha} \cdot \vec{s}_{i}^{\alpha+1}
\end{align*}
(The unit vector \(\vec{s}_{i}^{\alpha}\) indicates the spin at site \(i\) in the \(\alpha\) th layer.) A mean-field approximation is obtained from the variational density \(\rho_{0} \propto \exp \left(-\beta \mathcal{H}_{0}\right)\), with the trial Hamiltonian
\begin{align*}
-\beta \mathcal{H}_{0}=\sum_{\alpha=1}^{n} \sum_{i} \vec{h}^{\alpha} \cdot \vec{s}_{i}^{\alpha}
\end{align*}
(Note that the most general single-site density matrix may include the higher order terms \(L_{c_{1}, \cdots, c_{p}}^{\alpha} s_{c_{1}}^{\alpha} \cdots s_{c_{1}}^{\alpha}\), where \(s_{c}\) indicates component \(c\) of the vector \(\vec{s}\).)

(a) Calculate the partition function \(Z_{0}\left(\left\{\vec{h}^{\alpha}\right\}\right)\), and \(\beta F_{0}=-\ln Z_{0}\).

(b) Obtain the magnetizations \(m_{\alpha}=\left|\left\langle\vec{s}_{i}^{\alpha}\right\rangle_{0}\right|\), and \(\left\langle\beta \mathcal{H}_{0}\right\rangle_{0}\), in terms of the Langevin function \(\mathcal{L}(h)=\operatorname{coth}(h)-1 / h\).

(c) Calculate \(\langle\beta \mathcal{H}\rangle_{0}\), with the (reasonable) assumption that all the variational fields \(\left(\left\{\vec{h}^{\alpha}\right\}\right)\) are parallel.

(d) The exact free energy, \(\beta F=-\ln Z\), satisfies the Gibbs inequality, \(\beta F \leq \beta F_{0}+\) \(\left\langle\beta \mathcal{H}-\beta \mathcal{H}_{0}\right\rangle_{0}\). Give the self-consistent equations for the magnetizations \(\left\{m_{\alpha}\right\}\) that optimize \(\beta \mathcal{H}_{0}\). How would you solve these equations numerically?

(e) Find the critical temperature, and the behavior of the magnetization in the bulk by considering the limit \(n \rightarrow \infty\). (Note that \(\lim _{m \rightarrow 0} \mathcal{L}^{-1}(m)=3 m+9 m^{3} / 5+\) \(\mathcal{O}\left(m^{5}\right)\).

(f) By linearizing the self-consistent equations, show that the critical temperature of film depends on the number of layers \(n\), as \(k T_{c}(n \gg 1) \approx k T_{c}(\infty)-J_{V} \pi^{2} /\left(3 n^{2}\right)\).
(g) Derive a continuum form of the self-consistent equations, and keep terms to cubic order in \(m\). Show that the resulting nonlinear differential equation has a solution of the form \(m(x)=m_{\text {bulk }} \tanh (k x)\). What circumstances are described by this solution?

(h) How can the above solution be modified to describe a semi-infinite system? Obtain the critical behaviors of the healing length \(\lambda \sim 1 / k\).

(i) Show that the magnetization of the surface layer vanishes as \(\left|T-T_{c}\right|\).

The result in (f) illustrates a quite general result that the transition temperature of a finite system of size \(L\), approaches its asymptotic (infinite-size) limit from below, as \(T_{c}(L)=T_{c}(\infty)-A / L^{1 / \nu}\), where \(\nu\) is the exponent controlling the divergence of the correlation length. However, some liquid crystal films appeared to violate this behavior. In fact, in these films the couplings are stronger on the surface layers, which thus order before the bulk. For a discussion of the dependence of \(T_{c}\) on the number of layers in this case, see H. Li, M. Paczuski, M. Kardar, and K. Huang, Phys. Rev. B 44, 8274 (1991).

*Next*: [[id:3b8c3d1a-2268-41a3-9dd0-86e5febd1c9a][Partition Function and Free Energy]]
